/* El Analista: escenas propias de la carrera de Derecho (lote 11).
   Ids 21000-21999. Cada raíz propia usa su centena: raíz 21k00, consecuencias 21k10 a 21k16
   (las 21k15 y 21k16 son de tercer nivel). */
module.exports = {
  carrera: "der",

  huellas: {
    l11_horas_limpias: "Facturaste solo las horas que trabajaste",
    l11_horas_infladas: "Redondeaste tus horas facturables hacia arriba",
    l11_marcaste_cambio: "Marcaste un cambio que la otra parte escondió",
    l11_declaraste: "Declaraste en un pleito con tus notas y fechas",
    l11_salvedades: "Firmaste un dictamen con todas sus salvedades",
    l11_firmaste_limpio: "Firmaste un dictamen limpio porque el cliente pagaba",
    l11_rechazaste_dictamen: "Rechazaste firmar un dictamen dudoso",
    l11_comentaste_norma: "Comentaste una norma del regulador artículo por artículo",
    l11_atajo_regulador: "Buscaste un atajo por fuera con el regulador",
    l11_fideicomiso: "Armaste un fideicomiso para una familia en guerra",
    l11_testamento_dictado: "Redactaste un testamento al dictado del cliente",
    l11_mediaste_familia: "Sentaste a una familia entera antes de firmar",
    l11_arbitro_revelado: "Revelaste un vínculo viejo antes de ser árbitro",
    l11_arbitro_callado: "Callaste un vínculo viejo al aceptar un arbitraje",
  },

  propias: [
    /* ===== 21000 Las horas facturables (junior, en un bufete ajeno) ===== */
    { id: 21000, min: 0, max: 2, empleado: true, t: "Las horas del mes no cuadran",
      x: "Cierre de mes y te faltan horas facturables para la meta. Tus compañeros redondean hacia arriba sin pudor. Tu planilla espera en blanco.",
      o: [
        { t: "Facturar solo lo que trabajaste", d: { rep: 3, cri: 2, car: -3, deja: "l11_horas_limpias",
          msg: "Entregas la planilla corta. El socio la mira, levanta una ceja y no dice nada. Todavía.",
          luego: [{ en: 1, azar: [{ p: 40, id: 21010 }, { p: 25, id: 21011 }, { p: 20, id: 21013 }, { p: 15, id: 21014 }] }] } },
        { t: "Redondear hacia arriba, como todos", d: { cash: 1500, car: 3, rep: -2, deja: "l11_horas_infladas",
          msg: "Una llamada de cinco minutos se vuelve reunión de una hora. La meta se cumple sola.",
          luego: [{ en: 1, azar: [{ p: 45, id: 21012 }, { p: 25, id: 21013 }, { p: 30, id: 21014 }] }] } },
        { t: "Pedirle trabajo de verdad a otro socio", d: { ene: -4, red: 3, car: 1,
          msg: "Tocas la puerta de otra área. Te dan un expediente que nadie quería y horas de sobra.",
          luego: [{ en: 1, azar: [{ p: 45, id: 21013 }, { p: 20, id: 21010 }, { p: 35, id: 21014 }] }] } },
      ] },

    /* ===== 21100 El borrador de compraventa (junior) ===== */
    { id: 21100, min: 0, max: 3, empleado: true, t: "La versión limpia no está tan limpia",
      x: "Comparas el borrador de compraventa con el anterior. La otra parte cambió la cláusula de indemnización y no lo marcó. El cierre es el viernes.",
      o: [
        { t: "Marcarlo en rojo y avisarle a todos", d: { cri: 4, rep: 3, ene: -2, deja: "l11_marcaste_cambio",
          msg: "Mandas el comparativo con la cláusula en rojo. El abogado de enfrente pide disculpas por un error que no fue error.",
          luego: [{ en: 2, azar: [{ p: 35, id: 21110 }, { p: 20, id: 21111 }, { p: 25, id: 21114 }, { p: 20, id: 21112 }] }] } },
        { t: "Corregirlo en silencio en tu versión", d: { cri: 2, ene: -1,
          msg: "Devuelves la cláusula a su lugar sin comentario. Si ellos juegan a no marcar, tú también sabes jugar.",
          luego: [{ en: 2, azar: [{ p: 30, id: 21112 }, { p: 30, id: 21113 }, { p: 20, id: 21110 }, { p: 20, id: 21114 }] }] } },
        { t: "Guardarlo para la mesa de negociación", d: { car: 3, rep: -1, red: 1,
          msg: "Te guardas el hallazgo. En la mesa del jueves lo sacas justo cuando piden la última concesión.",
          luego: [{ en: 2, azar: [{ p: 25, id: 21112 }, { p: 35, id: 21113 }, { p: 25, id: 21111 }, { p: 15, id: 21114 }] }] } },
      ] },

    /* ===== 21200 Testigo en un litigio ===== */
    { id: 21200, min: 1, max: 4, t: "Te citan a declarar",
      x: "Una compraventa en la que trabajaste terminó en tribunales. Una de las partes te cita como testigo. Tus notas de entonces siguen en un cajón.",
      o: [
        { t: "Declarar con tus notas y la cronología", d: { cri: 3, rep: 2, ene: -4, deja: "l11_declaraste",
          msg: "Llegas con una carpeta y fechas. El juez anota más de lo que esperabas.",
          luego: [{ en: 1, azar: [{ p: 40, id: 21210 }, { p: 20, id: 21211 }, { p: 15, id: 21212 }, { p: 25, id: 21214 }] }] } },
        { t: "Decir lo mínimo y recordar poco", d: { ene: -1, rep: -1,
          msg: "«No lo recuerdo con precisión» se vuelve tu frase favorita. Funciona, hasta que deja de funcionar.",
          luego: [{ en: 1, azar: [{ p: 40, id: 21211 }, { p: 35, id: 21212 }, { p: 25, id: 21213 }] }] } },
        { t: "Buscar un error formal en la citación", d: { cri: 2, ene: -2, red: -1,
          msg: "Encuentras un error en la notificación y la citación se cae. El abogado que te citó anota tu nombre.",
          luego: [{ en: 2, azar: [{ p: 55, id: 21213 }, { p: 45, id: 21212 }] }] } },
      ] },

    /* ===== 21300 El dictamen dudoso ===== */
    { id: 21300, min: 2, max: 5, t: "El cliente quiere tu firma en un dictamen",
      x: "Un cliente necesita una opinión legal que diga que su estructura cumple la norma cambiaria. El banco la exige para pagar. Tu lectura es menos optimista.",
      o: [
        { t: "Firmarlo con todas las salvedades", d: { cash: 1500, rep: 3, cri: 3, deja: "l11_salvedades",
          msg: "Tu dictamen dice que sí, pero con cuatro condiciones. El cliente lo lee dos veces y no sonríe ninguna.",
          luego: [{ en: 2, azar: [{ p: 35, id: 21310 }, { p: 25, id: 21311 }, { p: 15, id: 21313 }, { p: 25, id: 21314 }] }] } },
        { t: "Firmarlo limpio, como lo pide", d: { cash: 6000, red: 2, rep: -1, deja: "l11_firmaste_limpio",
          msg: "Una página, cero salvedades y tu firma al pie. El cliente paga sin regatear, que siempre es mala señal.",
          luego: [{ en: 2, azar: [{ p: 45, id: 21310 }, { p: 55, id: 21312 }] }] } },
        { t: "Rechazar el encargo", d: { rep: 2, red: -3, deja: "l11_rechazaste_dictamen",
          msg: "Le dices que no puedes firmar eso. Te mira como quien mira un mueble que no sirve.",
          luego: [{ en: 1, azar: [{ p: 55, id: 21313 }, { p: 45, id: 21314 }] }] } },
      ] },

    /* ===== 21400 La norma del regulador ===== */
    { id: 21400, min: 2, max: 5, t: "El regulador publica un proyecto de norma",
      x: "La superintendencia de valores pone en consulta una norma que obligaría a los fondos de tus clientes a rehacer sus contratos. Hay un mes para opinar.",
      o: [
        { t: "Comentarla artículo por artículo", d: { cri: 4, rep: 2, ene: -4, deja: "l11_comentaste_norma",
          msg: "Doce páginas, cada objeción con su artículo y su alternativa. Las mandas el último día, a la última hora.",
          luego: [{ en: 1, azar: [{ p: 30, id: 21410 }, { p: 30, id: 21411 }, { p: 20, id: 21413 }, { p: 20, id: 21414 }] }] } },
        { t: "Llamar a un conocido de la superintendencia", d: { red: 3, rep: -1, deja: "l11_atajo_regulador",
          msg: "Un café con alguien que conoce a alguien. Te promete que tu punto va a llegar a la mesa correcta.",
          luego: [{ en: 1, azar: [{ p: 35, id: 21412 }, { p: 30, id: 21411 }, { p: 20, id: 21410 }, { p: 15, id: 21414 }] }] } },
        { t: "Preparar a tus clientes para cumplirla", d: { mod: 2, cash: 2000, ene: -2,
          msg: "Mientras otros pelean la norma, tú ya tienes los contratos nuevos. La adaptación se la cobras a cada cliente.",
          luego: [{ en: 1, azar: [{ p: 50, id: 21411 }, { p: 30, id: 21414 }, { p: 20, id: 21413 }] }] } },
      ] },

    /* ===== 21500 Sucesiones: el patriarca ===== */
    { id: 21500, min: 3, max: 6, t: "El patriarca quiere dejar fuera a un hijo",
      x: "Un cliente de toda la vida, dueño de un grupo familiar, te pide redactar su testamento. Quiere que uno de sus cuatro hijos no herede ni una acción.",
      o: [
        { t: "Explicarle la ley y armar un fideicomiso", d: { cash: 2000, cri: 4, rep: 3, ene: -3, deja: "l11_fideicomiso",
          msg: "La ley reserva una parte a cada hijo. Armas un fideicomiso donde ese hijo hereda dinero, pero no votos.",
          luego: [{ en: 2, azar: [{ p: 40, id: 21510 }, { p: 25, id: 21513 }, { p: 35, id: 21514 }] }] } },
        { t: "Redactar lo que pide, sin preguntas", d: { cash: 3000, red: 2, cri: -2, deja: "l11_testamento_dictado",
          msg: "Escribes lo que te dicta. Firma, te da la mano y dice que eres de los pocos que no le llevan la contraria.",
          luego: [{ en: 2, azar: [{ p: 60, id: 21511 }, { p: 40, id: 21514 }] }] } },
        { t: "Sentar a la familia antes de firmar", d: { red: 2, rep: 1, ene: -5, deja: "l11_mediaste_familia",
          msg: "Le propones una reunión con los cuatro hijos. Dice que lo va a pensar, con cara de no pensarlo.",
          luego: [{ en: 1, azar: [{ p: 40, id: 21512 }, { p: 35, id: 21513 }, { p: 25, id: 21514 }] }] } },
      ] },

    /* ===== 21600 El arbitraje ===== */
    { id: 21600, min: 4, max: 6, t: "Te nombran árbitro",
      x: "La cámara de comercio te propone como árbitro en una disputa entre dos fondos. Repasas las partes: uno de los socios fue cliente tuyo hace años.",
      o: [
        { t: "Aceptar y revelar el vínculo por escrito", d: { cash: 3000, rep: 4, cri: 2, ene: -3, deja: "l11_arbitro_revelado",
          msg: "Escribes dos párrafos sobre aquel cliente y los mandas a las partes. Nadie objeta, de momento.",
          luego: [{ en: 1, azar: [{ p: 45, id: 21610 }, { p: 25, id: 21612 }, { p: 30, id: 21613 }] }] } },
        { t: "Aceptar sin mencionarlo, fue hace mucho", d: { cash: 4000, rep: 1, ene: -3, deja: "l11_arbitro_callado",
          msg: "Fue hace años y era otro asunto. Firmas la aceptación y te preparas para leer mucho.",
          luego: [{ en: 1, azar: [{ p: 40, id: 21611 }, { p: 30, id: 21610 }, { p: 30, id: 21612 }] }] } },
        { t: "Declinar el nombramiento", d: { ene: 2, red: -2,
          msg: "Declinas con una carta cortés. La cámara anota tu nombre en otra lista: la de los que dicen que no.",
          luego: [{ en: 2, azar: [{ p: 55, id: 21613 }, { p: 45, id: 21614 }] }] } },
      ] },
  ],

  escenas: [
    /* ===== consecuencias de 21000 (horas facturables) ===== */
    { id: 21010, empleado: true, por: "Cerraste un mes de horas facturables", t: "Te ponen en revisión de desempeño",
      x: "Recursos humanos te cita: tus horas están por debajo de la media del piso. Te dan un trimestre para mejorar o para buscar otro piso.",
      o: [
        { t: "Mostrar la calidad de lo que entregaste", d: { cri: 3, rep: 2, ene: -2, msg: "Llevas tres escritos que ganaron. Te escuchan, asienten y te recuerdan que la calidad no se factura." } },
        { t: "Aceptar más casos aunque no duermas", d: { cash: 1000, car: 3, ene: -6, msg: "Sales de la revisión con dos expedientes nuevos y ojeras de regalo. El trimestre se cumple." } },
        { t: "Empezar a buscar otro bufete", d: { red: 3, car: -2, ene: 2, msg: "Actualizas el currículum y tomas tres cafés. Nadie te ofrece nada todavía, pero ya no te asusta la revisión." } },
      ] },
    { id: 21011, empleado: true, por: "Facturaste solo las horas que trabajaste", t: "El cliente audita cada hora",
      x: "Un cliente grande revisa un año de facturas con lupa. Las tuyas son las únicas que no tienen nada que explicar. El socio lo nota.",
      o: [
        { t: "Ofrecerte a ordenar la defensa del equipo", d: { car: 4, red: 2, ene: -4, msg: "Te pasas dos semanas explicando planillas ajenas. El socio aprende tu nombre de una vez." } },
        { t: "Mantener distancia y que cada uno responda", d: { rep: 2, red: -2, msg: "No defiendes a nadie. Tus compañeros tampoco te van a defender a ti el día que toque." } },
        { t: "Pedir que te pasen a la cuenta de ese cliente", d: { car: 3, red: 2, ene: -2, msg: "El cliente pide expresamente que lleves sus asuntos. Ahora tus horas pesan, y se revisan." } },
      ] },
    { id: 21012, empleado: true, por: "Redondeaste tus horas hacia arriba", t: "El auditor encontró tus llamadas",
      x: "El cliente audita un año de facturas. Tus llamadas de cinco minutos que se volvieron reuniones de una hora están marcadas en amarillo.",
      o: [
        { t: "Reconocerlo y devolver lo cobrado", d: { cash: -2000, rep: -2, cri: 3, msg: "Devuelves la diferencia y pides disculpas por escrito. El socio te odia una semana; el cliente se queda." } },
        { t: "Decir que todos lo hacen y señalar a otros", d: { rep: -6, red: -5, msg: "Tenías razón y no sirvió de nada. Ahora el piso entero sabe que no se te cuentan secretos." } },
        { t: "Sostener que fueron reuniones", d: { ene: -3, rep: -1, msg: "Juras que cada llamada fue una reunión de verdad. El auditor anota, sin levantar la vista.",
          luego: [{ en: 1, s: "rep", azar: [{ p: 55, id: 21015, bueno: true }, { p: 45, id: 21016, bueno: false }] }] } },
      ] },
    { id: 21013, empleado: true, por: "Cerraste un mes de horas facturables", t: "Te dan el caso grande del año",
      x: "El socio necesita a alguien con hambre de horas y buen estómago. Es un arbitraje que se va a comer tus fines de semana durante un año.",
      o: [
        { t: "Aceptar y meterte de lleno", d: { cash: 2000, car: 6, ene: -7, msg: "Un año de escritos y audiencias. Al final sabes más de ese caso que el cliente de su propia empresa." } },
        { t: "Aceptar con condiciones de horario", d: { car: 2, rep: 1, ene: -2, msg: "Pones límite a los domingos. El socio acepta, aunque te llama igual algún domingo." } },
        { t: "Pasar, ya tienes bastante", d: { ene: 3, car: -2, msg: "Se lo dan a tu compañero de escritorio. Lo ves pasar con el expediente bajo el brazo y café en la mano." } },
      ] },
    { id: 21014, empleado: true, por: "Cerraste un mes de horas facturables", t: "Un compañero te pide prestadas horas",
      x: "Tu compañero de escritorio no llega a la meta y te pide cargar a tu cliente unas horas que hizo para otro. Nadie lo notaría.",
      o: [
        { t: "Negarte con amabilidad", d: { rep: 2, red: -3, msg: "Le dices que no. Te dice que lo entiende, y desde ese día almuerza en otra mesa." } },
        { t: "Hacerle el favor por esta vez", d: { red: 3, rep: -3, msg: "Le cargas las horas. Te lo agradece con un abrazo y con la certeza de que habrá una segunda vez." } },
        { t: "Ayudarle a conseguir trabajo real", d: { red: 2, cri: 1, ene: -3, msg: "Le pasas un expediente tuyo que te sobraba. Llega a la meta con horas que sí existieron." } },
      ] },
    { id: 21015, empleado: true, por: "Juraste ante el auditor que tus horas eran reales", t: "El auditor cierra el tema",
      x: "El auditor no puede probar nada y cierra el informe. El socio te felicita en el pasillo y, desde entonces, revisa cada planilla tuya.",
      o: [
        { t: "Facturar limpio de aquí en adelante", d: { rep: 2, cri: 2, car: -1, msg: "Tus planillas se vuelven aburridas y exactas. El socio deja de revisarlas al año." } },
        { t: "Seguir igual, ya pasó la tormenta", d: { cash: 1500, rep: -3, msg: "Sigues redondeando. La próxima auditoría no la va a hacer el mismo auditor." } },
      ] },
    { id: 21016, empleado: true, por: "Juraste ante el auditor que tus horas eran reales", t: "El colegio de abogados te cita",
      x: "El cliente presentó una queja ante el colegio de abogados. Hay audiencia disciplinaria y tu matrícula para ejercer está sobre la mesa.",
      o: [
        { t: "Contratar defensa y reconocer el exceso", d: { cash: -3000, rep: -3, cri: 3, msg: "Te queda una amonestación en el registro. Duele menos que perder la matrícula, que era la otra opción." } },
        { t: "Defenderte tú y negarlo todo", d: { rep: -6, ene: -5, car: -3, msg: "El tribunal disciplinario no te cree. Tres meses de suspensión y una nota en tu expediente para siempre." } },
      ] },

    /* ===== consecuencias de 21100 (la cláusula de indemnización) ===== */
    { id: 21110, empleado: true, por: "Revisaste una compraventa línea por línea", t: "El socio quiere tus ojos en cada cierre",
      x: "Desde aquella compraventa, el socio no firma nada sin que lo leas tú antes. Es un honor que se paga en madrugadas.",
      o: [
        { t: "Leerlos todos", d: { car: 5, cri: 2, ene: -6, msg: "Lees cada contrato del piso. Sabes dónde se esconden las trampas y ya no recuerdas cómo era dormir." } },
        { t: "Enseñarle a otro a hacerlo", d: { red: 3, cri: 2, ene: -1, msg: "Armas una lista de lo que siempre revisas y entrenas a un asociado. El socio aprueba, a regañadientes." } },
        { t: "Pedir un bono por la carga", d: { cash: 2000, rep: -1, msg: "El socio te lo da, con la cara de quien anota un favor. La próxima evaluación la recordarás." } },
      ] },
    { id: 21111, empleado: true, por: "Revisaste una compraventa línea por línea", t: "El abogado de enfrente te llama",
      x: "El abogado de la otra parte en aquella compraventa te llama. Dice que necesita en su equipo a alguien que lea como tú.",
      o: [
        { t: "Usar la oferta para negociar en casa", d: { cash: 2000, red: 2, rep: -1, msg: "Tu socio iguala la oferta sin pestañear y te mira distinto desde entonces. Para bien y para mal." } },
        { t: "Agradecer y quedarte donde estás", d: { red: 3, rep: 2, msg: "Le dices que no, con elegancia. Te dice que la puerta queda abierta y lo dice en serio." } },
        { t: "Pedirle que te mande clientes, no ofertas", d: { red: 4, car: 2, ene: -2, msg: "Se ríe y al mes te refiere un asunto que su firma no puede llevar. Así empiezan las carreras." } },
      ] },
    { id: 21112, empleado: true, por: "Revisaste una cláusula de indemnización", t: "La cláusula aguantó el reclamo",
      x: "Aparece una deuda fiscal escondida de antes del cierre. Tu cliente reclama y la cláusula que cuidaste lo cubre hasta el último peso.",
      o: [
        { t: "Llevar tú el reclamo", d: { cash: 1500, car: 4, rep: 3, ene: -3, msg: "Escribes el reclamo citando tu propia cláusula. La otra parte paga sin ir a juicio." } },
        { t: "Dejárselo al área de litigios", d: { red: 2, ene: 1, msg: "Litigios gana y se lleva el crédito. Tú te quedas con la satisfacción, que no se deposita." } },
        { t: "Pedir que conste quién la redactó", d: { car: 2, rep: 2, red: -2, msg: "El socio lo menciona en la junta. Dos compañeros te felicitan y uno deja de saludarte." } },
      ] },
    { id: 21113, empleado: true, por: "Revisaste una cláusula de indemnización", t: "La cláusula volvió a cambiar",
      x: "Aparece una deuda fiscal escondida. Buscas la cláusula y descubres que en la versión firmada volvió a decir lo que querían ellos.",
      o: [
        { t: "Contárselo al socio de inmediato", d: { cri: 3, rep: -2, car: -2, msg: "El socio escucha sin interrumpir. Te dice que el error fue de todos, y lo anota a tu nombre." } },
        { t: "Litigar que ese cambio nunca se negoció", d: { cri: 2, ene: -4, msg: "Juntas correos, versiones y fechas para probar que el cambio entró a escondidas. El cliente apuesta contigo.",
          luego: [{ en: 1, s: "cri", azar: [{ p: 50, id: 21115, bueno: true }, { p: 50, id: 21116, bueno: false }] }] } },
        { t: "Callar y esperar que nadie revise", d: { rep: -5, ene: -3, msg: "Alguien revisa. Siempre alguien revisa. Te enteras por un correo con copia a medio bufete." } },
      ] },
    { id: 21114, empleado: true, por: "Revisaste una compraventa línea por línea", t: "Te piden los contratos de un fondo",
      x: "La firma estructura su primer fondo de inversión y el socio quiere que redactes el acuerdo entre los inversionistas. Nunca has hecho uno.",
      o: [
        { t: "Aceptar y estudiar los de la competencia", d: { mod: 2, cri: 4, car: 4, ene: -5, msg: "Lees cuarenta acuerdos ajenos y escribes el tuyo. El primer inversionista lo firma sin comentarios." } },
        { t: "Pedir que te acompañe alguien con experiencia", d: { red: 2, cri: 2, car: 1, msg: "Te asignan a una asociada veterana. Aprendes rápido y ella se queda con la mitad del mérito." } },
        { t: "Declinar y seguir en compraventas", d: { ene: 2, car: -2, msg: "Se lo dan a otro. El fondo sale bien y en el piso empiezan a hablar de esa persona, no de ti." } },
      ] },
    { id: 21115, empleado: true, por: "Litigaste una cláusula cambiada sin avisar", t: "El tribunal acepta tu argumento",
      x: "Probaste con los correos que aquel cambio nunca se negoció. El tribunal anula la cláusula y tu cliente cobra. El socio te invita a almorzar.",
      o: [
        { t: "Escribir un artículo sobre el caso", d: { rep: 4, red: 2, ene: -2, msg: "Lo publica una revista jurídica. Desde entonces, en tu gremio comparan cada versión dos veces." } },
        { t: "Cobrar el éxito en tu bono", d: { cash: 3000, car: 2, msg: "El bono llega con una nota del socio. La nota vale más, pero el bono paga el alquiler." } },
      ] },
    { id: 21116, empleado: true, por: "Litigaste una cláusula cambiada sin avisar", t: "Pierden el reclamo",
      x: "El tribunal dice que la versión firmada manda, la hayan marcado o no. El cliente pierde y alguien tiene que explicar quién no comparó.",
      o: [
        { t: "Asumirlo tú ante el cliente", d: { cri: 4, rep: -2, car: -3, msg: "Das la cara en la reunión. El cliente no te perdona, pero el socio no lo olvida, y eso juega a tu favor." } },
        { t: "Señalar que el cierre fue apurado", d: { rep: -4, red: -3, msg: "Es verdad y no ayuda. Todos estaban en ese cierre apurado y nadie te lo agradece." } },
      ] },

    /* ===== consecuencias de 21200 (testigo) ===== */
    { id: 21210, por: "Te citaron como testigo en un litigio", t: "Tu declaración decide el caso",
      x: "La sentencia cita tu testimonio en tres párrafos. La parte que ganó te manda flores. La que perdió, una carta de su abogado.",
      o: [
        { t: "Ignorar la carta", d: { ene: 1, rep: 1, msg: "La carta amenaza con todo y no hace nada. Las flores se marchitan antes que el pleito." } },
        { t: "Responderla con tu propio abogado", d: { cash: -1500, cri: 2, rep: 2, msg: "Una respuesta de dos páginas y no vuelven a escribir. Pagaste por dormir en paz." } },
        { t: "Ofrecerle tus servicios a la parte ganadora", d: { cash: 2000, red: 4, rep: -2, msg: "Te contrata. En el gremio alguien murmura que el testigo terminó cobrando, y no le falta razón." } },
      ] },
    { id: 21211, por: "Te citaron como testigo en un litigio", t: "El contrainterrogatorio te desarma",
      x: "El abogado contrario saca un correo tuyo de aquel cierre que contradice lo que acabas de decir. La sala entera te mira.",
      o: [
        { t: "Reconocer el error y explicar el contexto", d: { cri: 4, rep: -1, ene: -2, msg: "Explicas qué sabías entonces y qué sabes ahora. El juez asiente, que en esa sala ya es mucho." } },
        { t: "Insistir en tu versión", d: { rep: -3, ene: -3, msg: "Repites lo dicho con más firmeza. El abogado contrario sonríe y no pregunta nada más.",
          luego: [{ en: 1, s: "rep", azar: [{ p: 40, id: 21216, bueno: true }, { p: 60, id: 21215, bueno: false }] }] } },
      ] },
    { id: 21212, por: "Te citaron como testigo en un litigio", t: "Ahora buscan a los asesores",
      x: "Aquel pleito terminó en un acuerdo caro. La parte que pagó busca a quién culpar, y los asesores de la compraventa encabezan la lista.",
      o: [
        { t: "Revisar tus papeles con un abogado", d: { cash: -1500, cri: 3, ene: -2, msg: "Tus papeles aguantan. El abogado te cobra por confirmarlo y te recomienda guardar todo, siempre." } },
        { t: "Llamar a la parte y explicar tu rol", d: { red: 2, rep: 1, ene: -2, msg: "Una conversación larga y franca. Te borran de la lista y te agregan a la de contactos." } },
        { t: "Esperar a que llegue algo por escrito", d: { ene: 2, rep: -1, msg: "No llega nada. Pero en dos reuniones del sector notas que alguien baja la voz cuando entras." } },
      ] },
    { id: 21213, por: "Te citaron como testigo en un litigio", t: "El abogado que te citó vuelve",
      x: "Aquel abogado que te citó ahora pelea otro caso contra un cliente tuyo. Pide documentos tuyos y conoce bien tus mañas.",
      o: [
        { t: "Entregar lo que exige la ley, ni más ni menos", d: { cri: 3, rep: 2, ene: -3, msg: "Entregas cada papel debido y ninguno de sobra. No encuentra nada y lo sabe antes que tú." } },
        { t: "Pelear cada documento", d: { car: 2, rep: -1, ene: -5, msg: "Seis meses de incidentes y escritos. Ganas casi todos y el cliente paga cada uno." } },
        { t: "Proponerle una reunión para negociar", d: { red: 3, cri: 1, msg: "Café, dos horas y un acuerdo razonable. Te dice que la próxima vez no te va a citar de testigo." } },
      ] },
    { id: 21214, por: "Declaraste en un pleito con tus notas", t: "Te buscan como perito",
      x: "Un bufete de litigio leyó tu declaración y quiere contratarte como perito en otro pleito de compraventa. Paga bien y expone más.",
      o: [
        { t: "Aceptar", d: { cash: 4000, rep: 3, ene: -4, msg: "Tu informe pericial tiene cuarenta páginas y ninguna sobra. El otro perito tiene ochenta y se le nota." } },
        { t: "Aceptar solo si no hay choque con tus clientes", d: { cash: 2000, rep: 4, cri: 1, ene: -2, msg: "Revisas las partes antes de firmar. Aceptas tarde, pero nadie te puede recusar después." } },
        { t: "Declinar, ya tuviste suficiente tribunal", d: { ene: 3, red: -1, msg: "Prefieres los contratos a las salas de audiencia. Los contratos, al menos, no te contrainterrogan." } },
      ] },
    { id: 21215, por: "Insististe en tu versión ante el tribunal", t: "Te denuncian por falso testimonio",
      x: "La parte que perdió presenta una denuncia penal contra ti. Lo más probable es que no prospere, pero tu nombre ya figura en el expediente.",
      o: [
        { t: "Contratar al mejor penalista que puedas", d: { cash: -5000, rep: 1, ene: -3, msg: "La denuncia se archiva en seis meses. Te queda la factura y una lección sobre guardar los correos." } },
        { t: "Defenderte con tus propios medios", d: { cash: -500, cri: 3, rep: -2, ene: -7, msg: "La denuncia se archiva, pero tardas un año y lo cuentas en cada cena. Nadie te pidió que lo contaras." } },
      ] },
    { id: 21216, por: "Insististe en tu versión ante el tribunal", t: "El juez lo deja pasar",
      x: "El juez anota la contradicción y sigue. En la sentencia tu testimonio aparece como «poco confiable». Lo lee todo el gremio.",
      o: [
        { t: "Escribirles a tus clientes antes de que pregunten", d: { rep: 1, red: 2, ene: -2, msg: "Explicas el contexto antes de que llegue el chisme. Casi todos te creen; uno pide otro abogado." } },
        { t: "Hacer como que no pasó nada", d: { rep: -3, ene: 1, msg: "Nadie te lo menciona. Te lo mencionan a tus espaldas, que es peor." } },
      ] },

    /* ===== consecuencias de 21300 (el dictamen) ===== */
    { id: 21310, por: "Te pidieron firmar un dictamen dudoso", t: "El banco paga y el cliente vuelve",
      x: "El desembolso salió y la estructura funciona. El cliente vuelve con otra operación, y con otra opinión que quiere ver firmada.",
      o: [
        { t: "Aceptar y aplicar el mismo rigor", d: { cash: 3000, rep: 2, ene: -3, msg: "Mismo cliente, salvedades donde toquen. Se queja, paga y vuelve. Así se construye una cartera." } },
        { t: "Aceptar y subir tus honorarios", d: { cash: 5000, red: -1, msg: "Acepta el precio con una mueca. Te paga más y empieza a pedirte respuestas más rápidas." } },
        { t: "Esta vez, no", d: { rep: 1, red: -2, msg: "Le dices que la segunda estructura no la firmas. Se va sin discutir, que es su forma de discutir." } },
      ] },
    { id: 21311, por: "Firmaste un dictamen con salvedades", t: "El regulador lee tus salvedades",
      x: "El ente cambiario investiga la estructura del cliente. Tu dictamen es el único que avisó de los riesgos. Te llaman a explicarlo.",
      o: [
        { t: "Ir y explicarlo con detalle", d: { rep: 5, cri: 2, red: -2, ene: -4, msg: "Declaras como testigo y nadie te investiga. El cliente no te vuelve a hablar; el regulador te recuerda." } },
        { t: "Ir con abogado propio y decir lo justo", d: { cash: -2000, rep: 2, cri: 2, msg: "Respondes cada pregunta con tu dictamen en la mano. Cero frases de más, cero problemas después." } },
      ] },
    { id: 21312, por: "Firmaste un dictamen limpio para un cliente", t: "Tu firma está en el expediente",
      x: "El ente cambiario investiga la estructura del cliente. Tu dictamen sin salvedades está en la primera página del expediente.",
      o: [
        { t: "Colaborar y explicar cómo lo redactaste", d: { cri: 2, ene: -4, msg: "Les cuentas qué te mostró el cliente y qué no. El investigador toma nota de todo, incluido tu tono.",
          luego: [{ en: 1, s: "rep", azar: [{ p: 50, id: 21315, bueno: true }, { p: 50, id: 21316, bueno: false }] }] } },
        { t: "Culpar al cliente por ocultarte datos", d: { cri: 1, rep: -4, red: -5, msg: "Puede que sea cierto. El cliente lo niega y desde ese día habla mal de ti en cada almuerzo." } },
        { t: "Contratar defensa y guardar silencio", d: { cash: -4000, rep: -2, ene: -3, msg: "Tu abogado responde por ti con monosílabos. El caso se alarga y tu nombre sigue en la primera página." } },
      ] },
    { id: 21313, por: "Te pidieron firmar un dictamen dudoso", t: "El cliente se fue con otro",
      x: "El cliente consiguió su opinión en otro bufete, más barata y sin peros. Te enteras en una cena, de boca de un tercero.",
      o: [
        { t: "Desearle suerte, de verdad", d: { rep: 1, ene: 2, msg: "Brindas por él sin ironía. Nadie en la mesa lo nota, que es justo lo que querías." } },
        { t: "Contar en la cena por qué se fue", d: { rep: -3, red: -2, msg: "Lo cuentas con detalle. Al día siguiente dos clientes tuyos se preguntan qué contarás de ellos." } },
        { t: "Mandarle un mensaje por si necesita plan B", d: { red: 2, ene: -1, msg: "No responde. Seis meses después sí, con una urgencia y con un tono mucho más humilde." } },
      ] },
    { id: 21314, por: "Te pidieron firmar un dictamen dudoso", t: "Tu firma ya no se consigue fácil",
      x: "Un banco empieza a pedir a sus clientes que traigan opinión tuya. Dice que tus dictámenes se pueden leer sin miedo.",
      o: [
        { t: "Aprovechar y subir tarifas", d: { cash: 5000, car: 3, rep: -1, msg: "Los clientes pagan lo que pides. Algunos se van, y los que se quedan ya no regatean." } },
        { t: "Mantener precios y crecer en volumen", d: { cash: 3000, car: 3, red: 2, ene: -5, msg: "La fila de clientes llega a la escalera. Tu firma vale mucho y tu tiempo cada día menos." } },
        { t: "Atender solo lo que puedas revisar bien", d: { cash: 1000, rep: 3, ene: 1, msg: "Dices que no a la mitad. La otra mitad confirma que tu firma sigue siendo difícil de conseguir." } },
      ] },
    { id: 21315, por: "Colaboraste tras firmar un dictamen limpio", t: "Declaras como testigo y nada más",
      x: "El investigador concluye que el cliente te ocultó documentos. Quedas fuera del caso, aunque tu dictamen se lee en voz alta en la audiencia.",
      o: [
        { t: "Poner salvedades a todo de aquí en adelante", d: { cri: 3, rep: 2, cash: -1000, msg: "Tus dictámenes se vuelven más largos y algo más baratos de vender. Duermes mejor." } },
        { t: "Seguir como siempre, ya pasó", d: { cash: 2000, rep: -2, msg: "Sigues firmando limpio a quien paga. El investigador, que tiene buena memoria, también sigue ahí." } },
      ] },
    { id: 21316, por: "Colaboraste tras firmar un dictamen limpio", t: "El colegio te suspende",
      x: "El tribunal disciplinario concluye que firmaste sin diligencia. Seis meses sin poder firmar. Tus clientes se enteran antes que tú.",
      o: [
        { t: "Usar el tiempo para estudiar y volver", d: { cash: -3000, cri: 4, ene: 3, car: -4, msg: "Seis meses de libros y nada de firmas. Vuelves con menos clientes y mejor criterio." } },
        { t: "Apelar la sanción", d: { cash: -2000, rep: -1, ene: -4, msg: "La apelación tarda más que la suspensión. Cuando llega el fallo, ya no importa." } },
      ] },

    /* ===== consecuencias de 21400 (la norma) ===== */
    { id: 21410, por: "Opinaste sobre una norma del regulador", t: "Tus cambios quedaron en la norma",
      x: "La norma final sale con dos cambios que pediste casi palabra por palabra. Nadie lo dice en voz alta, pero en el gremio se sabe.",
      o: [
        { t: "Dar una charla sobre la norma nueva", d: { rep: 4, red: 3, ene: -3, msg: "Sala llena en la cámara de fondos. Explicas una norma que en parte escribiste tú. Nadie pregunta cómo." } },
        { t: "Ofrecer la adaptación a los clientes", d: { cash: 3000, car: 2, ene: -2, msg: "Nadie conoce mejor esos dos artículos. Lo cobras como corresponde." } },
        { t: "Guardar perfil bajo", d: { rep: 1, ene: 2, msg: "No presumes nada. El regulador lo agradece y te tiene en cuenta para la próxima consulta." } },
      ] },
    { id: 21411, por: "Opinaste sobre una norma del regulador", t: "La norma sale igual que el borrador",
      x: "Nadie escuchó a nadie. La norma sale tal cual y los fondos tienen seis meses para rehacer contratos. El teléfono no para.",
      o: [
        { t: "Atender a todos aunque no duermas", d: { cash: 5000, car: 3, ene: -7, msg: "Seis meses de contratos en serie. Cobras bien y aprendes a dormir en los taxis." } },
        { t: "Escoger los clientes que mejor pagan", d: { cash: 3000, red: -3, msg: "Te quedas con los grandes. Los pequeños se acuerdan de que no les contestaste." } },
        { t: "Armar una plantilla y repartir el trabajo", d: { mod: 3, cash: 2500, ene: -3, msg: "Un contrato modelo, tres asociados y una lista de control. Sale rápido y casi sin errores." } },
      ] },
    { id: 21412, por: "Hablaste por fuera con alguien del regulador", t: "Se publica quién habló con quién",
      x: "Un periódico publica las reuniones informales de la superintendencia durante la consulta. Tu café aparece con fecha y hora.",
      o: [
        { t: "Dar la cara y explicar qué se habló", d: { cri: 2, rep: -1, ene: -3, msg: "Cuentas qué dijiste y qué no. Fue un café aburrido y tu explicación también. Eso te salva." } },
        { t: "No decir nada y esperar que pase", d: { rep: -4, ene: 1, msg: "Pasa, pero tarda. Durante meses tu nombre sale cada vez que alguien escribe sobre cabildeo." } },
        { t: "Echarle la culpa a tu contacto", d: { rep: -5, red: -6, msg: "Tu contacto pierde el puesto. Tú pierdes al contacto y a todos los que lo conocían." } },
      ] },
    { id: 21413, por: "Opinaste sobre una norma del regulador", t: "El regulador te invita a una mesa técnica",
      x: "La superintendencia arma un grupo para redactar el reglamento de la norma. Quiere a alguien del sector que sepa leer y escribir contratos.",
      o: [
        { t: "Aceptar, aunque no se cobra", d: { rep: 5, red: 4, car: 2, ene: -5, msg: "Un año de reuniones sin pago. Sales conociendo a todo el regulador, y el regulador a ti." } },
        { t: "Aceptar y contárselo a tus clientes", d: { cash: 2000, red: 3, rep: -3, msg: "Tus clientes se enteran de todo antes que nadie. Alguien en la mesa se da cuenta de que se filtra." } },
        { t: "Declinar, no tienes tiempo", d: { ene: 2, red: -2, msg: "Invitan a otro. Ese otro será, dentro de un tiempo, el que todos llamen cuando haya dudas." } },
      ] },
    { id: 21414, por: "Opinaste sobre una norma del regulador", t: "Un cliente quiere impugnar la norma",
      x: "Un fondo grande quiere pedir la nulidad de la norma ante el tribunal administrativo. Te pide que lleves el caso y dice que el costo no importa.",
      o: [
        { t: "Llevar el caso", d: { car: 3, ene: -4, msg: "Presentas la demanda con cada artículo desmontado. La superintendencia contesta con un ejército.",
          luego: [{ en: 2, s: "cri", azar: [{ p: 45, id: 21415, bueno: true }, { p: 55, id: 21416, bueno: false }] }] } },
        { t: "Recomendar cumplir y no pelear", d: { cri: 3, rep: 1, red: -2, msg: "Le explicas que el pleito es largo y la norma, defendible. Se va con otro bufete que sí quiere pelear." } },
        { t: "Llevarlo, pero cobrar por adelantado", d: { cash: 5000, rep: -1, ene: -4, msg: "Cobras primero y litigas después. El cliente acepta, aunque nota que confías poco en el resultado." } },
      ] },
    { id: 21415, por: "Impugnaste una norma del regulador", t: "El tribunal anula un artículo",
      x: "Después de un pleito largo, el tribunal anula un artículo de la norma. Uno solo, pero el que importaba. Los demás fondos te llaman.",
      o: [
        { t: "Atenderlos a todos", d: { cash: 6000, car: 4, ene: -5, msg: "Cada fondo quiere saber qué cambia para él. Cobras a cada uno la misma explicación." } },
        { t: "Escribir el caso para una revista jurídica", d: { rep: 4, cri: 2, ene: -1, msg: "El artículo se cita en la facultad. Ahora hay estudiantes que conocen tu nombre de los apuntes." } },
      ] },
    { id: 21416, por: "Impugnaste una norma del regulador", t: "Pierdes contra el regulador",
      x: "El tribunal confirma la norma entera. Tu cliente pagó un pleito largo para nada, y la superintendencia ya sabe muy bien tu nombre.",
      o: [
        { t: "Recomponer la relación con la superintendencia", d: { red: 2, rep: 1, ene: -3, msg: "Pides una reunión y vas sin cliente. Te reciben con frialdad y te despiden con algo menos de frío." } },
        { t: "Apelar a la instancia siguiente", d: { car: 1, rep: -1, ene: -4, msg: "Tu cliente paga otra ronda. En la superintendencia ya tienen una carpeta con tu nombre en el lomo." } },
      ] },

    /* ===== consecuencias de 21500 (el testamento) ===== */
    { id: 21510, por: "Armaste un fideicomiso para un patriarca", t: "El hijo excluido demanda",
      x: "Murió el patriarca. El hijo que quería dejar fuera demanda, pero el fideicomiso le da su parte y le quita los votos. Su abogado busca grietas.",
      o: [
        { t: "Defender la estructura tú", d: { cash: 2000, car: 4, rep: 4, ene: -5, msg: "Un año de audiencias. El fideicomiso aguanta cada golpe y tu nombre empieza a sonar en sucesiones." } },
        { t: "Ofrecerle al hijo un acuerdo dentro del fideicomiso", d: { red: 3, rep: 2, cri: 2, msg: "Le das una silla con voz pero sin voto. Firma, refunfuña y por primera vez en años va a una junta." } },
        { t: "Pasarle el caso a un litigante", d: { ene: 2, car: -1, msg: "El litigante gana y factura el triple que tú. La estructura era tuya; el aplauso, de él." } },
      ] },
    { id: 21511, por: "Redactaste un testamento al dictado del cliente", t: "El testamento se cae en tribunales",
      x: "Murió el patriarca. El hijo excluido impugna y el juez le da la razón: la ley le reservaba su parte. La familia pregunta quién redactó eso.",
      o: [
        { t: "Asumirlo ante la familia", d: { cri: 4, rep: -3, red: -1, msg: "Dices que lo advertiste poco y lo redactaste mucho. La viuda valora la franqueza; los hijos, menos." } },
        { t: "Decir que hiciste lo que te pidieron", d: { rep: -5, red: -4, msg: "Es cierto y no sirve. Un abogado que escribe lo que le dictan es un taquígrafo caro." } },
        { t: "Ofrecer un acuerdo entre hermanos, sin cobrar", d: { cash: -2000, red: 2, rep: 1, ene: -5, msg: "Sientas a los cuatro hermanos en una mesa. Es lo que debiste hacer al principio.",
          luego: [{ en: 1, s: "red", azar: [{ p: 50, id: 21515, bueno: true }, { p: 50, id: 21516, bueno: false }] }] } },
      ] },
    { id: 21512, por: "Sentaste a una familia antes de un testamento", t: "La reunión familiar estalla",
      x: "Sentaste a los cuatro hijos con el padre. A los veinte minutos dos se van dando un portazo. El patriarca te mira como si fuera culpa tuya.",
      o: [
        { t: "Seguir con los que se quedaron", d: { cri: 2, rep: 1, ene: -3, msg: "Avanzas con la mitad de la familia. Es menos de lo que querías y más de lo que había." } },
        { t: "Volver a lo que pidió el patriarca", d: { cash: 2000, rep: -2, msg: "Redactas lo que dictó desde el principio. Firma con alivio y tú con un nudo en el estómago." } },
        { t: "Proponer otra reunión, con un mediador", d: { cash: -500, red: 2, ene: -4, msg: "El mediador cobra caro y habla poco. A la tercera sesión, el portazo se vuelve una conversación." } },
      ] },
    { id: 21513, por: "Ayudaste a una familia con su herencia", t: "Los hermanos firman un protocolo",
      x: "Tras meses de reuniones, la familia firma reglas escritas sobre quién manda y quién hereda qué. El hijo más difícil es ahora quien más las defiende.",
      o: [
        { t: "Pedir quedarte como asesor de la familia", d: { cash: 4000, car: 3, red: 2, ene: -2, msg: "Te dan un asiento fijo en sus reuniones. Ahora sabes cómo piensan tres generaciones." } },
        { t: "Recomendar a alguien neutral para eso", d: { rep: 3, red: 2, msg: "Les sugieres un asesor externo. Te lo agradecen y te recomiendan con otras tres familias." } },
        { t: "Cobrar y despedirte", d: { cash: 3000, ene: 2, msg: "Cierras la carpeta con el protocolo firmado. Lo mejor de las herencias ajenas es que terminan." } },
      ] },
    { id: 21514, por: "Redactaste el testamento de un patriarca", t: "Otra familia toca la puerta",
      x: "Un amigo del patriarca, con otro grupo y otros hijos peleados, quiere que hagas por su familia lo mismo que hiciste por aquella.",
      o: [
        { t: "Aceptar con el mismo método", d: { cash: 4000, car: 3, ene: -4, msg: "Mismo método, otra familia, los mismos gritos con otro apellido. Sale mejor la segunda vez." } },
        { t: "Aceptar y subir honorarios", d: { cash: 6000, rep: -1, ene: -4, msg: "Paga sin chistar. Las familias con plata pagan cualquier cosa, menos que les digan que no." } },
        { t: "Declinar, ya tienes suficiente drama", d: { ene: 3, red: -1, msg: "Lo mandas con un colega. Te ahorras cenas tensas y un cliente que habría pagado bien." } },
      ] },
    { id: 21515, por: "Ofreciste arreglar un testamento que se cayó", t: "Los hermanos aceptan repartir",
      x: "Cuatro hermanos, un acuerdo y tu firma como testigo. No te pagan por esto, pero la viuda te llama para cada asunto de la familia.",
      o: [
        { t: "Quedarte como asesor del grupo", d: { cash: 3000, car: 2, red: 3, ene: -2, msg: "Lo que empezó como un error termina como tu mejor cliente. Nadie en la familia lo menciona." } },
        { t: "Cerrar el capítulo y seguir", d: { rep: 2, ene: 3, msg: "Te despides con la deuda saldada. La lección sobre la ley de herencias ya no se te olvida." } },
      ] },
    { id: 21516, por: "Ofreciste arreglar un testamento que se cayó", t: "La familia te demanda",
      x: "El acuerdo no cuaja y dos hermanos te demandan por mala práctica. Piden lo que dejaron de heredar, más intereses.",
      o: [
        { t: "Usar tu seguro profesional y negociar", d: { cash: -4000, rep: -2, ene: -2, msg: "El seguro cubre la mayor parte y tú el resto. Firmas un acuerdo confidencial que todos conocen." } },
        { t: "Pelear el caso hasta el final", d: { cash: -6000, cri: 2, rep: -1, ene: -7, msg: "Ganas tras años de pleito. Lo que te costó defenderte es casi lo mismo que pedían." } },
      ] },

    /* ===== consecuencias de 21600 (el arbitraje) ===== */
    { id: 21610, por: "Aceptaste arbitrar una disputa entre fondos", t: "Tu laudo queda firme",
      x: "Dictas el laudo y ninguna de las partes lo impugna. La que perdió paga en plazo, que en este oficio casi nunca pasa.",
      o: [
        { t: "Aceptar el siguiente arbitraje que llegue", d: { cash: 4000, rep: 3, ene: -4, msg: "La cámara te pone primero en la lista. Los arbitrajes pagan bien y no tienen horario." } },
        { t: "Volver de lleno a tus clientes", d: { car: 2, ene: 1, msg: "Vuelves a la oficina con un caso menos y un prestigio más. Los clientes lo notan en la tarjeta." } },
        { t: "Dar clases de arbitraje en la facultad", d: { rep: 3, red: 3, ene: -2, msg: "Los martes en la noche, cuarenta estudiantes. Tres de ellos serán árbitros y se acordarán de ti." } },
      ] },
    { id: 21611, por: "Callaste un vínculo viejo al aceptar un arbitraje", t: "La parte perdedora te recusa",
      x: "Tras el laudo, la parte que perdió descubre a tu antiguo cliente y pide anularlo todo. Dice que callaste un vínculo que debías revelar.",
      o: [
        { t: "Admitir que debiste decirlo", d: { cri: 3, rep: -4, msg: "Lo reconoces por escrito. El laudo queda en duda y tu franqueza, en el expediente." } },
        { t: "Defender que el vínculo no pesaba", d: { ene: -4, rep: -1, msg: "Escribes un descargo largo y sereno. La decisión ya no depende de ti.",
          luego: [{ en: 1, s: "rep", azar: [{ p: 45, id: 21615, bueno: true }, { p: 55, id: 21616, bueno: false }] }] } },
        { t: "Renunciar a la lista de árbitros", d: { ene: 2, rep: -2, car: -3, msg: "Te retiras antes de que te retiren. Algunos lo leen como elegancia; la mayoría, como confesión." } },
      ] },
    { id: 21612, por: "Aceptaste arbitrar una disputa entre fondos", t: "Una parte presiona por debajo",
      x: "En mitad del proceso, el abogado de uno de los fondos te invita a almorzar. Dice que solo quiere hablar del clima.",
      o: [
        { t: "Rechazar y avisar a la otra parte", d: { rep: 3, red: -2, msg: "Mandas un correo a ambas partes contando la invitación. El abogado no vuelve a mirarte a los ojos." } },
        { t: "Ir y hablar de verdad solo del clima", d: { red: 2, rep: -3, msg: "Hablan del clima. Pero alguien los ve juntos, y en este oficio eso basta." } },
        { t: "Denunciarlo ante la cámara", d: { rep: 4, red: -4, ene: -2, msg: "La cámara lo amonesta. Te ganas el respeto de la institución y un enemigo con buena memoria." } },
      ] },
    { id: 21613, por: "Te propusieron como árbitro", t: "La cámara te llama otra vez",
      x: "La cámara de comercio vuelve a proponerte, esta vez para un caso más grande. No conoces a nadie de las partes, o eso parece.",
      o: [
        { t: "Aceptar y revisar las partes a fondo", d: { cash: 4000, rep: 3, cri: 1, ene: -4, msg: "Revisas socios, filiales y abogados. Todo limpio. Te toma una semana y te ahorra un disgusto." } },
        { t: "Aceptar sin revisar más", d: { cash: 4000, rep: -1, ene: -2, msg: "Aceptas rápido. A mitad del caso descubres un primo lejano en una filial. Lo revelas tarde y mal." } },
        { t: "Declinar otra vez", d: { ene: 2, red: -3, rep: -1, msg: "La cámara te borra de la lista corta. Dos negativas seguidas se leen como falta de interés." } },
      ] },
    { id: 21614, por: "Declinaste ser árbitro por un vínculo viejo", t: "Un fondo te quiere en su comité",
      x: "Uno de los fondos de aquella disputa supo por qué no quisiste arbitrar. Te ofrece un asiento pagado en su comité de inversiones.",
      o: [
        { t: "Aceptar el asiento", d: { cash: 5000, red: 3, ene: -3, msg: "Una reunión al mes y acceso a todo lo que el fondo mira. Escuchas mucho más de lo que opinas." } },
        { t: "Aceptar cuando termine el arbitraje", d: { cash: 2000, rep: 2, msg: "Esperas a que haya laudo. Entras más tarde y sin que nadie pueda decir nada de tu silla." } },
        { t: "Declinar: sería el mismo conflicto al revés", d: { rep: 3, red: -1, msg: "El fondo lo entiende y te admira un poco más. Admirar no paga, pero se recuerda." } },
      ] },
    { id: 21615, por: "Defendiste un laudo frente a una recusación", t: "El tribunal sostiene tu laudo",
      x: "El tribunal dice que el vínculo era viejo y no pesó. Tu laudo queda firme, y tú con una advertencia que nadie más lee.",
      o: [
        { t: "Revelar todo de aquí en adelante", d: { rep: 2, cri: 2, msg: "Tus declaraciones de independencia se vuelven largas como novelas. Nadie vuelve a recusarte." } },
        { t: "Seguir con tu criterio de siempre", d: { cash: 2000, rep: -2, msg: "Ganaste esta. La cámara, por si acaso, ya no te propone para casos entre fondos." } },
      ] },
    { id: 21616, por: "Defendiste un laudo frente a una recusación", t: "Anulan tu laudo",
      x: "El tribunal anula el laudo por falta de revelación. Las partes tienen que empezar de cero y la cámara te saca de la lista.",
      o: [
        { t: "Aceptarlo y volver a ejercer", d: { rep: -3, car: -2, ene: -2, msg: "Vuelves a tus contratos con la cabeza baja. Los clientes de siempre no preguntan; los nuevos, sí." } },
        { t: "Recurrir la decisión", d: { cash: -3000, rep: -2, ene: -5, msg: "El recurso no prospera y vuelve a salir en las noticias del gremio. Esta vez con foto." } },
      ] },
  ],

  opciones: [
    { escena: 31, t: "Concederla con derecho de los demás a igualarla", d: { cri: 4, rep: 3, red: -2, ene: -3,
      msg: "Redactas la carta, pero cualquier otro inversionista puede pedir lo mismo. El fondo firma con cara de haber perdido algo." } },
    { escena: 15, t: "Aceptar solo con seguro e indemnidad negociados", d: { cri: 3, rep: 3, car: 2, red: -2, ene: -3,
      msg: "Pides seguro de responsabilidad para directores y una carta que te cubra. Tardan meses y en la junta te miran raro." } },
    { escena: 33, t: "Comparar los contratos y no solo el precio", d: { cri: 5, car: 2, ene: -4,
      msg: "Lees los dos borradores. El precio alto venía con tantas condiciones que valía menos. Te cuesta tres noches verlo." } },
    { escena: 27, t: "Proponer un protocolo familiar por escrito", d: { cri: 3, rep: 2, red: -1, ene: -5,
      msg: "Propones poner por escrito quién decide qué. Dos hermanos aceptan; el tercero llega con su propio abogado." } },
  ],

  finales: [
    { id: "l11_letra_chica", huellas: ["l11_marcaste_cambio", "l11_salvedades"], t: "La letra chica era tuya",
      x: "Marcaste el cambio que nadie marcó y firmaste con salvedades cuando te pagaban por no ponerlas. Cobraste menos que otros y dormiste mejor que todos." },
    { id: "l11_firma_facil", huellas: ["l11_firmaste_limpio", "l11_horas_infladas"], t: "Una firma fácil de conseguir",
      x: "Redondeaste horas y firmaste lo que el cliente quería leer. Tu firma circuló por todas partes y cada vez valió un poco menos." },
  ],
};
