/* El Analista: escenas propias de la carrera de Computación (sis), lote 13.
   Ids 23000-23999. Cada raíz usa su centena: raíz 23k00 -> consecuencias 23k10 a 23k16.
   En cada raíz, 23k10-23k14 son de segundo nivel y 23k15-23k16 de tercer nivel (hojas). */
module.exports = {
  carrera: "sis",

  huellas: {
    l13_automatizaste: "Automatizaste un área entera y entregaste la lista",
    l13_reconvertiste: "Automatizaste un área sin dejar a nadie en la calle",
    l13_ensenaste: "Le enseñaste a programar a alguien que iba a sobrar",
    l13_usaste_datos: "Usaste datos de clientes sin permiso de nadie",
    l13_pediste_permiso: "Pediste permiso antes de usar datos de clientes",
    l13_desconectaste: "Desconectaste todo en un ataque y cerraste a mano",
    l13_restauraste: "Restauraste los sistemas a contrarreloj en un ataque",
    l13_pagaste_rescate: "Recomendaste pagarles el rescate a unos atacantes",
    l13_callaste_puerta: "Callaste que el ataque entró por un servidor tuyo",
    l13_vendiste_modelo: "Le vendiste tu modelo de riesgo a un banco",
    l13_licenciaste: "Licenciaste tu modelo y te quedaste el código",
    l13_te_lo_quedaste: "No vendiste tu modelo y quisiste montar algo propio",
    l13_cto: "Fuiste CTO de una fintech de noche y fines de semana",
    l13_asesor_startup: "Asesoraste una fintech a cambio de un pedazo chico",
    l13_sin_freno: "Encendiste tu algoritmo de trading sin freno",
    l13_con_limites: "Encendiste tu algoritmo con límites de pérdida",
    l13_apagaste_modelo: "Apagaste un modelo de crédito que discriminaba",
    l13_corregiste_silencio: "Corregiste en silencio un modelo con sesgo",
    l13_defendiste_modelo: "Defendiste un modelo que rechazaba a un barrio",
  },

  propias: [
    /* ===== 23100 Automatizar el área (cargo 1 a 4) ===== */
    { id: 23100, min: 1, max: 4, empleado: true, t: "Te piden automatizar el área",
      x: "Conciliaciones: seis personas y tres días al mes. Tu jefe quiere que lo haga un script y te pide, de paso, la lista de quién sobra.",
      o: [
        { t: "Automatizarlo todo y entregar la lista", d: { mod: 5, car: 5, red: -5, rep: -2, deja: "l13_automatizaste",
          msg: "El script cierra en dos horas lo que tomaba tres días. En el pasillo, la gente deja de saludarte.",
          luego: [{ en: 1, s: "cri", azar: [{ p: 30, id: 23110, bueno: false }, { p: 35, id: 23111, bueno: true }, { p: 35, id: 23112 }] }] } },
        { t: "Automatizar y convertir al equipo en revisores", d: { mod: 3, cri: 3, red: 3, car: 1, ene: -5, deja: "l13_reconvertiste",
          msg: "Le vendes a tu jefe que alguien tiene que vigilar a la máquina. Compra la idea, sin entusiasmo.",
          luego: [{ en: 1, s: "red", azar: [{ p: 45, id: 23114, bueno: true }, { p: 30, id: 23111 }, { p: 25, id: 23110, bueno: false }] }] } },
        { t: "Decir que no se puede automatizar", d: { red: 4, rep: -1, car: -3,
          msg: "Explicas, con mucha jerga, que el proceso es demasiado artesanal. Tu jefe no te entiende, que era la idea.",
          luego: [{ en: 1, s: "red", azar: [{ p: 55, id: 23113, bueno: false }, { p: 45, id: 23114, bueno: true }] }] } },
      ] },

    /* ===== 23200 Datos de clientes (cargo 0 a 2) ===== */
    { id: 23200, min: 0, max: 2, empleado: true, t: "Datos que no deberías tocar",
      x: "Armas un modelo de riesgo y descubres que tienes acceso a toda la base de clientes del banco. Con ella el modelo acierta mucho más. Nadie lo autorizó.",
      o: [
        { t: "Usarlos sin preguntar: el modelo es mejor", d: { mod: 5, car: 3, deja: "l13_usaste_datos",
          msg: "El modelo mejora de un día para otro. Tu jefe pregunta cómo lo lograste y contestas con una sonrisa.",
          luego: [{ en: 2, s: "cri", azar: [{ p: 35, id: 23210, bueno: false }, { p: 35, id: 23211, bueno: true }, { p: 30, id: 23212, bueno: false }] }] } },
        { t: "Pedir permiso a cumplimiento y esperar", d: { cri: 4, car: -1, ene: -2, deja: "l13_pediste_permiso",
          msg: "Cumplimiento tarda seis semanas y aprueba la mitad, sin nombres. El modelo mejora menos, pero mejora.",
          luego: [{ en: 1, s: "cri", azar: [{ p: 50, id: 23213, bueno: true }, { p: 25, id: 23211 }, { p: 25, id: 23214, bueno: false }] }] } },
        { t: "Avisar que el acceso está abierto", d: { cri: 3, rep: 3, red: -1,
          msg: "Reportas el hueco. Te lo cierran a ti y, de paso, a otros cuarenta que tampoco debían ver nada.",
          luego: [{ en: 1, s: "rep", azar: [{ p: 55, id: 23213, bueno: true }, { p: 45, id: 23214, bueno: false }] }] } },
      ] },

    /* ===== 23300 Ataque a la hora del cierre (cargo 2 a 5) ===== */
    { id: 23300, min: 2, max: 5, t: "Pantallas en negro antes del cierre",
      x: "Faltan veinte minutos para el cierre de mes y los servidores aparecen cifrados. Una nota pide rescate en cripto. Nadie en el piso sabe más de sistemas que tú.",
      o: [
        { t: "Desconectar todo y cerrar a mano", d: { cri: 4, rep: 2, ene: -6, deja: "l13_desconectaste",
          msg: "Cortas la red de cuajo. El cierre sale con dos días de retraso, en papel y a punta de café.",
          luego: [{ en: 1, s: "cri", azar: [{ p: 40, id: 23310, bueno: true }, { p: 30, id: 23311, bueno: false }, { p: 30, id: 23312 }] }] } },
        { t: "Restaurar el respaldo a contrarreloj", d: { mod: 5, car: 3, ene: -5, deja: "l13_restauraste",
          msg: "Restauras el respaldo de anoche. Cierras a tiempo, con un día entero de operaciones por reconstruir.",
          luego: [{ en: 1, s: "mod", azar: [{ p: 35, id: 23310, bueno: true }, { p: 35, id: 23313, bueno: false }, { p: 30, id: 23312 }] }] } },
        { t: "Recomendar pagar el rescate", d: { cri: -3, rep: -3, car: 1, deja: "l13_pagaste_rescate",
          msg: "Se paga. Las llaves llegan y funcionan. Nadie quiere volver a hablar del tema, y tú menos que nadie.",
          luego: [{ en: 1, azar: [{ p: 30, id: 23312 }, { p: 40, id: 23313 }, { p: 30, id: 23314 }] }] } },
      ] },

    /* ===== 23400 Un banco quiere tu modelo (cargo 3 a 6) ===== */
    { id: 23400, min: 3, max: 6, t: "Un banco quiere comprar tu modelo",
      x: "Un modelo de riesgo que escribiste de noche funciona demasiado bien. Un banco grande quiere comprarlo, con el código y los derechos incluidos.",
      o: [
        { t: "Venderlo todo de una vez", d: { cash: 25000, car: 2, deja: "l13_vendiste_modelo",
          msg: "Firmas, cobras y entregas el repositorio. Por primera vez, algo que programaste vale más que tu sueldo.",
          luego: [{ en: 1, azar: [{ p: 35, id: 23410 }, { p: 30, id: 23411 }, { p: 35, id: 23412 }] }] } },
        { t: "Licenciarlo y quedarte con el código", d: { cash: 8000, mod: 2, ene: -3, deja: "l13_licenciaste",
          msg: "Cobras cada año por el uso y el código sigue siendo tuyo. Ahora tienes un cliente que llama a las once de la noche.",
          luego: [{ en: 1, s: "mod", azar: [{ p: 40, id: 23413, bueno: true }, { p: 25, id: 23410 }, { p: 20, id: 23411, bueno: false }, { p: 15, id: 23414, bueno: false }] }] } },
        { t: "No venderlo y montar algo propio con él", d: { cash: -4000, cri: 2, ene: -4, deja: "l13_te_lo_quedaste",
          msg: "Les dices que no. Si vale tanto para ellos, quizá valga más para ti. Contratas un servidor y un abogado.",
          luego: [{ en: 2, s: "cri", azar: [{ p: 35, id: 23413, bueno: true }, { p: 35, id: 23414, bueno: false }, { p: 30, id: 23411, bueno: false }] }] } },
      ] },

    /* ===== 23500 CTO de una startup (cargo 1 a 4) ===== */
    { id: 23500, min: 1, max: 4, t: "Una fintech te quiere de CTO",
      x: "Dos amigos montan una fintech de pagos y necesitan quien escriba el producto. No hay sueldo: hay acciones de algo que todavía no existe.",
      o: [
        { t: "Entrar como CTO de noche y fines de semana", d: { mod: 4, red: 3, ene: -8, deja: "l13_cto",
          msg: "Programas después del trabajo y los domingos. La fintech empieza a existir y tus horas de sueño, a desaparecer.",
          luego: [{ en: 2, s: "mod", azar: [{ p: 30, id: 23510, bueno: true }, { p: 35, id: 23511, bueno: false }, { p: 20, id: 23512 }, { p: 15, id: 23513 }] }] } },
        { t: "Asesorar a cambio de un pedazo chico", d: { cri: 2, red: 3, ene: -3, deja: "l13_asesor_startup",
          msg: "Una reunión cada dos semanas y un porcentaje que cabe en una servilleta. Te parece justo.",
          luego: [{ en: 2, azar: [{ p: 30, id: 23510 }, { p: 40, id: 23511 }, { p: 30, id: 23513 }] }] } },
        { t: "Decir que no y desearles suerte", d: { ene: 2, red: -1,
          msg: "Les dices que no. Se van con un abrazo y un poco de decepción que intentan disimular.",
          luego: [{ en: 2, azar: [{ p: 40, id: 23514 }, { p: 60, id: 23511 }] }] } },
      ] },

    /* ===== 23600 Trading algorítmico (cargo 2 a 5) ===== */
    { id: 23600, min: 2, max: 5, t: "Tu algoritmo de trading está terminado",
      x: "En tres años de datos históricos, tu algoritmo no tiene una sola semana mala. Ya puedes ponerle dinero real. Eso es justo lo que te preocupa.",
      o: [
        { t: "Encenderlo con todo y sin freno", d: { mod: 3, car: 3, cash: 3000, deja: "l13_sin_freno",
          msg: "Lo enciendes con todo el tamaño posible. Primer mes: arriba. Ya sabes lo que se dice del primer mes.",
          luego: [{ en: 1, s: "cri", azar: [{ p: 40, id: 23610, bueno: false }, { p: 25, id: 23611 }, { p: 35, id: 23612, bueno: true }] }] } },
        { t: "Encenderlo chico y con límites de pérdida", d: { mod: 3, cri: 3, deja: "l13_con_limites",
          msg: "Lo arrancas con poco y un interruptor que lo apaga si pierde de más. Aburrido, como debe ser.",
          luego: [{ en: 1, s: "cri", azar: [{ p: 40, id: 23612, bueno: true }, { p: 35, id: 23613 }, { p: 10, id: 23610, bueno: false }, { p: 15, id: 23611 }] }] } },
        { t: "Probarlo en papel seis meses más", d: { cri: 4, car: -2, ene: -2,
          msg: "Seis meses de pruebas sin dinero. Alrededor tuyo, la paciencia se agota antes que los datos.",
          luego: [{ en: 1, azar: [{ p: 60, id: 23614 }, { p: 40, id: 23611 }] }] } },
      ] },

    /* ===== 23700 Un modelo con sesgo (cargo 4 a 6) ===== */
    { id: 23700, min: 4, max: 6, t: "El modelo rechaza a un barrio entero",
      x: "El modelo de crédito que maneja tu equipo rechaza a casi todos los de un mismo barrio. Nadie se lo pidió. Lo aprendió de los datos.",
      o: [
        { t: "Apagarlo hasta entender por qué", d: { cri: 5, rep: 2, car: -2, deja: "l13_apagaste_modelo",
          msg: "Lo apagas y se vuelve a aprobar a mano. Las solicitudes se apilan y todas las miradas van hacia ti.",
          luego: [{ en: 1, s: "cri", azar: [{ p: 45, id: 23710, bueno: true }, { p: 30, id: 23711 }, { p: 25, id: 23712, bueno: false }] }] } },
        { t: "Corregirlo en silencio", d: { mod: 4, cri: -1, deja: "l13_corregiste_silencio",
          msg: "Ajustas los pesos un fin de semana. El lunes el barrio aparece aprobado y nadie pregunta nada.",
          luego: [{ en: 1, azar: [{ p: 35, id: 23712 }, { p: 35, id: 23713 }, { p: 30, id: 23710 }] }] } },
        { t: "Defenderlo: los datos son los datos", d: { car: 3, rep: -3, cri: -3, deja: "l13_defendiste_modelo",
          msg: "Explicas que el modelo solo refleja el riesgo. Suena impecable en la sala y horrible fuera de ella.",
          luego: [{ en: 1, azar: [{ p: 50, id: 23712 }, { p: 50, id: 23714 }] }] } },
      ] },
  ],

  escenas: [
    /* ===== 23100 Automatizar el área ===== */
    { id: 23110, empleado: true, por: "Automatizaste las conciliaciones del área", t: "El script se cae el día del cierre",
      x: "El banco cambió el formato de sus archivos y tu script lleva dos horas escupiendo errores. Es día de cierre y quedan pocos que sepan hacerlo a mano.",
      o: [
        { t: "Arreglarlo durante la noche", d: { mod: 4, rep: 2, ene: -6,
          msg: "A las tres de la mañana encuentras el problema: una coma. El cierre sale y nadie se entera de lo que costó." } },
        { t: "Llamar a los que sabían hacerlo a mano", d: { cri: 3, red: -2, rep: -2,
          msg: "Contestan los que quedan. El cierre sale tarde y con una lección: el robot necesitaba un plan B con dueño." } },
        { t: "Contarle a tu jefe y pedir un día de prórroga", d: { cri: 2, car: -1, ene: -2,
          msg: "Se lo dices sin adornos. Tu jefe respira hondo y pide el día. Ahora la falla tiene tu firma.",
          luego: [{ en: 1, s: "cri", azar: [{ p: 50, id: 23115, bueno: true }, { p: 50, id: 23116, bueno: false }] }] } },
      ] },
    { id: 23111, empleado: true, por: "Automatizaste las conciliaciones del área", t: "Quieren lo mismo en tesorería",
      x: "Funcionó tan bien que ahora quieren lo mismo en tesorería. Más gente, más procesos y otra lista que alguien tendrá que firmar.",
      o: [
        { t: "Aceptar y que la lista la haga recursos humanos", d: { car: 5, mod: 3, red: -2, cash: 3000,
          msg: "Haces el código y otro hace la lista. La diferencia es enorme para ti y ninguna para los de la lista." } },
        { t: "Aceptar con una condición: nadie sale sin reubicación", d: { car: 2, red: 4, cri: 2, ene: -3,
          msg: "La condición retrasa todo un trimestre. Tesorería se automatiza y nadie termina en la calle." } },
        { t: "Pasarle el proyecto a otro", d: { ene: 3, car: -2, red: 1,
          msg: "Lo pasas con mucha amabilidad. El otro lo hace peor y más rápido, y se lleva el aplauso." } },
      ] },
    { id: 23112, por: "Entregaste la lista de quién sobraba", t: "Te escribe alguien de la lista",
      x: "Una de las personas que salió te manda un mensaje. No reclama nada: pregunta si sabes de algún trabajo y si le firmarías una carta.",
      o: [
        { t: "Firmarle la carta y mover contactos", d: { red: 3, rep: 2, ene: -2,
          msg: "Le consigues dos entrevistas y en una la contratan. No te lo agradece en voz alta, y está bien." } },
        { t: "Contestar con cortesía y nada más", d: { ene: 1, rep: -1,
          msg: "Le deseas lo mejor en tres líneas. Lees la respuesta, que es más corta todavía." } },
        { t: "No contestar", d: { ene: 2, rep: -3,
          msg: "Lo dejas en visto. En una plaza pequeña, el visto también viaja." } },
      ] },
    { id: 23113, empleado: true, por: "Dijiste que el área no se podía automatizar", t: "Una consultora te pasa por encima",
      x: "Tu jefe trajo una consultora. En seis semanas automatizan lo que dijiste que era imposible y despiden a la mitad igual. Ahora te miran raro a ti.",
      o: [
        { t: "Admitir que lo frenaste por la gente", d: { cri: 3, red: 2, rep: -2, car: -2,
          msg: "Tu jefe te escucha. Valora la honestidad y anota que no se puede contar contigo para todo." } },
        { t: "Revisar su código y encontrarle fallas", d: { mod: 4, rep: 2, ene: -4,
          msg: "Encuentras tres, y una es grave. La consultora cobra igual y tú recuperas algo de terreno." } },
        { t: "Fingir sorpresa", d: { ene: 1, rep: -4,
          msg: "Pones cara de asombro. Nadie se la cree, y tu jefe menos que nadie." } },
      ] },
    { id: 23114, por: "Protegiste al equipo de conciliaciones", t: "Alguien del equipo quiere programar",
      x: "El que más años lleva en conciliaciones te pide que le enseñes a programar. Dice que no piensa ser el siguiente de ninguna lista.",
      o: [
        { t: "Enseñarle dos tardes por semana", d: { red: 4, cri: 2, rep: 2, ene: -4, deja: "l13_ensenaste",
          msg: "Aprende lento y no olvida nada. A los seis meses te corrige un script, y tiene razón." } },
        { t: "Pasarle un curso en línea", d: { red: 1, ene: -1,
          msg: "Le mandas el enlace con ánimo. Lo termina a medias, que es como se terminan casi todos." } },
        { t: "Decirle que a su edad no vale la pena", d: { rep: -4, red: -3,
          msg: "Lo dices sin pensar. Él lo piensa por los dos y no vuelve a pedirte nada." } },
      ] },
    { id: 23115, empleado: true, por: "Admitiste que tu script falló en el cierre", t: "Te ponen a vigilar a los robots",
      x: "Tu jefe valoró que no escondieras la falla. Ahora quiere que diseñes los controles de todos los procesos automáticos de la casa.",
      o: [
        { t: "Aceptar y escribir el manual de controles", d: { cri: 5, car: 4, ene: -4,
          msg: "Escribes quién revisa qué, cuándo y qué pasa si falla. Aburrido de leer, imposible de saltarse." } },
        { t: "Aceptar si te dan un equipo", d: { car: 3, red: 3, ene: -2,
          msg: "Te dan dos personas. Una de ellas era de conciliaciones, y conoce los fallos mejor que nadie." } },
      ] },
    { id: 23116, empleado: true, por: "Admitiste que tu script falló en el cierre", t: "Auditoría lo anota como falla de control",
      x: "El informe de auditoría dice que un proceso crítico dependía de una persona y un script sin respaldo. La persona eres tú.",
      o: [
        { t: "Firmar el plan de corrección", d: { cri: 3, car: -1, ene: -3,
          msg: "Documentas todo y entrenas a dos personas. Dejas de ser imprescindible, que era el problema." } },
        { t: "Discutir el hallazgo", d: { rep: -3, cri: -1,
          msg: "Discutes una tarde entera. El hallazgo queda igual y ahora también queda tu nombre." } },
      ] },

    /* ===== 23200 Datos de clientes ===== */
    { id: 23210, empleado: true, por: "Usaste datos de clientes sin permiso", t: "Cumplimiento pregunta por tus consultas",
      x: "Una revisión de accesos encontró tus consultas a la base de clientes. Cumplimiento quiere una explicación por escrito antes del viernes.",
      o: [
        { t: "Contar la verdad y borrar las copias", d: { cri: 3, rep: -3, car: -3,
          msg: "Te ganas una amonestación formal y conservas el trabajo. El modelo vuelve a ser mediocre." } },
        { t: "Decir que tu jefe lo sabía", d: { rep: -2, red: -3,
          msg: "Lo escribes con cuidado. Cumplimiento cita a tu jefe para el lunes.",
          luego: [{ en: 1, azar: [{ p: 55, id: 23215, bueno: false }, { p: 45, id: 23216 }] }] } },
        { t: "Argumentar que era por el bien del banco", d: { rep: -4, cri: -2, car: -2,
          msg: "Cumplimiento escucha el argumento y lo anota palabra por palabra. Esa nota te va a seguir." } },
      ] },
    { id: 23211, empleado: true, por: "Armaste un modelo de riesgo con datos de clientes", t: "Tu modelo decide sobre gente real",
      x: "El banco adopta tu modelo para aprobar créditos. Ahora decide sobre gente de verdad, y esa gente empieza a preguntar por qué la rechazaron.",
      o: [
        { t: "Hacer que el modelo explique cada rechazo", d: { mod: 3, cri: 4, ene: -4,
          msg: "Le agregas una razón legible a cada rechazo. Más trabajo para ti, menos llamadas furiosas para todos." } },
        { t: "Dejarlo como está: funciona", d: { car: 3, rep: -2,
          msg: "Funciona, en efecto. Las quejas llegan al área comercial, que no sabe qué contestar." } },
      ] },
    { id: 23212, empleado: true, por: "Usaste datos de clientes sin permiso", t: "Una filtración con tu copia en el medio",
      x: "Se filtró una base de clientes del banco. Entre los archivos que circulan hay uno que lleva el nombre de tu modelo.",
      o: [
        { t: "Ir a seguridad antes de que te llamen", d: { cri: 4, rep: -2, car: -2,
          msg: "Llegas primero. La filtración vino de un proveedor, pero tu copia tampoco debía existir." } },
        { t: "Borrar todo y esperar", d: { rep: -5, cri: -3, car: -3,
          msg: "Borras todo. Los registros del servidor no borran nada y te llaman igual, con menos paciencia." } },
      ] },
    { id: 23213, empleado: true, por: "Llevaste a cumplimiento un problema de datos", t: "Cumplimiento te pide ayuda",
      x: "En cumplimiento nadie entiende de bases de datos. Te piden que revises quién más tiene accesos que no debería tener.",
      o: [
        { t: "Hacerlo con todo el rigor", d: { cri: 4, rep: 3, red: -3, ene: -3,
          msg: "Encuentras doscientos accesos sobrantes. Cien personas te odian un poco y cumplimiento te adora." } },
        { t: "Hacerlo sin señalar a nadie", d: { cri: 1, red: 2, rep: 1,
          msg: "Cierras los accesos sin nombres ni culpables. Nadie se entera de que fuiste tú, que era el plan." } },
        { t: "Decir que no es tu trabajo", d: { ene: 2, car: -1,
          msg: "Técnicamente no lo es. Cumplimiento contrata a un externo que tarda un año y cobra como tres." } },
      ] },
    { id: 23214, empleado: true, por: "Respetaste los datos de clientes del banco", t: "Otra área llegó primero",
      x: "Otra área presentó un modelo de riesgo mejor que el tuyo. Usaron datos de un proveedor que nadie revisó. Tu jefe pregunta por qué no se te ocurrió.",
      o: [
        { t: "Explicar el riesgo de esos datos", d: { cri: 3, rep: 1, car: -1,
          msg: "Lo explicas con calma. Tu jefe asiente y se queda con el otro modelo, por ahora." } },
        { t: "Revisar sus datos y encontrar el problema", d: { mod: 3, rep: 2, red: -3, ene: -3,
          msg: "Encuentras clientes duplicados y fechas imposibles. Ganas el punto y una enemistad en otra área." } },
        { t: "Callarte y mejorar el tuyo", d: { mod: 2, ene: -2,
          msg: "Trabajas en silencio un mes. Tu modelo mejora y nadie lo nota, que es lo normal." } },
      ] },
    { id: 23215, empleado: true, por: "Dijiste que tu jefe sabía lo de los datos", t: "Tu jefe dice que no sabía nada",
      x: "Tu jefe declara que nunca autorizó nada. Hay un correo suyo que dice «haz lo que haga falta». Ambiguo, como todos los correos de jefe.",
      o: [
        { t: "Mostrar el correo", d: { cri: 1, rep: -2, red: -4, car: -2,
          msg: "El correo no prueba nada y lo cambia todo. Tu jefe ya no te asigna nada importante." } },
        { t: "Asumirlo y no insistir", d: { red: 2, rep: -3, car: -3,
          msg: "Te comes la amonestación. Tu jefe te debe una, y los dos lo saben." } },
      ] },
    { id: 23216, empleado: true, por: "Dijiste que tu jefe sabía lo de los datos", t: "Tu jefe te cubre y te pasa la cuenta",
      x: "Tu jefe confirma tu versión ante cumplimiento. Una semana después te pide que firmes unas cifras que no revisaste.",
      o: [
        { t: "Firmarlas: te cubrió", d: { car: 2, rep: -3, cri: -2,
          msg: "Firmas. La deuda queda saldada y empieza otra, que es como funcionan estas cosas." } },
        { t: "Revisarlas antes de firmar", d: { cri: 3, red: -2, ene: -2,
          msg: "Te tomas dos días y encuentras un error. Tu jefe lo corrige sin mirarte a los ojos." } },
      ] },

    /* ===== 23300 Ataque a la hora del cierre ===== */
    { id: 23310, empleado: true, por: "Sacaste adelante un cierre durante un ataque", t: "Te piden el plan de continuidad",
      x: "La dirección quiere que nunca más un cierre dependa de la suerte. Te piden diseñar el plan de continuidad, además de tu trabajo.",
      o: [
        { t: "Diseñarlo y ensayarlo con simulacros", d: { cri: 5, rep: 3, car: 3, ene: -5,
          msg: "Haces tres simulacros. En el segundo, el director no sabe dónde está el respaldo. En el tercero, sí." } },
        { t: "Diseñarlo en papel y archivarlo", d: { car: 1, ene: -1,
          msg: "Queda un documento precioso en una carpeta compartida. Nadie lo va a abrir hasta que haga falta." } },
        { t: "Pedir que te lo paguen aparte", d: { cash: 3000, red: -2, ene: -3,
          msg: "Lo cobras como proyecto. Te lo pagan, y desde entonces te tratan un poco como proveedor." } },
      ] },
    { id: 23311, por: "Desconectaste todo en un ataque y cerraste a mano", t: "Un cliente se va por el retraso",
      x: "Un cliente grande se cansó de esperar el cierre y se lleva la cuenta. Dice que le importa poco por qué fue.",
      o: [
        { t: "Llamarlo y explicarle el ataque", d: { red: 3, rep: 1, ene: -2,
          msg: "Te escucha hasta el final. No vuelve, pero le recomienda tu nombre a un amigo por la forma en que se lo contaste." } },
        { t: "Dejarlo ir", d: { ene: 1, car: -2,
          msg: "Lo dejas ir sin llamada. La cuenta se va, y con ella un pedazo del bono de fin de año." } },
      ] },
    { id: 23312, por: "Viviste un ataque de rescate en pleno cierre", t: "Tus datos aparecen en un foro",
      x: "Los atacantes publican parte de lo que se llevaron: contratos, correos y una hoja de sueldos. El tuyo también está.",
      o: [
        { t: "Avisar a cada cliente afectado", d: { rep: 4, red: 2, ene: -5,
          msg: "Haces cuarenta llamadas incómodas. Casi todos agradecen enterarse por ti y no por el foro." } },
        { t: "Dejar que hable el área legal", d: { ene: 1, red: -2, rep: -1,
          msg: "Legal manda un comunicado impecable. Los clientes lo leen y llaman igual, ahora más molestos." } },
        { t: "Rastrear qué se llevaron y por dónde", d: { mod: 3, cri: 2, ene: -3,
          msg: "Te encierras con los registros de los servidores. Tardas, pero el rastro existe.",
          luego: [{ en: 1, s: "mod", azar: [{ p: 60, id: 23315, bueno: true }, { p: 40, id: 23316, bueno: false }] }] } },
      ] },
    { id: 23313, por: "Recuperaste los sistemas después de un ataque", t: "Vuelven a entrar",
      x: "Tres meses después, el mismo mensaje en las mismas pantallas. Los atacantes nunca se fueron del todo. Esta vez es el cierre trimestral.",
      o: [
        { t: "Rehacer la red desde cero", d: { mod: 4, cri: 3, car: 2, ene: -7,
          msg: "Seis semanas de reconstrucción. Al final sabes dónde está cada cable y quién tiene cada llave." } },
        { t: "Traer una firma de respuesta a incidentes", d: { cri: 2, red: 2, rep: -1,
          msg: "Llegan, limpian y dejan un informe largo. La mitad dice lo que tú venías diciendo." } },
        { t: "Esconderlo hasta después del cierre", d: { rep: -5, cri: -3, car: -2,
          msg: "Cierras como si nada. El problema sigue ahí, esperando, y ahora también tu silencio." } },
      ] },
    { id: 23314, por: "Recomendaste pagarles el rescate a unos atacantes", t: "El regulador pregunta por el pago",
      x: "El regulador quiere saber quién autorizó pagarles a los atacantes y adónde fue el dinero. Tu nombre está en el acta, recomendándolo.",
      o: [
        { t: "Explicar la decisión con todos los datos", d: { cri: 3, rep: -2, ene: -4,
          msg: "Presentas tiempos, riesgos y alternativas. El regulador no aplaude, pero tampoco sanciona." } },
        { t: "Decir que solo diste una opinión técnica", d: { rep: -4, red: -2,
          msg: "Técnicamente es cierto. El regulador no es muy amigo de los tecnicismos." } },
      ] },
    { id: 23315, por: "Rastreaste el origen de un ataque", t: "Encuentras por dónde entraron",
      x: "Un correo falso a contabilidad, una clave reciclada y tres semanas de paciencia. Tienes el informe completo.",
      o: [
        { t: "Presentarlo a la dirección con nombres", d: { cri: 3, rep: 3, red: -4,
          msg: "Lo presentas con nombres y fechas. Contabilidad no te vuelve a invitar al almuerzo." } },
        { t: "Presentarlo sin culpables, solo con fallas", d: { cri: 4, red: 2, rep: 2, ene: -2,
          msg: "Hablas de procesos, no de personas. Arreglan las fallas y nadie se esconde la próxima vez." } },
      ] },
    { id: 23316, por: "Rastreaste el origen de un ataque", t: "La puerta era tu servidor de pruebas",
      x: "El rastro termina en un servidor de pruebas que montaste hace un año y olvidaste apagar. Nadie más lo sabe todavía.",
      o: [
        { t: "Contarlo tú, completo", d: { cri: 5, rep: -3, car: -2,
          msg: "Lo cuentas en la reunión. Silencio largo. Después alguien dice que al menos lo encontraste." } },
        { t: "Apagarlo y no decir nada", d: { cri: -4, rep: -1, ene: -3, deja: "l13_callaste_puerta",
          msg: "Lo apagas a las dos de la mañana. El informe dice «origen indeterminado» y duermes peor." } },
      ] },

    /* ===== 23400 Un banco quiere tu modelo ===== */
    { id: 23410, por: "Le entregaste tu modelo de riesgo a un banco", t: "Tu modelo sale en la prensa",
      x: "El banco usa tu modelo para cobrarles más caro a ciertos clientes. Un periodista lo descubre y quiere saber quién lo escribió.",
      o: [
        { t: "Dar la cara y explicar cómo debía usarse", d: { cri: 3, rep: 2, red: -3, ene: -3,
          msg: "Explicas para qué servía y para qué no. El banco te borra de su lista de contactos." } },
        { t: "No comentar", d: { ene: 1, rep: -2,
          msg: "La nota sale con tu nombre y la frase «no quiso comentar», que suena peor que cualquier comentario." } },
        { t: "Filtrar que el banco lo modificó", d: { cri: 2, rep: -1, red: -4,
          msg: "El banco sabe que fuiste tú. Ellos también tienen abogados, y más que tú." } },
      ] },
    { id: 23411, por: "Te ofrecieron comprar tu modelo de riesgo", t: "Tu antigua firma reclama el código",
      x: "Tu antigua firma dice que escribiste el modelo con sus equipos y en su horario. Tienen copias de correos tuyos de aquella época.",
      o: [
        { t: "Negociar y cederles una parte", d: { cash: -6000, red: 2, cri: 2,
          msg: "Les cedes una parte del dinero. Caro, pero mucho más barato que un juicio." } },
        { t: "Ir a juicio con el historial de cambios del código", d: { cash: -3000, mod: 2, ene: -5,
          msg: "Cada cambio del código tiene fecha y hora. Contratas abogado y le explicas qué es un repositorio.",
          luego: [{ en: 2, s: "mod", azar: [{ p: 55, id: 23415, bueno: true }, { p: 45, id: 23416, bueno: false }] }] } },
        { t: "Soltar el código y olvidarte", d: { ene: 3, rep: -2, car: -2,
          msg: "Te sacudes el problema. El modelo deja de ser tuyo y, en el fondo, nunca terminó de serlo." } },
      ] },
    { id: 23412, por: "Le vendiste tu modelo de riesgo a un banco", t: "En el banco nadie entiende tu código",
      x: "El equipo del banco no logra mantener tu modelo. Te llaman cada semana con una duda nueva y la misma urgencia.",
      o: [
        { t: "Ofrecer asesoría los jueves, cobrando", d: { cash: 6000, ene: -4, red: 2,
          msg: "Los jueves son del banco. Te pagan bien por explicar lo que ya vendiste, que es un buen negocio." } },
        { t: "Dejarles documentación y desaparecer", d: { mod: 2, ene: -2, red: -2,
          msg: "Escribes el manual que nunca escribiste. Te tardas un mes y nadie lo lee entero." } },
        { t: "Contestar gratis por buena voluntad", d: { red: 4, rep: 2, ene: -5,
          msg: "Contestas cada duda sin cobrar. El banco te recomienda en todas partes y te sigue llamando." } },
      ] },
    { id: 23413, por: "Te quedaste con el código de tu modelo de riesgo", t: "Otros bancos quieren lo mismo",
      x: "Tres bancos más preguntan por el modelo. Con cuatro clientes, el código deja de ser un proyecto de noche y empieza a ser una empresa.",
      o: [
        { t: "Venderles a todos y contratar ayuda", d: { cash: 15000, car: 4, red: 3, ene: -6,
          msg: "Contratas a dos programadores y un abogado. El proyecto de noche ahora tiene nómina." } },
        { t: "Elegir un cliente y hacerlo bien", d: { cash: 6000, cri: 3, ene: -2,
          msg: "Le dices que no a dos bancos. El que eliges te trata como si fuera tu único cliente, porque lo es." } },
        { t: "Subir el precio hasta que alguno diga que no", d: { cash: 9000, red: -3,
          msg: "Dos aceptan el precio nuevo y uno se va molesto. Aprendes cuánto vale tu código, y cuánto no." } },
      ] },
    { id: 23414, por: "Negociaste tu modelo de riesgo con un banco", t: "El banco armó su propia versión",
      x: "El banco contrató a dos programadores y armó un modelo casi igual al tuyo. Casi: los errores también los copiaron.",
      o: [
        { t: "Demandar por copia", d: { cash: -4000, cri: 1, ene: -4,
          msg: "El abogado dice que el caso es bueno y lento. Las dos cosas resultan ciertas." } },
        { t: "Ofrecerles arreglar sus errores, cobrando", d: { cash: 5000, rep: 2, red: 2,
          msg: "Te pagan por arreglar la copia de tu propio modelo. Humillante y rentable, en ese orden." } },
        { t: "Mejorar el tuyo y seguir", d: { mod: 4, ene: -3,
          msg: "Le agregas lo que la copia no tiene. Que te copien la versión vieja." } },
      ] },
    { id: 23415, por: "Fuiste a juicio por la propiedad de tu código", t: "El juez lee tu historial de cambios",
      x: "El historial muestra cada cambio con fecha y hora: noches y domingos, nunca en horario de oficina. El juez falla a tu favor.",
      o: [
        { t: "Cobrar las costas y cerrar el tema", d: { cash: 6000, rep: 3,
          msg: "Te devuelven lo gastado y un poco más. Tu antigua firma deja de nombrarte en voz alta." } },
        { t: "Contarlo en público como lección", d: { rep: 4, red: 3, ene: -2,
          msg: "Das una charla sobre cómo separar lo tuyo de lo del empleador. Llena la sala de programadores con miedo." } },
      ] },
    { id: 23416, por: "Fuiste a juicio por la propiedad de tu código", t: "Perdiste el juicio por el código",
      x: "Tres de tus cambios clave son de un martes a las diez de la mañana, desde la red de tu antigua firma. Con eso alcanzó.",
      o: [
        { t: "Pagar y aprender a separar las cosas", d: { cash: -8000, cri: 4,
          msg: "Pagas. Desde entonces tienes dos computadoras y no las mezclas ni para revisar el clima." } },
        { t: "Apelar", d: { cash: -4000, rep: -1, ene: -4,
          msg: "Apelas. El abogado se alegra mucho más que tú." } },
      ] },

    /* ===== 23500 CTO de una startup ===== */
    { id: 23510, por: "Ayudaste a construir la fintech de unos amigos", t: "La fintech levanta capital",
      x: "Un fondo entra en la fintech. Tus acciones, que eran papel, de pronto tienen precio. El fondo pide que nadie del equipo venda en años.",
      o: [
        { t: "Quedarte con todo y esperar", d: { cri: 2, ene: -1,
          msg: "Te quedas con papel caro. No lo puedes vender, pero lo puedes mirar." } },
        { t: "Vender una parte en la ronda", d: { cash: 12000, rep: -1,
          msg: "Vendes un pedazo antes de que se cierre la puerta. El fondo frunce el ceño; tu cuenta, no." } },
        { t: "Pedir más acciones por tu trabajo", d: { mod: 1, red: -3,
          msg: "Lo pides en plena negociación. Los fundadores se miran entre ellos y piden una semana.",
          luego: [{ en: 1, azar: [{ p: 50, id: 23515 }, { p: 50, id: 23516, bueno: false }] }] } },
      ] },
    { id: 23511, por: "Te ofrecieron entrar a una fintech de amigos", t: "La fintech cierra",
      x: "Se acabó el dinero antes que las ideas. Tus amigos cierran la fintech y te invitan a una última cerveza para contarlo.",
      o: [
        { t: "Ir y brindar por lo aprendido", d: { red: 3, ene: 2, cri: 1,
          msg: "Brindan por los errores, que son muchos y muy instructivos. Te vas con dos ideas y una resaca." } },
        { t: "Comprarles el código por casi nada", d: { cash: -1500, mod: 3, red: -2,
          msg: "Te lo venden sin regatear, que es la forma más triste de ganar algo." } },
        { t: "Mandar un mensaje y no ir", d: { ene: 1, red: -2,
          msg: "Escribes algo amable desde el sofá. La foto de la despedida sale sin ti." } },
      ] },
    { id: 23512, empleado: true, por: "Fuiste CTO de una fintech de noche", t: "Tu jefe se entera de tu otro trabajo",
      x: "Tu jefe ve el nombre de la fintech en tu perfil profesional. Quiere saber si tu contrato te permite trabajar para otros.",
      o: [
        { t: "Mostrar que no compite y pedir permiso", d: { cri: 3, rep: 1, car: -1,
          msg: "Lo pides por escrito y te lo dan, con condiciones. Ahora tu tiempo libre tiene un reglamento." } },
        { t: "Borrarlo del perfil y negarlo todo", d: { rep: -4, cri: -2,
          msg: "Lo borras esa misma noche. Tu jefe ya tenía la captura de pantalla." } },
        { t: "Ofrecerle un pedazo de la fintech", d: { red: 2, rep: -2,
          msg: "Se ríe, lo piensa y acepta un pedazo pequeño. Ahora tu jefe también es tu socio, y eso es peor." } },
      ] },
    { id: 23513, por: "Ayudaste a construir la fintech de unos amigos", t: "La fintech te pide más horas",
      x: "Los fundadores dicen que así no llegan: necesitan más de ti. Te ofrecen el doble de acciones a cambio de más noches.",
      o: [
        { t: "Meterle todavía más noches", d: { mod: 3, red: 2, ene: -8,
          msg: "Duermes cinco horas y programas otras cinco. El producto avanza; tu cara, no tanto." } },
        { t: "Contratarles a alguien y supervisarlo", d: { cash: -2000, cri: 2, red: 2,
          msg: "Pagas de tu bolsillo los primeros meses de un programador junior. Aprende rápido y no duerme en tu lugar." } },
        { t: "Quedarte como estás y que busquen a otro", d: { cri: 2, ene: 2, red: -2,
          msg: "Les dices que hasta ahí llegas. Lo entienden, y lo dicen con un tono que no termina de entenderlo." } },
      ] },
    { id: 23514, por: "Le dijiste que no a la fintech de unos amigos", t: "La fintech triunfa sin ti",
      x: "La fintech que rechazaste acaba de levantar una ronda grande. El CTO que contrataron sale en una revista con una sudadera que podría ser tuya.",
      o: [
        { t: "Felicitarlos de corazón", d: { red: 3, ene: 1,
          msg: "Les escribes sin rencor. Te invitan a la fiesta de la ronda y a una cerveza con el CTO." } },
        { t: "Pedir entrar ahora como inversionista", d: { cash: -5000, red: 1,
          msg: "Te aceptan, al precio de ahora. Lo que ayer era gratis hoy cuesta caro." } },
        { t: "Cerrar la revista", d: { cri: 1, ene: -2,
          msg: "La cierras y la vuelves a abrir dos veces. No era tu momento, y lo sabes." } },
      ] },
    { id: 23515, por: "Pediste más acciones de la fintech", t: "Más acciones y tu firma en todo",
      x: "Los fundadores aceptan: más acciones, pero firmas como responsable técnico ante el fondo. Si algo se cae, el nombre que suena es el tuyo.",
      o: [
        { t: "Firmar y asumirlo", d: { car: 3, mod: 2, ene: -4,
          msg: "Firmas. Desde entonces revisas el servidor antes de dormir y apenas te despiertas." } },
        { t: "Firmar con un equipo detrás", d: { cri: 2, red: 2, ene: -2,
          msg: "Exiges dos programadores más antes de firmar. Te los dan, y ahora tienes a quién despertar." } },
      ] },
    { id: 23516, por: "Pediste más acciones de la fintech", t: "Te sacan de la tabla de socios",
      x: "El fondo dice que tu pedido rompe la tabla de accionistas. Los fundadores eligen al fondo y te recompran lo tuyo al precio de antes.",
      o: [
        { t: "Aceptar la recompra", d: { cash: 4000, red: -2,
          msg: "Cobras poco por mucho trabajo. La amistad sobrevive, con un tema que nadie toca." } },
        { t: "Pelearlo con el contrato en la mano", d: { cash: -2000, cri: 2, ene: -4,
          msg: "Tu contrato era una servilleta escaneada. Aprendes lo que vale un abogado antes de firmar." } },
      ] },

    /* ===== 23600 Trading algorítmico ===== */
    { id: 23610, por: "Pusiste tu algoritmo a operar con dinero real", t: "Un desplome en cuatro minutos",
      x: "El mercado cae fuerte en cuatro minutos. Tu algoritmo vende, el precio cae más y vuelve a vender. Tienes el dedo sobre el botón de apagado.",
      o: [
        { t: "Apagarlo de inmediato", d: { cash: -3000, cri: 3,
          msg: "Lo apagas. Pierdes, pero lo que pierdes tiene fondo." } },
        { t: "Dejarlo: lo diseñaste para esto", d: { cash: -2000, cri: -2,
          msg: "Lo dejas correr. Pase lo que pase, ahora es problema de la lógica que escribiste.",
          luego: [{ en: 1, s: "mod", azar: [{ p: 55, id: 23615, bueno: false }, { p: 45, id: 23616, bueno: true }] }] } },
        { t: "Pasarlo a manual y operar tú", d: { cash: -1500, mod: 2, ene: -5,
          msg: "Te pones al teclado. Recuperas la mitad y descubres que tu algoritmo tenía más calma que tú." } },
      ] },
    { id: 23611, por: "Escribiste un algoritmo de trading", t: "Un operador quiere tu código",
      x: "El operador más veterano de la mesa te pide el código del algoritmo. Dice que es para aprender. Lleva veinte años sin aprender nada.",
      o: [
        { t: "Dárselo entero", d: { red: 2, rep: -2,
          msg: "Se lo das. Una semana después lo presenta como suyo, con tus comentarios y tus faltas de ortografía." } },
        { t: "Darle una versión sin lo importante", d: { red: 1, cri: 2,
          msg: "Le das el esqueleto sin el corazón. Él no lo nota y tú no se lo dices." } },
        { t: "Decirle que no", d: { red: -3, rep: 1,
          msg: "Le dices que no con educación. Él te deja de pasar información con la misma educación." } },
      ] },
    { id: 23612, empleado: true, por: "Pusiste tu algoritmo a operar con dinero real", t: "La mesa te triplica el capital",
      x: "El algoritmo cierra el año arriba y sin sustos. La mesa triplica el capital asignado y te pregunta si escala igual.",
      o: [
        { t: "Escalarlo de a poco", d: { cash: 6000, cri: 3, car: 2,
          msg: "Subes el tamaño en tramos y miras cómo se mueve el precio. Gana menos de lo posible y más de lo esperado." } },
        { t: "Escalarlo de una vez", d: { cash: 12000, car: 4, cri: -1,
          msg: "Gana más, pero el triple de tamaño mueve el precio en tu contra. Lo notas tarde, y pagas la lección." } },
        { t: "Quedarte con el tamaño de ahora", d: { cash: 3000, cri: 2, car: -1,
          msg: "Dices que no a más capital. La mesa no entiende a alguien que rechaza dinero ajeno." } },
      ] },
    { id: 23613, por: "Le pusiste límites de pérdida a tu algoritmo", t: "El interruptor lo apagó en mal momento",
      x: "Un susto de una tarde dispara tu límite y el algoritmo se apaga. Al día siguiente el mercado sube con fuerza y tú estás fuera.",
      o: [
        { t: "Respetar el límite: para eso está", d: { cash: -1000, cri: 4,
          msg: "Lo enciendes al otro día, igual que antes. La disciplina no sale en los informes, pero se nota." } },
        { t: "Aflojar el límite para la próxima", d: { cash: 2000, cri: -3,
          msg: "Lo aflojas un poco. Es lo que hace todo el mundo justo antes de perderlo todo." } },
      ] },
    { id: 23614, por: "Probaste tu algoritmo seis meses más en papel", t: "Tu algoritmo memorizaba el pasado",
      x: "Con datos nuevos, el algoritmo deja de ganar. No había descubierto nada: había memorizado tres años de historia. La prueba te salvó.",
      o: [
        { t: "Rehacerlo con datos que nunca vio", d: { mod: 5, cri: 3, ene: -5,
          msg: "Separas datos para entrenar y datos para probar, como dicen los libros. Gana menos, y de verdad." } },
        { t: "Contar en la mesa por qué no se usó", d: { rep: 3, cri: 2,
          msg: "Cuentas cómo casi te engañas. La mesa aprende más de tu error que de diez aciertos ajenos." } },
        { t: "Dejar el trading algorítmico", d: { ene: 3, car: -1,
          msg: "Archivas el proyecto. Te quedas con una certeza: el pasado es un mal profesor si solo lo memorizas." } },
      ] },
    { id: 23615, por: "Dejaste tu algoritmo vendiendo en un desplome", t: "El regulador revisa tu algoritmo",
      x: "El regulador investiga quién empujó la caída de aquella tarde. Tu algoritmo aparece en la lista de los que más vendieron.",
      o: [
        { t: "Entregar el código y la lógica completa", d: { cri: 3, rep: -2, ene: -4,
          msg: "Explicas cada regla a gente que no programa. Concluyen que fue torpeza, no mala fe. Algo es algo." } },
        { t: "Contratar un perito técnico", d: { cash: -4000, rep: -1,
          msg: "El perito habla por ti con palabras que nadie entiende. Funciona, que es lo que pagaste." } },
      ] },
    { id: 23616, por: "Dejaste tu algoritmo vendiendo en un desplome", t: "Tu algoritmo recompró en el piso",
      x: "Tu algoritmo vendió en la caída y recompró en el piso. Al cerrar el día, la cuenta está arriba. Nadie entiende cómo, y tú tampoco del todo.",
      o: [
        { t: "Estudiar por qué funcionó", d: { cash: 4000, mod: 4, cri: 2, ene: -3,
          msg: "Pasas una semana con los registros. Era una regla que escribiste de madrugada y no recordabas." } },
        { t: "Cobrar el mérito sin entenderlo", d: { cash: 4000, car: 3, cri: -3,
          msg: "Aceptas los aplausos. Lo que no entiendes también puede salir mal, y no vas a saber por qué." } },
      ] },

    /* ===== 23700 Un modelo con sesgo ===== */
    { id: 23710, por: "Revisaste un modelo que rechazaba a un barrio", t: "Encuentras la variable escondida",
      x: "El modelo usaba el código postal como atajo. Quitarlo es fácil; explicar por qué estuvo años ahí, no tanto.",
      o: [
        { t: "Contar el hallazgo dentro de la casa", d: { cri: 3, rep: 4, red: -2,
          msg: "Lo presentas en el comité tal cual. Varios se incomodan, y ese era el punto." } },
        { t: "Quitarla y documentarlo sin ruido", d: { cri: 3, mod: 2,
          msg: "Una línea menos de código y una página más de documentación. Nadie lo celebra." } },
        { t: "Convertirlo en norma para todos los modelos", d: { cri: 4, car: 2, ene: -4,
          msg: "Propones que cada modelo nuevo pase una revisión de sesgos antes de salir. La aprueban sin mucho entusiasmo.",
          luego: [{ en: 2, s: "rep", azar: [{ p: 55, id: 23715, bueno: true }, { p: 45, id: 23716, bueno: false }] }] } },
      ] },
    { id: 23711, empleado: true, por: "Apagaste un modelo de crédito con sesgo", t: "Te exigen volver a encenderlo",
      x: "Las solicitudes atrasadas ya son miles y el área comercial grita. La dirección te da una semana para encender el modelo, entendido o no.",
      o: [
        { t: "Encenderlo con revisión humana de rechazos", d: { cri: 3, car: 1, ene: -5,
          msg: "El modelo vuelve a decidir y alguien revisa cada rechazo. Lento, caro y correcto." } },
        { t: "Pedir otra semana y jugártela", d: { cri: 2, rep: 1, car: -3,
          msg: "Te dan la semana con muy mala cara. La usas entera, y la cara no mejora." } },
        { t: "Encenderlo tal cual y lavarte las manos", d: { car: 2, rep: -3, cri: -2,
          msg: "Lo enciendes. El barrio vuelve a quedar fuera y tú quedas con un informe a medio escribir." } },
      ] },
    { id: 23712, por: "Tuviste en tus manos un modelo con sesgo", t: "Un periodista pregunta por el barrio",
      x: "Un periodista tiene una lista de vecinos rechazados y una pregunta sencilla: si una máquina decide por dirección, ¿quién responde?",
      o: [
        { t: "Dar la entrevista y responder", d: { rep: 3, red: 2, ene: -3,
          msg: "Respondes con lo que sabes y lo que no. La nota sale dura, pero tu nombre sale entero." } },
        { t: "Mandar un comunicado de dos líneas", d: { ene: 1, rep: -2,
          msg: "Dos líneas que no dicen nada. La nota las cita completas, que es peor." } },
        { t: "Negarte y avisar a legal", d: { cri: 1, car: 1, rep: -3,
          msg: "Legal te felicita por no hablar. El barrio, en cambio, sí habla de ti." } },
      ] },
    { id: 23713, por: "Corregiste en silencio un modelo de crédito", t: "La corrección rompió otra cosa",
      x: "Al ajustar el modelo para el barrio, empezó a aprobar créditos que no debía en otra zona. La morosidad sube y nadie sabe que lo tocaste.",
      o: [
        { t: "Confesar el ajuste y arreglarlo bien", d: { cri: 4, rep: -3, car: -2,
          msg: "Lo cuentas todo. Te ganas un regaño y, más tarde, la confianza de los que saben de modelos." } },
        { t: "Arreglarlo otra vez en silencio", d: { mod: 2, cri: -3, ene: -4,
          msg: "Otro fin de semana, otro ajuste. Empiezas a notar que el silencio también cobra intereses." } },
      ] },
    { id: 23714, por: "Defendiste un modelo que rechazaba a un barrio", t: "Otro banco presta en ese barrio",
      x: "Un banco más chico empezó a prestar justo donde tu modelo rechazaba. La morosidad le salió normal y le está quitando clientes a tu casa.",
      o: [
        { t: "Admitir que el modelo se equivocó", d: { cri: 4, rep: 2, car: -2,
          msg: "Lo admites en el comité. Duele menos de lo que pensabas y sirve más de lo que esperabas." } },
        { t: "Copiarles la estrategia sin decir nada", d: { car: 2, cri: 1, rep: -1,
          msg: "Abres el barrio sin anunciarlo. Los vecinos se acuerdan de quién llegó primero." } },
        { t: "Decir que tuvieron suerte", d: { rep: -3, cri: -3,
          msg: "Lo dices en voz alta. La suerte del otro banco dura ya dos años y sigue sumando." } },
      ] },
    { id: 23715, por: "Propusiste una norma para revisar sesgos", t: "Tu norma se vuelve estándar",
      x: "La asociación de bancos adopta tu norma de revisión de sesgos. Te invitan a explicarla en un foro lleno de gente que antes no te contestaba.",
      o: [
        { t: "Ir y explicarla tú", d: { rep: 5, red: 5, ene: -3,
          msg: "Hablas veinte minutos y respondes una hora. Al salir tienes más tarjetas que en toda tu carrera." } },
        { t: "Mandar a alguien de tu equipo", d: { red: 2, rep: 2, ene: 2,
          msg: "Mandas a quien hizo la mitad del trabajo. Lo hace muy bien, y ahora el foro conoce a dos." } },
      ] },
    { id: 23716, por: "Propusiste una norma para revisar sesgos", t: "Te llaman «el que frena todo»",
      x: "Cada modelo nuevo pasa ahora por tu revisión. Los equipos se quejan de que todo tarda el doble y te ponen un apodo poco cariñoso.",
      o: [
        { t: "Automatizar la revisión", d: { mod: 4, red: 2, ene: -4,
          msg: "Escribes un programa que revisa los modelos por ti. Tarda una hora en vez de dos semanas. El apodo se queda." } },
        { t: "Sostener el proceso como está", d: { cri: 3, red: -3,
          msg: "No cedes. Los modelos salen más tarde y salen mejor. Nadie te lo agradece en la cara." } },
      ] },
  ],

  opciones: [
    { escena: 6, t: "Escribir un clasificador que lo ordene en una tarde", d: { mod: 5, red: 2, cri: -2, ene: -2,
      msg: "El script ordena casi todo bien y veinte archivos en la carpeta equivocada. Esos veinte los encuentra otro." } },
    { escena: 23, t: "Parametrizar el tipo de cambio en todos los modelos", d: { mod: 6, car: 2, ene: -6,
      msg: "Una semana sin dormir y ahora el tipo de cambio es una sola celda. La próxima devaluación se ajusta en un minuto." } },
    { escena: 40, t: "Dejar un bot operando y vigilar los registros", d: { mod: 4, ene: 2, cash: -1000,
      msg: "El bot pierde poco y tú aprendes mucho: cada error queda escrito en los registros, con hora y motivo." } },
    { escena: 109, t: "Reconstruir la trazabilidad desde los servidores", d: { cri: 4, mod: 3, red: -2, ene: -5,
      msg: "Sacas de los servidores quién tocó qué y cuándo. Impecable. También aparecen cosas que tu equipo prefería olvidar." } },
  ],

  finales: [
    { id: "l13_maquina", huellas: ["l13_automatizaste", "l13_sin_freno"], t: "Lo que no cabe en el código, sobra",
      x: "Automatizaste un área entera y encendiste tu algoritmo sin freno. Fuiste rápido en todo, también en dejar atrás a la gente que no cabía en el código." },
    { id: "l13_conciencia", huellas: ["l13_reconvertiste", "l13_apagaste_modelo"], t: "Máquinas con alguien detrás",
      x: "Protegiste a un equipo de tu propio script y apagaste un modelo que discriminaba. Escribiste máquinas toda la vida, pero nunca las dejaste decidir sin nadie detrás." },
  ],
};
