/* El Analista: escenas propias de la carrera de Administración (lote 12).
   Ids 22000-22999. Cada raíz propia usa su centena: raíz 22N00 -> consecuencias 22N10 a 22N19.
   Temas: la red de contactos como activo, dirigir gente, conflictos de equipo,
   banca privada, empresas familiares y vender lo que uno sabe hacer. */
module.exports = {
  carrera: "adm",

  huellas: {
    l12_recomendaste: "Recomendaste con todo a un compañero de promoción",
    l12_matices: "Recomendaste a un compañero con matices honestos",
    l12_formaste: "Formaste a un recomendado tuyo hasta que brilló",
    l12_mediaste: "Mediaste tú en un pleito entre dos analistas",
    l12_separaste: "Separaste a dos analistas que no se hablaban",
    l12_visitaste_familias: "Visitaste una por una a las familias que heredaste",
    l12_atajo_familia: "Moviste dinero de una familia por donde no debías",
    l12_sucesion_franca: "Le dijiste a un fundador quién debía sucederlo",
    l12_protocolo: "Le armaste un protocolo a una empresa familiar",
    l12_sacaste_estrella: "Sacaste a tu mejor vendedor por cómo trataba al equipo",
    l12_condiciones: "Le pusiste condiciones por escrito a un vendedor difícil",
    l12_miraste_otro_lado: "Miraste para otro lado con un vendedor que maltrataba",
    l12_vendiste_agenda: "Cobraste por abrirle tu agenda a un fondo extranjero",
    l12_presentaste_claro: "Presentaste gente con la comisión dicha de frente",
    l12_organizaste: "Organizaste el reencuentro de veinte años de tu promoción",
  },

  propias: [
    /* ===== 22100 Un compañero de promoción quiere entrar ===== */
    { id: 22100, min: 0, max: 2, empleado: true, t: "Un excompañero quiere entrar a tu firma",
      x: "Abren una vacante en tu área y un compañero de la universidad te pide un empujón. Fue bueno en los trabajos en grupo y flojo en los exámenes.",
      o: [
        { t: "Recomendarlo con todo, tu palabra por delante", d: { red: 4, rep: -1, deja: "l12_recomendaste",
          msg: "Le pasas su hoja de vida a tu jefe con una nota tuya. Desde hoy tu nombre va pegado al suyo.",
          luego: [{ en: 1, s: "red", azar: [{ p: 30, id: 22110, bueno: true }, { p: 35, id: 22111, bueno: false }, { p: 20, id: 22112 }, { p: 15, id: 22113 }] }] } },
        { t: "Recomendarlo con matices honestos", d: { cri: 3, red: 1, deja: "l12_matices",
          msg: "Escribes lo bueno y lo flojo. Tu jefe agradece el dato; tu compañero no sabe que hubo matices.",
          luego: [{ en: 1, azar: [{ p: 25, id: 22110 }, { p: 15, id: 22111 }, { p: 20, id: 22112 }, { p: 40, id: 22113 }] }] } },
        { t: "Decirle que no mezclas amistad y trabajo", d: { ene: 2, red: -3,
          msg: "Se lo dices con cariño. Contesta «claro, entiendo» con un punto final que pesa.",
          luego: [{ en: 1, azar: [{ p: 30, id: 22112 }, { p: 30, id: 22113 }, { p: 40, id: 22114 }] }] } },
      ] },

    /* ===== 22200 Dos analistas que no se hablan ===== */
    { id: 22200, min: 1, max: 4, t: "Dos analistas que no se hablan",
      x: "En tu equipo hay dos analistas que se escriben con copia a todos para no dirigirse la palabra. El trabajo ya empieza a notarlo.",
      o: [
        { t: "Sentarlos juntos y mediar tú", d: { ene: -3, cri: 2, red: 2, deja: "l12_mediaste",
          msg: "Una sala, una hora, tres cafés. No salen abrazados, pero salen hablando.",
          luego: [{ en: 1, s: "cri", azar: [{ p: 40, id: 22210, bueno: true }, { p: 20, id: 22211 }, { p: 15, id: 22212, bueno: false }, { p: 25, id: 22213 }] }] } },
        { t: "Separarlos: cada uno a un proyecto distinto", d: { ene: 1, mod: -1, deja: "l12_separaste",
          msg: "Reorganizas el tablero para que no coincidan. Funciona, aunque ahora tienes dos equipos a medias.",
          luego: [{ en: 1, azar: [{ p: 30, id: 22210 }, { p: 30, id: 22211 }, { p: 15, id: 22212 }, { p: 25, id: 22214 }] }] } },
        { t: "Pasárselo a recursos humanos", d: { ene: 2, red: -2,
          msg: "Lo mandas a quien le toca. Recursos humanos abre un expediente y agenda una reunión para dentro de un mes.",
          luego: [{ en: 1, azar: [{ p: 30, id: 22210 }, { p: 35, id: 22211 }, { p: 35, id: 22212 }] }] } },
      ] },

    /* ===== 22300 Heredas las familias de un banquero ===== */
    { id: 22300, min: 2, max: 4, empleado: true, t: "Heredas las familias de un banquero",
      x: "Un banquero privado se jubila y te pasan sus clientes: doce familias con dinero viejo que lo conocían a él, no a ti. Tienes un trimestre.",
      o: [
        { t: "Visitarlas una por una, en sus casas", d: { ene: -5, red: 5, deja: "l12_visitaste_familias",
          msg: "Doce visitas, doce cafés y una abuela que te pregunta si comes bien. Ya te conocen la cara.",
          luego: [{ en: 1, s: "red", azar: [{ p: 35, id: 22310, bueno: true }, { p: 25, id: 22311, bueno: false }, { p: 25, id: 22312 }, { p: 15, id: 22313 }] }] } },
        { t: "Pedirle al banquero que te presente en persona", d: { red: 3, ene: -2, cash: -1000,
          msg: "Lo invitas a almorzar con cada familia. Él cuenta anécdotas; tú escuchas, pagas y anotas.",
          luego: [{ en: 1, azar: [{ p: 30, id: 22310 }, { p: 15, id: 22311 }, { p: 20, id: 22312 }, { p: 35, id: 22313 }] }] } },
        { t: "Mandar una carta formal y un reporte impecable", d: { mod: 2, ene: 1, red: -2,
          msg: "El reporte es perfecto. Lo leen tres familias; las otras lo archivan sin abrir el sobre.",
          luego: [{ en: 1, azar: [{ p: 15, id: 22310 }, { p: 50, id: 22311 }, { p: 20, id: 22312 }, { p: 15, id: 22313 }] }] } },
      ] },

    /* ===== 22400 La sucesión de una empresa familiar ===== */
    { id: 22400, min: 2, max: 5, t: "El fundador quiere dejárselo todo al hijo",
      x: "El dueño de una empresa familiar te encarga su plan de sucesión. Quiere al hijo mayor de gerente. La que conoce el negocio es la hija menor.",
      o: [
        { t: "Recomendar a la hija, aunque al padre le duela", d: { cri: 4, rep: 2, red: -2, deja: "l12_sucesion_franca",
          msg: "Lo dices con números y con calma. El padre se queda mirando por la ventana un buen rato.",
          luego: [{ en: 2, s: "cri", azar: [{ p: 30, id: 22410, bueno: true }, { p: 30, id: 22411, bueno: false }, { p: 25, id: 22412 }, { p: 15, id: 22413 }] }] } },
        { t: "Proponer un protocolo familiar y un consejo", d: { mod: 2, cri: 3, ene: -3, deja: "l12_protocolo",
          msg: "Reglas escritas: quién entra, cómo se elige y quién arbitra. Lento, pero nadie sale herido el primer día.",
          luego: [{ en: 2, azar: [{ p: 30, id: 22410 }, { p: 10, id: 22411 }, { p: 25, id: 22412 }, { p: 35, id: 22413 }] }] } },
        { t: "Darle al padre el plan que pidió", d: { cash: 3000, red: 2, cri: -2,
          msg: "Sucesión a la medida del fundador. Cobras completo y el hijo mayor te aprieta la mano con fuerza.",
          luego: [{ en: 2, azar: [{ p: 40, id: 22414 }, { p: 35, id: 22412 }, { p: 25, id: 22413 }] }] } },
      ] },

    /* ===== 22500 Tu mejor vendedor maltrata a los juniors ===== */
    { id: 22500, min: 3, max: 6, t: "Tu mejor vendedor maltrata al equipo",
      x: "Trae un tercio de los ingresos del área. Este mes también hizo llorar a dos analistas y ya hay una queja por escrito.",
      o: [
        { t: "Sacarlo, aunque se lleve facturación", d: { rep: 3, red: 2, cash: -3000, deja: "l12_sacaste_estrella",
          msg: "Se lo dices en una sala sin ventanas. Recoge sus cosas en diez minutos y sale sin despedirse.",
          luego: [{ en: 1, s: "rep", azar: [{ p: 40, id: 22510, bueno: true }, { p: 45, id: 22511, bueno: false }, { p: 15, id: 22512 }] }] } },
        { t: "Ponerle condiciones por escrito y seguirlo de cerca", d: { cri: 3, ene: -3, deja: "l12_condiciones",
          msg: "Le das tres reglas y un mes. Firma con una sonrisa que no te gusta nada.",
          luego: [{ en: 1, s: "cri", azar: [{ p: 20, id: 22510 }, { p: 25, id: 22513, bueno: true }, { p: 40, id: 22514, bueno: false }, { p: 15, id: 22511 }] }] } },
        { t: "Mirar para otro lado: los números mandan", d: { cash: 3000, rep: -3, red: -3, deja: "l12_miraste_otro_lado",
          msg: "Archivas la queja. El trimestre cierra en récord y en la oficina se habla bajito.",
          luego: [{ en: 1, azar: [{ p: 40, id: 22512 }, { p: 35, id: 22514 }, { p: 25, id: 22511 }] }] } },
      ] },

    /* ===== 22600 Te ofrecen cobrar por abrir puertas ===== */
    { id: 22600, min: 4, max: 6, t: "Te ofrecen cobrar por abrir puertas",
      x: "Un fondo extranjero quiere entrar al país y no conoce a nadie. Te ofrece una comisión por cada reunión que le consigas con tus contactos.",
      o: [
        { t: "Aceptar y abrirle toda tu agenda", d: { cash: 5000, red: -2, rep: -1, deja: "l12_vendiste_agenda",
          msg: "Veinte correos el primer día. Tus contactos contestan; algunos, con signos de interrogación.",
          luego: [{ en: 1, s: "red", azar: [{ p: 30, id: 22610, bueno: true }, { p: 35, id: 22611, bueno: false }, { p: 20, id: 22612 }, { p: 15, id: 22613 }] }] } },
        { t: "Presentar solo a quien conoces bien, y avisar", d: { cash: 2000, cri: 3, red: 1, deja: "l12_presentaste_claro",
          msg: "Cinco presentaciones, todas con la comisión dicha de frente. Nadie se sorprende y nadie se ofende.",
          luego: [{ en: 1, azar: [{ p: 35, id: 22610 }, { p: 15, id: 22611 }, { p: 20, id: 22612 }, { p: 30, id: 22613 }] }] } },
        { t: "Negarte: tu red no está en venta", d: { red: 2, ene: 1,
          msg: "Le dices que no con amabilidad. Dos meses después ves que consiguió a otro que sí.",
          luego: [{ en: 1, azar: [{ p: 45, id: 22614 }, { p: 55, id: 22612 }] }] } },
      ] },

    /* ===== 22700 Veinte años de la promoción ===== */
    { id: 22700, min: 5, max: 6, t: "Veinte años de la promoción",
      x: "Te piden organizar el reencuentro de la universidad. Media promoción dirige empresas, la otra media busca trabajo y todos tienen algo que pedir.",
      o: [
        { t: "Organizarlo tú, con lista y mesas pensadas", d: { ene: -5, red: 6, cash: -1500, deja: "l12_organizaste",
          msg: "Tres meses de planillas y llamadas. La noche sale redonda y todos saben quién la armó.",
          luego: [{ en: 1, s: "red", azar: [{ p: 30, id: 22710, bueno: true }, { p: 30, id: 22711 }, { p: 25, id: 22712 }, { p: 15, id: 22713, bueno: false }] }] } },
        { t: "Ir a la fiesta y escuchar más que hablar", d: { red: 3, cri: 2,
          msg: "Cambias de mesa tres veces y preguntas por los hijos. Sales con siete tarjetas y ninguna promesa.",
          luego: [{ en: 1, azar: [{ p: 30, id: 22710 }, { p: 40, id: 22711 }, { p: 15, id: 22712 }, { p: 15, id: 22713 }] }] } },
        { t: "No ir: la red de verdad no se ve en fiestas", d: { ene: 3, red: -3,
          msg: "Te quedas en casa. Al día siguiente ves las fotos y tres caras que ya no reconoces.",
          luego: [{ en: 1, azar: [{ p: 40, id: 22711 }, { p: 60, id: 22714 }] }] } },
      ] },
  ],

  escenas: [
    /* ===== 22100 Un excompañero quiere entrar ===== */
    { id: 22110, empleado: true, por: "Recomendaste a un compañero de promoción", t: "Tu recomendado es el mejor de su camada",
      x: "Tu compañero resultó mejor en lo suyo de lo que nadie esperaba. Tu jefe te lo comenta con un tono que no sabes si es elogio.",
      o: [
        { t: "Pedirlo para tu equipo", d: { car: 2, mod: 2, red: 2, msg: "Te lo asignan. Ahora el éxito de tu recomendado también cuenta como tuyo, y sus errores también." } },
        { t: "Aprender de él sin complejos", d: { mod: 3, cri: 2, ene: -1, msg: "Le preguntas cómo arma sus modelos. Te lo explica encantado y sin una gota de condescendencia." } },
        { t: "Tomar distancia: que brille solo", d: { ene: 2, red: -2, msg: "Lo dejas volar por su cuenta. A los meses ya ni recuerda quién le pasó la hoja de vida." } },
      ] },
    { id: 22111, empleado: true, por: "Recomendaste a un compañero de promoción", t: "Tu recomendado no da la talla",
      x: "Lleva tres entregas tarde y tu jefe te pregunta, delante de todo el equipo, de dónde salió.",
      o: [
        { t: "Asumirlo y ayudarlo a enderezarse", d: { ene: -4, rep: 1, red: 3, msg: "Te quedas con él dos noches por semana revisando entregas. Tu jefe no dice nada, que ya es bastante.",
          luego: [{ en: 1, s: "red", azar: [{ p: 50, id: 22115, bueno: true }, { p: 50, id: 22116, bueno: false }] }] } },
        { t: "Decir que solo pasaste una hoja de vida", d: { rep: -3, red: -4, msg: "Técnicamente es verdad. Tu compañero se entera esa misma tarde por el pasillo." } },
        { t: "Hablar con él sin rodeos", d: { cri: 3, red: -1, ene: -1, msg: "Le dices que está quedando mal, y tú con él. Lo toma peor de lo esperado y mejor de lo temido." } },
      ] },
    { id: 22112, por: "Un compañero de promoción te pidió un empujón", t: "Tu compañero ahora está del lado del cliente",
      x: "Aquel compañero terminó en una empresa que hoy busca asesor para una compra. Él decide a quién se le da el mandato.",
      o: [
        { t: "Llamarlo como el viejo amigo que eres", d: { red: 4, car: 3, cash: 2000, msg: "Te contesta al segundo timbre. Hablan media hora de la universidad y cinco minutos del mandato." } },
        { t: "Ir por el canal formal, como cualquiera", d: { cri: 2, rep: 2, ene: -2, msg: "Mandas tu propuesta por la vía oficial. Él la lee entera y te escribe una línea: «bien hecho»." } },
        { t: "Dejar que otro de tu equipo lleve la relación", d: { ene: 2, red: -2, msg: "Te quitas el conflicto de encima. También te quitas el mandato, que se va con otra firma." } },
      ] },
    { id: 22113, por: "Un compañero de promoción te pidió un empujón", t: "Quiere saber por qué no lo contrataron",
      x: "La vacante se la dieron a otro. Tu compañero te invita un café y quiere saber, de verdad, qué falló.",
      o: [
        { t: "Decirle la verdad, aunque incomode", d: { cri: 2, red: 1, ene: -2, msg: "Le hablas de los exámenes y de cómo se vendió. Se queda callado y paga los dos cafés." } },
        { t: "Echarle la culpa al proceso", d: { red: 1, rep: -1, msg: "Le dices que fue política interna. Se va aliviado y sin aprender nada." } },
        { t: "Ofrecerte a preparar con él la próxima", d: { red: 3, ene: -3, msg: "Tres sábados de entrevistas de práctica. Consigue trabajo en otra firma y te manda una botella." } },
      ] },
    { id: 22114, empleado: true, por: "Le dijiste que no a un compañero de promoción", t: "Entró igual, por otra puerta",
      x: "Tu compañero consiguió el puesto sin tu ayuda. Ahora se sientan a dos escritorios y te saluda con una cortesía exacta.",
      o: [
        { t: "Invitarlo a almorzar y limpiar el aire", d: { red: 3, ene: -1, cash: -500, msg: "Pagas tú. A la mitad del almuerzo se ríe de algo de la universidad y la cortesía se afloja." } },
        { t: "Mantener la cortesía exacta", d: { ene: 1, red: -1, msg: "Buenos días, buenas tardes. Funciona como un contrato bien redactado: nadie se queja." } },
        { t: "Competir con él en cada entrega", d: { car: 3, mod: 2, ene: -4, red: -3, msg: "Ganas tres de cinco. Él gana las otras dos y la simpatía del piso." } },
      ] },
    { id: 22115, empleado: true, por: "Ayudaste a enderezarse a un recomendado tuyo", t: "Tu recomendado se enderezó",
      x: "Seis meses de cafés y correcciones. Hoy presentó solo ante el comité y nadie le encontró nada.",
      o: [
        { t: "Dejar que se lleve todo el crédito", d: { red: 4, rep: 2, deja: "l12_formaste", msg: "No dices una palabra. Él sí: en la cena de fin de año brinda por ti delante de todos." } },
        { t: "Recordarle a tu jefe quién lo formó", d: { car: 3, red: -2, msg: "Tu jefe toma nota. Tu compañero también, y no le gusta lo que anota." } },
      ] },
    { id: 22116, empleado: true, por: "Ayudaste a enderezarse a un recomendado tuyo", t: "Lo despiden igual",
      x: "No alcanzó. Lo despiden un viernes y tu jefe te mira como quien ya lo sabía desde el principio.",
      o: [
        { t: "Ayudarlo a buscar otro trabajo", d: { red: 3, ene: -2, msg: "Le consigues dos entrevistas con conocidos. Una sale. Te lo agradece más que el puesto original." } },
        { t: "Pasar la página rápido", d: { ene: 2, red: -2, rep: 1, msg: "No lo mencionas más. Tu jefe tampoco, y eso cuenta como perdón." } },
      ] },

    /* ===== 22200 Dos analistas que no se hablan ===== */
    { id: 22210, por: "Tuviste que resolver un pleito en tu equipo", t: "La tregua aguanta",
      x: "Los dos analistas trabajan juntos en la entrega más grande del año. No son amigos, pero el modelo cuadra a la primera.",
      o: [
        { t: "Reconocérselo a los dos en público", d: { red: 3, rep: 2, msg: "Lo dices en la reunión del lunes. Los dos miran la mesa a la vez, que ya es coordinación." } },
        { t: "No decir nada y no tentar la suerte", d: { ene: 2, msg: "Lo que funciona no se toca. Lo anotas en tu cuaderno con un signo de interrogación." } },
        { t: "Darles juntos otra entrega, más difícil", d: { car: 3, mod: 2, ene: -2, msg: "Refunfuñan los dos, cada uno por su lado. La entregan antes de plazo." } },
      ] },
    { id: 22211, por: "Tuviste que resolver un pleito en tu equipo", t: "Uno de los dos renuncia",
      x: "El más callado de los dos se va a la competencia. En la entrevista de salida dice que nadie lo protegió.",
      o: [
        { t: "Llamarlo y escuchar lo que no dijo", d: { red: 3, cri: 3, ene: -2, msg: "Te cuenta cosas que nunca viste desde tu escritorio. Cuelgas y revisas cómo repartes el trabajo." } },
        { t: "Reemplazarlo rápido y seguir", d: { ene: -2, car: 1, mod: -1, msg: "Contratas en tres semanas. El nuevo es bueno y tarda dos meses en entender el modelo." } },
        { t: "Pedirle al que se quedó que cubra ambos puestos", d: { car: 2, ene: -3, red: -3, msg: "Acepta sin protestar. Ahora el que no habla con nadie es él." } },
      ] },
    { id: 22212, por: "Tuviste que resolver un pleito en tu equipo", t: "El pleito estalla frente al cliente",
      x: "En plena reunión, uno corrige al otro con una frialdad que el cliente nota. Al salir, el cliente te pregunta si todo está bien.",
      o: [
        { t: "Reconocerlo y contarle cómo lo vas a resolver", d: { rep: 2, cri: 3, ene: -2, msg: "Le hablas claro. Asiente, no promete nada y pide que le mandes el acta por escrito.",
          luego: [{ en: 1, s: "rep", azar: [{ p: 55, id: 22215, bueno: true }, { p: 45, id: 22216, bueno: false }] }] } },
        { t: "Decir que fue un mal día", d: { rep: -2, ene: 1, msg: "El cliente sonríe por educación. Ya tuvo muchos malos días con otros asesores." } },
        { t: "Sacar a uno de los dos de la cuenta", d: { red: -3, car: 1, rep: 1, msg: "Problema resuelto en la cuenta y trasladado al resto del piso." } },
      ] },
    { id: 22213, por: "Mediaste tú en un pleito entre dos analistas", t: "Otra área quiere tu receta",
      x: "Se corrió la voz de cómo arreglaste lo de los dos analistas. Otra área tiene un pleito parecido y quiere que les hables.",
      o: [
        { t: "Dar una charla, aunque te quite dos tardes", d: { red: 4, rep: 3, ene: -3, msg: "Cuentas lo que hiciste sin adornos. Al final te aplauden más por lo de los tres cafés que por el método." } },
        { t: "Ofrecerte a mediar su caso en persona", d: { cri: 3, red: 3, ene: -4, msg: "Te sientas con dos desconocidos que se detestan. Sales con dolor de cabeza y dos aliados nuevos." } },
        { t: "Declinar: no eres terapeuta de nadie", d: { ene: 2, red: -1, msg: "Les mandas un libro de negociación. Te dan las gracias y no lo abren." } },
      ] },
    { id: 22214, por: "Separaste a dos analistas que no se hablaban", t: "Te sobra un analista",
      x: "Al separarlos, a uno le tocó un proyecto que se cayó. Lleva dos semanas sin nada que hacer y todo el piso lo sabe.",
      o: [
        { t: "Inventarle un proyecto interno que sirva", d: { mod: 2, red: 2, ene: -2, msg: "Le pides ordenar las plantillas del equipo. Lo hace tan bien que ahora todos le piden favores." } },
        { t: "Prestárselo a otra área", d: { red: 2, car: 1, msg: "La otra área te lo agradece. Tanto que ya no te lo quiere devolver." } },
        { t: "Devolverlo a su equipo de antes", d: { ene: 1, rep: -1, msg: "Vuelve a sentarse frente al otro. Se saludan con la cabeza y el aire se pone espeso." } },
      ] },
    { id: 22215, por: "Le admitiste a un cliente un pleito de tu equipo", t: "El cliente valora la franqueza",
      x: "El cliente renueva el mandato y comenta que prefiere asesores que admiten sus problemas antes que los que los esconden.",
      o: [
        { t: "Agradecer y cumplir lo que prometiste", d: { rep: 3, cash: 2500, msg: "Cumples al pie de la letra. El cliente lo cuenta en su gremio como ejemplo de algo." } },
        { t: "Usar la anécdota en tus propuestas", d: { red: 2, cash: 1500, rep: -1, msg: "Funciona dos veces. A la tercera, un cliente nuevo te pregunta si tu equipo siempre se pelea." } },
      ] },
    { id: 22216, por: "Le admitiste a un cliente un pleito de tu equipo", t: "El cliente pide otro equipo",
      x: "La franqueza no alcanzó. El cliente quiere otro equipo para la siguiente fase y te lo dice por escrito.",
      o: [
        { t: "Aceptarlo y armar un equipo nuevo", d: { ene: -3, car: -1, rep: 1, msg: "Armas otro equipo en una semana. Los dos analistas, por fin, coinciden en algo: les duele." } },
        { t: "Pedir una última oportunidad con los mismos", d: { rep: -2, red: 1, cri: -1, msg: "Te la dan de mala gana. Cada reunión se siente como un examen que nadie quiere aprobar." } },
      ] },

    /* ===== 22300 Heredas las familias de un banquero ===== */
    { id: 22310, empleado: true, por: "Heredaste la cartera de un banquero privado", t: "Te confían a los nietos",
      x: "El patriarca de una de las familias quiere que asesores a sus nietos, que acaban de heredar y quieren invertir en todo lo que ven en redes.",
      o: [
        { t: "Darles clases con su propio dinero", d: { red: 3, rep: 3, ene: -3, cash: 2000, msg: "Una tarde al mes, pizarra y portafolio en mano. Al tercer mes ya preguntan por comisiones." } },
        { t: "Ponerles un portafolio conservador y punto", d: { cri: 2, red: -2, cash: 1500, msg: "El abuelo aprueba. Los nietos abren una cuenta en otra plataforma con la mitad del dinero." } },
        { t: "Dejarles una parte para equivocarse", d: { red: 4, cri: 1, cash: 1000, msg: "Pierden un poco en una moneda digital y aprenden mucho. El abuelo dice que así aprendió él." } },
      ] },
    { id: 22311, empleado: true, por: "Heredaste la cartera de un banquero privado", t: "Una familia se va a la competencia",
      x: "La familia más grande de la cartera mueve su dinero a otro banco. Te enteras por la transferencia, no por ellos.",
      o: [
        { t: "Ir a verlos y preguntar por qué", d: { red: 2, cri: 3, ene: -2, msg: "Pides una cita y te la dan para dentro de dos semanas. Vas con una libreta y sin presentación.",
          luego: [{ en: 1, s: "red", azar: [{ p: 40, id: 22315, bueno: true }, { p: 60, id: 22316, bueno: false }] }] } },
        { t: "Soltarla y cuidar a las que quedan", d: { ene: 1, red: 2, car: -1, msg: "Llamas a las otras once esa misma semana. Ninguna se va. Tu jefe solo mira la que se fue." } },
        { t: "Ofrecer bajar comisiones para que vuelvan", d: { cash: -2000, red: 2, rep: -1, msg: "Vuelven con la mitad. Las otras familias se enteran del descuento en la primera cena." } },
      ] },
    { id: 22312, empleado: true, por: "Heredaste la cartera de un banquero privado", t: "Te piden algo que no está en el manual",
      x: "Una de las familias quiere mover dinero por una vía que cumplimiento no ve con buenos ojos. Dice que el banquero anterior lo hacía siempre.",
      o: [
        { t: "Negarte y explicar la norma", d: { cri: 4, rep: 3, red: -3, msg: "Lo explicas con paciencia. Te escuchan con la cara de quien piensa en cambiar de banquero." } },
        { t: "Consultarlo con cumplimiento antes de responder", d: { cri: 2, ene: -2, red: -1, msg: "Cumplimiento tarda tres semanas en decir que no. La familia nota cada uno de esos días." } },
        { t: "Hacerlo como lo hacía él", d: { cash: 3000, rep: -6, cri: -3, deja: "l12_atajo_familia", msg: "Sale sin problema. Ahora hay un papel con tu firma que nadie debería leer nunca." } },
      ] },
    { id: 22313, empleado: true, por: "Heredaste la cartera de un banquero privado", t: "El jubilado sigue mandando",
      x: "El banquero se jubiló, pero almuerza con tus familias cada semana. Te consultan a ti y le hacen caso a él.",
      o: [
        { t: "Convertirlo en aliado: invitarlo a las revisiones", d: { red: 4, rep: 2, car: -1, msg: "Se sienta al lado y asiente cuando hablas. Las familias empiezan a asentir también." } },
        { t: "Pedirle a tu jefe que le ponga límites", d: { car: 1, red: -4, msg: "Tu jefe lo llama. El jubilado cuenta en tres almuerzos que el banco lo echó como a un perro." } },
        { t: "Esperar a que se canse", d: { ene: 1, red: -1, msg: "No se cansa. Se compra un palo de golf nuevo y ahora juega con dos de tus clientes." } },
      ] },
    { id: 22315, empleado: true, por: "Fuiste a preguntar por qué se fue una familia", t: "La familia vuelve",
      x: "Te escucharon y reconocieron que se fueron por un descuido de antes, no tuyo. Vuelven con la mitad de su dinero.",
      o: [
        { t: "Agradecer y no prometer de más", d: { rep: 3, cash: 2000, msg: "Les dices que el próximo descuido lo vas a avisar tú antes que nadie. Les gusta la idea." } },
        { t: "Pedirles que te presenten a sus primos", d: { red: 4, cash: 1500, rep: -1, msg: "Te presentan a los primos con una ceja levantada. Los primos abren cuenta igual." } },
      ] },
    { id: 22316, empleado: true, por: "Fuiste a preguntar por qué se fue una familia", t: "Te dicen la verdad incómoda",
      x: "Se fueron porque tus reportes les parecían de banco y no de familia. No vuelven, pero te lo dicen sin rodeos.",
      o: [
        { t: "Rediseñar tus reportes con eso en mente", d: { cri: 4, red: 2, ene: -3, msg: "Menos tablas, más llamadas. Las otras familias notan el cambio y nadie sabe por qué fue." } },
        { t: "Tomarlo como un gusto personal y seguir", d: { ene: 2, cri: -1, msg: "Un gusto personal que ahora se gestiona en otro banco." } },
      ] },

    /* ===== 22400 La sucesión de una empresa familiar ===== */
    { id: 22410, por: "Asesoraste la sucesión de una empresa familiar", t: "La hija queda al frente",
      x: "La hija menor termina a cargo de la empresa familiar. Lo primero que hace es revisar a todos los asesores de su padre, tú incluido.",
      o: [
        { t: "Presentarte como ante un cliente nuevo", d: { cri: 2, red: 3, ene: -2, cash: 2000, msg: "Llegas con propuesta fresca y sin nostalgia. Te contrata con la condición de que la tutees." } },
        { t: "Recordarle lo que hiciste por la familia", d: { red: 1, rep: -1, cash: 1000, msg: "Te escucha con cortesía. Ella prefiere hablar del futuro, y tú hablaste del pasado." } },
        { t: "Ofrecer acompañar la transición sin cobrar", d: { red: 5, rep: 2, cash: -1500, ene: -3, msg: "Seis meses de reuniones gratis. Después te da el contrato más grande que ha firmado la empresa." } },
      ] },
    { id: 22411, por: "Asesoraste la sucesión de una empresa familiar", t: "El fundador te quita el mandato",
      x: "No le gustó lo que escuchó. Paga la última factura con retraso y les dice a sus amigos del club que lo tuyo es pura teoría.",
      o: [
        { t: "Escribirle una carta sin rencor", d: { red: 2, rep: 1, ene: -1, msg: "Le agradeces la confianza y le dejas la puerta abierta. Sin una sola palabra de más.",
          luego: [{ en: 1, s: "red", azar: [{ p: 45, id: 22415, bueno: true }, { p: 55, id: 22416, bueno: false }] }] } },
        { t: "Dejarlo ir y cuidar a tus otros clientes", d: { ene: 1, red: 1, car: -1, msg: "Llamas a los demás antes de que les llegue el chisme. Llegas primero, por poco." } },
        { t: "Contar tu versión a quien pregunte", d: { rep: -2, red: -2, msg: "La cuentas bien. El club prefiere la del fundador, que paga las rondas." } },
      ] },
    { id: 22412, por: "Asesoraste la sucesión de una empresa familiar", t: "Los hermanos se pelean por el control",
      x: "Los hijos del fundador ya no se hablan. Cada uno te llama por separado para pedirte que estés de su lado.",
      o: [
        { t: "No tomar partido y proponer un mediador", d: { cri: 3, rep: 2, red: -1, msg: "Ninguno de los dos queda contento. Es la primera vez en meses que coinciden en algo." } },
        { t: "Ponerte del lado del que tiene razón", d: { cri: 2, car: 1, red: -3, msg: "Tienes razón en quién tiene razón. El otro hermano te borra de su agenda y de la empresa." } },
        { t: "Proponerles vender la empresa y repartir", d: { cash: 4000, mod: 2, red: -2, msg: "Silencio largo en los dos teléfonos. A la semana te piden un mandato de venta, firmado por ambos." } },
      ] },
    { id: 22413, por: "Asesoraste la sucesión de una empresa familiar", t: "El fundador no suelta",
      x: "Plan firmado, sucesor nombrado, y el fundador sigue llegando a las siete a firmar cheques. Nadie se atreve a decirle nada.",
      o: [
        { t: "Decírselo tú, a solas", d: { cri: 2, rep: 2, red: -2, msg: "Lo escucha mirando el escritorio que ya no es suyo. Al otro día llega a las ocho, que ya es algo." } },
        { t: "Proponerle presidir el consejo y soltar la gerencia", d: { red: 3, cri: 2, ene: -2, msg: "Le das un título más grande y menos llaves. Lo acepta porque suena a ascenso." } },
        { t: "No es tu problema: cobrar y seguir", d: { cash: 1500, red: -2, msg: "Cobras la última factura. La empresa sigue con dos gerentes y medio." } },
      ] },
    { id: 22414, por: "Le diste a un fundador el plan que pedía", t: "El hijo te pide que lo rescates",
      x: "El hijo mayor lleva dos años al frente y la empresa pierde clientes. Te llama de noche y pide un plan discreto, sin que su padre sepa.",
      o: [
        { t: "Armarle el plan sin esconderle nada al padre", d: { cri: 3, rep: 2, ene: -3, msg: "Le dices que a escondidas no. Se enoja un día y al siguiente te pide que estés en la reunión." } },
        { t: "Hacerlo a escondidas, como pide", d: { cash: 3000, rep: -3, red: 2, msg: "Trabajas de noche, como él. El padre se entera en un mes y te llama por tu apellido." } },
        { t: "Decirle que necesita un gerente profesional", d: { cri: 3, red: -2, msg: "Se queda callado. Contrata a uno de tus contactos, que te debe una para siempre." } },
      ] },
    { id: 22415, por: "Le escribiste una carta sin rencor a un fundador", t: "El fundador vuelve a llamar",
      x: "Pasó un año y su sucesor no funcionó. El fundador te llama, carraspea y dice que quiere hablar de aquella carta.",
      o: [
        { t: "Volver sin decir «te lo dije»", d: { red: 4, rep: 3, cash: 3000, msg: "No lo dices. Él lo nota y te sirve el café en persona, que en esa casa es un honor." } },
        { t: "Volver cobrando el doble", d: { cash: 5000, red: -2, msg: "Paga sin regatear. También te recuerda cada mes cuánto le cuestas." } },
      ] },
    { id: 22416, por: "Le escribiste una carta sin rencor a un fundador", t: "Tu carta circula por el club",
      x: "El fundador enseña tu carta en el club como prueba de que los asesores no entienden a las familias. Dos posibles clientes la leen.",
      o: [
        { t: "Llamar a esos dos y explicarte", d: { red: 2, rep: 1, ene: -3, msg: "Uno te escucha y te contrata. El otro dice que la carta le pareció muy educada, lo cual no ayuda." } },
        { t: "No defenderte: la carta habla sola", d: { cri: 2, red: -2, msg: "La carta habla, sí. En un club donde todos escuchan al que paga las rondas." } },
      ] },

    /* ===== 22500 Tu mejor vendedor maltrata al equipo ===== */
    { id: 22510, por: "Le pusiste límites a tu mejor vendedor", t: "El equipo respira",
      x: "Sin gritos en el pasillo, los analistas empiezan a proponer ideas. Uno de ellos trae un cliente que nadie esperaba.",
      o: [
        { t: "Darle el cliente para que lo lleve", d: { red: 3, car: 2, cash: 2000, msg: "Lo lleva con nervios y sin errores. El resto del equipo empieza a buscar clientes también." } },
        { t: "Llevarlo tú y que aprenda a tu lado", d: { cash: 3000, red: 2, ene: -2, msg: "Te sigue a cada reunión con una libreta. Toma notas hasta de cómo saludas." } },
        { t: "Repartir el cliente entre todos", d: { red: 2, ene: 1, cash: 1500, msg: "Todos tocan un poco y nadie es dueño de nada. El cliente pregunta quién es su contacto." } },
      ] },
    { id: 22511, por: "Tuviste que lidiar con un vendedor que maltrataba", t: "Se lleva a sus clientes",
      x: "Se fue a la competencia y en tres semanas llamó a cada uno de sus clientes. La mitad ya firmó con él.",
      o: [
        { t: "Visitar a los que quedan, uno por uno", d: { red: 4, ene: -4, cash: -1000, msg: "Recorres la ciudad un mes entero. Los que quedan se quedan, y ahora te conocen a ti." } },
        { t: "Aceptar la pérdida y salir a vender tú", d: { car: 2, red: 2, ene: -3, msg: "Vuelves a hacer llamadas en frío como en tus primeros años. Te salen mejor que entonces." } },
        { t: "Mandarle una carta de abogados", d: { cash: -2000, cri: 1, rep: -1, msg: "Su contrato tenía una cláusula de no captar clientes. Tus abogados la subrayan en amarillo.",
          luego: [{ en: 1, s: "cri", azar: [{ p: 50, id: 22515, bueno: true }, { p: 50, id: 22516, bueno: false }] }] } },
      ] },
    { id: 22512, por: "Tuviste que lidiar con un vendedor que maltrataba", t: "Los juniors se van",
      x: "Tres analistas renuncian en el mismo mes. En las entrevistas de salida, los tres mencionan a la misma persona.",
      o: [
        { t: "Enfrentar por fin al vendedor", d: { rep: 2, cri: 2, cash: -2000, ene: -3, msg: "Tarde, pero lo haces. Los que quedan lo notan; los que se fueron, no." } },
        { t: "Reclutar más rápido de lo que se van", d: { ene: -4, car: 1, rep: -1, msg: "Contratas cuatro. A los seis meses quedan dos. La matemática no perdona." } },
        { t: "Defender los números ante quien pregunte", d: { rep: -4, cash: 2000, msg: "Los números se defienden solos. Tu reputación en las universidades, no tanto." } },
      ] },
    { id: 22513, por: "Le pusiste condiciones a tu mejor vendedor", t: "Cambió de verdad",
      x: "Pasaron seis meses. Sigue vendiendo como siempre y ahora almuerza con los analistas. Uno dice que aprende más de él que de nadie.",
      o: [
        { t: "Darle un equipo a cargo", d: { car: 3, red: 3, cash: 2000, msg: "Lo dirige con cuidado de quien ya rompió cosas. Es el equipo que menos rota del área." } },
        { t: "Celebrarlo sin bajar la guardia", d: { cri: 2, ene: -1, msg: "Le das la mano y sigues revisando las encuestas internas cada trimestre." } },
        { t: "Contarlo como caso en tu red", d: { red: 3, rep: 2, msg: "Tres colegas te piden consejo para sus propios vendedores difíciles. Ahora eres referencia en algo." } },
      ] },
    { id: 22514, por: "Tuviste que lidiar con un vendedor que maltrataba", t: "Volvió a las andadas",
      x: "Ayer le tiró un informe a un analista delante de un cliente. Ya no es un asunto interno.",
      o: [
        { t: "Sacarlo ahora, sin segunda vuelta", d: { rep: 3, cri: 2, cash: -3000, msg: "Lo haces esa misma tarde. El cliente que lo vio te llama para decirte que hiciste bien." } },
        { t: "Darle una última oportunidad", d: { rep: -3, red: -2, cash: 2000, msg: "La última de varias últimas. El equipo deja de creer en tus palabras." } },
        { t: "Mover al analista a otro equipo", d: { rep: -4, red: -3, ene: 1, msg: "Proteges a la víctima mudándola de piso. Todos entienden el mensaje, y no es el que querías." } },
      ] },
    { id: 22515, por: "Le mandaste abogados a un vendedor que se fue", t: "Llegan a un acuerdo",
      x: "La carta funcionó. Firma un acuerdo, te devuelve dos clientes y promete no tocar al resto durante un año.",
      o: [
        { t: "Cerrar el tema y no volver a nombrarlo", d: { ene: 3, cash: 2000, msg: "Guardas el acuerdo en un cajón. El nombre deja de sonar en las reuniones." } },
        { t: "Llamar ya a los clientes devueltos", d: { red: 3, cash: 3000, ene: -2, msg: "Les dices la verdad sobre lo que pasó. Uno se ríe; el otro te pide una reunión semanal." } },
      ] },
    { id: 22516, por: "Le mandaste abogados a un vendedor que se fue", t: "La pelea sale a la luz",
      x: "Respondió con una entrevista donde dice que tu equipo era un infierno y que él era lo único que funcionaba. Tu red la leyó entera.",
      o: [
        { t: "Contestar con datos, una sola vez", d: { rep: 1, cri: 2, ene: -2, msg: "Un comunicado corto, sin adjetivos. Nadie lo comparte, pero los que importan lo leen." } },
        { t: "Callar y dejar que el tiempo hable", d: { rep: -2, red: -1, ene: 2, msg: "El tiempo habla lento. Durante un año, en cada cena alguien te pregunta por el infierno." } },
      ] },

    /* ===== 22600 Te ofrecen cobrar por abrir puertas ===== */
    { id: 22610, por: "Le abriste puertas a un fondo extranjero", t: "Una de tus presentaciones cierra",
      x: "Una de las reuniones que conseguiste termina en compra. El fondo te paga lo pactado y te ofrece un extra si consigues otra igual.",
      o: [
        { t: "Buscar la siguiente con el mismo cuidado", d: { cash: 5000, red: 2, ene: -3, msg: "Tardas seis meses en encontrar la segunda. El fondo dice que valió la espera." } },
        { t: "Cobrar y retirarte del negocio de las puertas", d: { cash: 3000, rep: 2, ene: 2, msg: "Cierras la etapa con una buena historia y sin deberle nada a nadie." } },
        { t: "Pedir entrar en la operación como inversionista", d: { cash: -4000, car: 3, red: 2, msg: "Pones parte de tu comisión en la empresa. Ahora te importa mucho cómo le va." } },
      ] },
    { id: 22611, por: "Cobraste por abrirle tu agenda a un fondo", t: "Un contacto se siente usado",
      x: "Un viejo amigo de la universidad se entera de que cobraste por presentarlo. Te escribe una sola línea: «¿cuánto valgo?».",
      o: [
        { t: "Llamarlo y darle la explicación completa", d: { red: 2, ene: -2, cri: 1, msg: "Lo llamas esa misma noche. Te deja hablar sin interrumpir, que es peor que si gritara.",
          luego: [{ en: 1, s: "red", azar: [{ p: 50, id: 22615, bueno: true }, { p: 50, id: 22616, bueno: false }] }] } },
        { t: "Ofrecerle parte de la comisión", d: { cash: -1500, red: -1, rep: -1, msg: "La acepta. Algo se rompió del todo justo cuando la acepta." } },
        { t: "No contestar", d: { red: -4, ene: 1, msg: "El mensaje queda en visto para siempre. Tu amigo también." } },
      ] },
    { id: 22612, por: "Un fondo extranjero buscó tus contactos", t: "El fondo quedó mal con medio mercado",
      x: "El fondo extranjero rompió una oferta a última hora con una empresa local. Todo el mercado lo comenta y te preguntan qué sabes de ellos.",
      o: [
        { t: "Contar lo que sabes, sin adornos", d: { rep: 2, cri: 2, red: -1, msg: "Dices lo que viste y nada más. El fondo deja de escribirte; el mercado te escribe más." } },
        { t: "Guardar silencio y dejar que pase", d: { ene: 1, red: -1, msg: "Pasa, como todo. Algunos interpretan tu silencio como complicidad y otros como clase." } },
        { t: "Ofrecerte a reparar la relación", d: { red: 4, rep: 2, ene: -4, msg: "Sientas al fondo y a la empresa en la misma mesa. Nadie firma nada, pero vuelven a hablarse." } },
      ] },
    { id: 22613, por: "Le abriste puertas a un fondo extranjero", t: "Un cliente tuyo pregunta de qué lado estás",
      x: "Una de las empresas que presentaste al fondo es cliente tuyo en otra operación. Te pregunta, con mucha calma, de qué lado estás.",
      o: [
        { t: "Renunciar a la comisión y explicarlo todo", d: { cash: -2000, rep: 3, cri: 2, msg: "Le mandas el acuerdo con el fondo y una línea: «no cobro esta». Te cree, y lo cuenta." } },
        { t: "Sostener que son cosas distintas", d: { rep: -3, cash: 1000, msg: "Son cosas distintas, legalmente. Tu cliente usa otro adjetivo." } },
        { t: "Pedirle permiso por escrito para seguir", d: { cri: 3, red: 1, ene: -2, msg: "Lo firma después de leerlo dos veces. Ahora todos los papeles están en regla." } },
      ] },
    { id: 22614, por: "Le dijiste que no a un fondo extranjero", t: "El fondo vuelve con otra propuesta",
      x: "Al fondo le fue mal con el otro intermediario. Vuelve a buscarte: ahora quiere un asesor fijo, sin comisión por reunión.",
      o: [
        { t: "Aceptar la asesoría fija, con contrato claro", d: { cash: 4000, car: 2, ene: -3, msg: "Un contrato de dos páginas y ninguna agenda en venta. Te piden criterio, no teléfonos." } },
        { t: "Declinar otra vez", d: { red: 2, ene: 2, msg: "Lo declinas igual de amable. En el mercado se sabe que te buscaron dos veces." } },
      ] },
    { id: 22615, por: "Le explicaste a un amigo por qué cobraste", t: "Tu amigo lo entiende",
      x: "Escuchó, se rió y te dijo que la próxima vez le avises antes. Después te presentó a su cuñado, que también busca un fondo.",
      o: [
        { t: "Presentarlo gratis esta vez", d: { red: 4, rep: 2, msg: "Al cuñado le va bien y a tu amigo, mejor. En la promoción se habla de ti con cariño." } },
        { t: "Avisarle de la comisión desde el principio", d: { cash: 2000, cri: 2, red: 1, msg: "Lo dices antes del primer café. El cuñado asiente como quien ya sabía cómo funciona esto." } },
      ] },
    { id: 22616, por: "Le explicaste a un amigo por qué cobraste", t: "La promoción se entera",
      x: "Tu amigo lo contó en el grupo de la promoción. Nadie te dice nada directamente, pero tres invitaciones dejan de llegar.",
      o: [
        { t: "Escribir en el grupo y dar la cara", d: { rep: 1, red: 2, ene: -3, msg: "Un mensaje largo y sincero. Dos responden con un pulgar; uno te llama para tomar algo." } },
        { t: "Dejar que se enfríe", d: { red: -3, ene: 1, msg: "Se enfría. Tu lugar en el grupo, también." } },
      ] },

    /* ===== 22700 Veinte años de la promoción ===== */
    { id: 22710, por: "Fuiste al reencuentro de tu promoción", t: "Un compañero quiere vender su empresa",
      x: "El de la última fila hoy tiene la distribuidora más grande de la región. Quiere venderla y prefiere que la lleve alguien que lo conozca.",
      o: [
        { t: "Llevar la venta tú, con precio de amigo", d: { cash: 6000, red: 3, ene: -4, msg: "Le cobras menos de lo normal y trabajas más de lo normal. Así son los mandatos entre amigos.",
          luego: [{ en: 2, s: "cri", azar: [{ p: 55, id: 22715, bueno: true }, { p: 45, id: 22716, bueno: false }] }] } },
        { t: "Llevarla a precio de mercado", d: { cash: 9000, red: -1, ene: -4, msg: "Paga lo que cuesta y te exige lo que paga. Sin descuento por los apuntes que le prestaste." } },
        { t: "Pasársela a otro asesor para no mezclar", d: { red: 2, rep: 2, ene: 2, msg: "Le recomiendas a alguien de confianza. Tu compañero lo entiende y te invita a la firma igual." } },
      ] },
    { id: 22711, por: "Tu promoción cumplió veinte años", t: "Un compañero en apuros",
      x: "El más brillante de la carrera perdió su empresa y te escribe. No pide dinero: pide trabajo o, al menos, una presentación.",
      o: [
        { t: "Darle un lugar en tu equipo", d: { red: 4, rep: 2, cash: -2000, ene: -2, msg: "Llega con humildad y con veinte años de oficio. En seis meses ya trae sus propios clientes." } },
        { t: "Presentarlo a tres personas de tu agenda", d: { red: 3, ene: -1, msg: "Tres correos, tres cafés. Uno lo contrata y los otros dos te agradecen el dato." } },
        { t: "Mandarle un abrazo y una lista de vacantes", d: { ene: 1, red: -2, msg: "Te contesta «gracias, de verdad». Los dos saben que no es de verdad." } },
      ] },
    { id: 22712, por: "Fuiste al reencuentro de tu promoción", t: "La promoción quiere un club de inversión",
      x: "Cinco compañeros quieren juntar dinero para comprar empresas pequeñas y te piden que lo administres. Confianza sobra; reglas, ninguna.",
      o: [
        { t: "Aceptar, pero con reglas escritas", d: { cash: 4000, cri: 3, ene: -4, msg: "Redactas estatutos que nadie quiere leer. El primer desacuerdo se resuelve en diez minutos gracias a ellos." } },
        { t: "Entrar solo como inversionista", d: { cash: -2000, red: 2, msg: "Pones tu parte y dejas que otro administre. En cada reunión te preguntan qué opinas igual." } },
        { t: "Declinar: amigos y dinero no se mezclan", d: { ene: 2, red: -2, msg: "Lo dices con una sonrisa. El club se arma sin ti y tus amigos te dejan de contar cómo va." } },
      ] },
    { id: 22713, por: "Fuiste al reencuentro de tu promoción", t: "La noche termina mal",
      x: "Dos compañeros resucitan una pelea de hace veinte años en tu mesa. Uno es cliente tuyo y el otro quiere serlo.",
      o: [
        { t: "Separarlos y llevar a cada uno a su casa", d: { red: 3, rep: 2, ene: -3, msg: "Dos viajes en carro a la madrugada. Al día siguiente, los dos te escriben para pedir perdón." } },
        { t: "Tomar partido por tu cliente", d: { cash: 2000, red: -3, msg: "Tu cliente lo agradece. El otro ya no quiere serlo, y se lo cuenta a la promoción entera." } },
        { t: "Pedir la cuenta e irte", d: { ene: 2, red: -2, msg: "Te vas antes del postre. Las fotos de esa noche circulan sin ti, lo cual es una suerte." } },
      ] },
    { id: 22714, por: "No fuiste al reencuentro de tu promoción", t: "Te enteras tarde de un negocio",
      x: "En el reencuentro se armó una compra entre cuatro compañeros. Te enteras por la prensa, cuando ya tiene asesor.",
      o: [
        { t: "Llamar para felicitarlos y ofrecerte después", d: { red: 3, ene: -1, msg: "Te lo agradecen con sinceridad. La próxima vez te llaman antes, o eso dicen." } },
        { t: "Organizar tú el siguiente encuentro", d: { red: 4, ene: -3, cash: -1000, msg: "Lo organizas a los seis meses. Van menos, pero los que van te cuentan todo." } },
        { t: "Aceptar que la red también se riega", d: { cri: 2, ene: 1, red: -1, msg: "Lo anotas como lección. La red no se enoja; solo se olvida de ti." } },
      ] },
    { id: 22715, por: "Llevaste la venta de un compañero de promoción", t: "La distribuidora se vende bien",
      x: "Se vendió a buen precio y tu compañero lo cuenta en cada cena. Ya te llamaron dos de sus proveedores.",
      o: [
        { t: "Atenderlos a los dos con el mismo cuidado", d: { cash: 5000, red: 3, ene: -3, msg: "Dos mandatos nuevos de una sola cena. La red funcionando como dicen los libros." } },
        { t: "Quedarte solo con el mejor de los dos", d: { cash: 3000, cri: 2, msg: "Eliges bien. El otro proveedor se va con alguien más y no te guarda rencor." } },
      ] },
    { id: 22716, por: "Llevaste la venta de un compañero de promoción", t: "La amistad no resiste la negociación",
      x: "En la última ronda le recomendaste aceptar menos de lo que quería. Vendió, cobraste y ya no te saluda en el grupo.",
      o: [
        { t: "Buscarlo y hablarlo de frente", d: { red: 2, cri: 2, ene: -2, msg: "Le explicas los números otra vez. Entiende los números; la amistad tarda más." } },
        { t: "Aceptar el precio de haber sido honesto", d: { rep: 2, red: -2, msg: "Tenías razón y lo perdiste. A veces la cuenta sale así." } },
      ] },
  ],

  opciones: [
    { escena: 27, t: "Proponer un protocolo familiar antes que los números",
      d: { cri: 4, red: 3, ene: -4, car: -1, msg: "Les hablas de quién entra, quién hereda y quién arbitra. Siguen peleando, pero ahora por turnos." } },
    { escena: 14, t: "Preguntarle qué lo haría quedarse y rehacer su puesto",
      d: { red: 3, car: 2, ene: -4, cash: -1500, msg: "Le diseñas el rol a la medida y se queda. Dos más del equipo ya preguntan cuándo les toca." } },
    { escena: 9, t: "Pedirle presentaciones a tu promoción, no escribir en frío",
      d: { red: 5, car: 2, ene: -3, rep: -1, msg: "Diez compañeros te presentan a diez fondos. Te contestan todos, y ahora debes diez favores." } },
    { escena: 22, t: "Ofrecerte a liderar la integración de los equipos",
      d: { car: 5, cri: 2, red: -2, ene: -6, msg: "Te dan la integración. Conoces a todos los de ambos lados, y ahora todos te culpan del organigrama." } },
  ],

  finales: [
    { id: "l12_red_patrimonio", huellas: ["l12_organizaste", "l12_presentaste_claro"], t: "La red como patrimonio",
      x: "Armaste el reencuentro de tu promoción y presentaste gente con la comisión dicha de frente. Tu agenda fue tu capital y nunca tuviste que explicar de dónde salía." },
    { id: "l12_primero_gente", huellas: ["l12_mediaste", "l12_sacaste_estrella"], t: "Primero la gente",
      x: "Sentaste a dos analistas peleados en la misma mesa y sacaste a tu mejor vendedor por cómo trataba al equipo. Facturaste menos de lo que podías y nadie lloró en tu pasillo." },
  ],
};
