/* El Analista: escenas propias de la carrera de Economía (lote 8).
   Ids 18000-18999. Cada raíz propia usa su centena: raíz 18N00 -> consecuencias 18N10 a 18N16.
   Las x10 a x14 son de segundo nivel; las x15 y x16, de tercer nivel (hojas). */
module.exports = {
  carrera: "eco",

  huellas: {
    l8_contra_consenso: "Publicaste tu primer pronóstico lejos del consenso",
    l8_con_consenso: "Acercaste tu primer pronóstico al consenso",
    l8_nota_curva: "Avisaste a toda la mesa que la curva anunciaba recesión",
    l8_razon_temprano: "Tuviste razón antes de tiempo y aguantaste hasta el final",
    l8_indice_propio: "Publicaste tu propio índice de precios",
    l8_indice_referencia: "Tu índice de precios se volvió referencia",
    l8_avisaste_devaluacion: "Avisaste a tus clientes de una devaluación",
    l8_cubriste_callado: "Te cubriste de una devaluación sin avisar a nadie",
    l8_operaste_tesis: "Operaste con dinero tu propia lectura del ciclo",
    l8_firmaste_plan: "Firmaste un plan del gobierno contra la inflación",
    l8_criticaste_plan: "Declinaste asesorar al gobierno y lo analizaste desde fuera",
    l8_sostuviste_numero: "Sostuviste tu pronóstico ante tu mayor cliente",
    l8_cambiaste_numero: "Cambiaste tu pronóstico para no perder un cliente",
  },

  propias: [
    /* ===== 18000 Tu primer pronóstico con firma (temprana) ===== */
    { id: 18000, min: 0, max: 2, empleado: true, t: "Tu primer pronóstico con firma",
      x: "El informe mensual llevará tu proyección de inflación. El consenso del mercado dice una cosa; tu modelo, bastante otra.",
      o: [
        { t: "Publicar tu número, lejos del consenso", d: { cri: 3, rep: 2, ene: -2, deja: "l8_contra_consenso",
          msg: "Tu jefe lo lee dos veces y lo firma con una ceja levantada. El informe sale con tu número.",
          luego: [{ en: 1, s: "cri", azar: [{ p: 40, id: 18010, bueno: true }, { p: 35, id: 18011, bueno: false }, { p: 25, id: 18012 }] }] } },
        { t: "Acercarlo al consenso, por si acaso", d: { rep: 1, ene: 1, deja: "l8_con_consenso",
          msg: "Mueves dos decimales hacia donde están todos. Nadie reclama nunca por coincidir.",
          luego: [{ en: 1, azar: [{ p: 45, id: 18013 }, { p: 35, id: 18012 }, { p: 20, id: 18010 }] }] } },
        { t: "Publicar un rango tan ancho que no falle", d: { cri: 1, rep: -1,
          msg: "Entre bastante y muchísimo. Técnicamente imposible fallar; prácticamente imposible usarlo.",
          luego: [{ en: 1, azar: [{ p: 55, id: 18014 }, { p: 45, id: 18012 }] }] } },
      ] },

    /* ===== 18100 La curva se invirtió (temprana) ===== */
    { id: 18100, min: 0, max: 3, empleado: true, t: "La curva se invirtió",
      x: "Prestar a corto plazo paga más que prestar a largo. En tus clases eso anunciaba recesión. La mesa sigue comprando como si nada.",
      o: [
        { t: "Mandar una nota a toda la mesa", d: { cri: 3, rep: 1, red: -1, ene: -2, deja: "l8_nota_curva",
          msg: "Una página, un gráfico y la palabra recesión en el asunto. Alguien responde con un emoji de sueño.",
          luego: [{ en: 1, s: "cri", azar: [{ p: 35, id: 18110, bueno: true }, { p: 40, id: 18111 }, { p: 25, id: 18112 }] }] } },
        { t: "Decírselo a tu jefe y a nadie más", d: { cri: 2, ene: -1,
          msg: "Se lo cuentas en el ascensor. Asiente, dice «interesante» y se baja en su piso.",
          luego: [{ en: 1, azar: [{ p: 40, id: 18112 }, { p: 35, id: 18111 }, { p: 25, id: 18113 }] }] } },
        { t: "Callarte: la curva ya ha fallado antes", d: { ene: 1,
          msg: "Es cierto, ha fallado. También ha acertado. Decides no averiguar cuál de las dos toca.",
          luego: [{ en: 2, azar: [{ p: 55, id: 18113 }, { p: 45, id: 18114 }] }] } },
      ] },

    /* ===== 18200 El dato oficial no cuadra (temprana-media) ===== */
    { id: 18200, min: 1, max: 4, t: "El dato oficial no cuadra",
      x: "El banco central publica una inflación que no se parece a la de los anaqueles. Llevas meses anotando precios por tu cuenta y tu número es otro.",
      o: [
        { t: "Publicar tu propio índice de precios", d: { cri: 3, rep: 3, ene: -3, deja: "l8_indice_propio",
          msg: "Lo publicas con la metodología al pie. Al día siguiente lo comparte gente que no sabías que te leía.",
          luego: [{ en: 1, s: "cri", azar: [{ p: 35, id: 18210, bueno: true }, { p: 30, id: 18211, bueno: false }, { p: 35, id: 18212 }] }] } },
        { t: "Usar el dato oficial y anotar la duda", d: { cri: 1, ene: 1,
          msg: "Tus informes usan el número del banco central. En una nota al pie pides mirarlo con cuidado.",
          luego: [{ en: 1, azar: [{ p: 55, id: 18213 }, { p: 45, id: 18212 }] }] } },
        { t: "Llevárselo en privado a alguien del banco", d: { red: 3, cri: 1,
          msg: "Le mandas tu hoja a un técnico del banco central que conociste en la universidad. Contesta «gracias» y nada más.",
          luego: [{ en: 1, azar: [{ p: 45, id: 18214 }, { p: 35, id: 18212 }, { p: 20, id: 18211 }] }] } },
      ] },

    /* ===== 18300 El ancla cambiaria no aguanta (media) ===== */
    { id: 18300, min: 2, max: 4, t: "El ancla cambiaria no aguanta",
      x: "Las reservas caen cada mes y el tipo de cambio oficial sigue fijo. Tus números dicen que se rompe pronto. Tus clientes deben en dólares.",
      o: [
        { t: "Avisar a tus clientes ya", d: { cri: 3, red: 2, ene: -2, deja: "l8_avisaste_devaluacion",
          msg: "Les escribes uno por uno: cúbranse. Algunos te agradecen; otros te llaman alarmista.",
          luego: [{ en: 1, s: "cri", azar: [{ p: 40, id: 18310, bueno: true }, { p: 35, id: 18311 }, { p: 25, id: 18312, bueno: false }] }] } },
        { t: "Cubrirte tú y no decir nada", d: { cash: 3000, rep: -2, deja: "l8_cubriste_callado",
          msg: "Pasas tus ahorros a dólares en silencio. Duermes mejor. Tus clientes también, pero por ignorancia.",
          luego: [{ en: 1, azar: [{ p: 45, id: 18314 }, { p: 35, id: 18313 }, { p: 20, id: 18311 }] }] } },
        { t: "Esperar más señales antes de alarmar", d: { cri: 1, ene: 1,
          msg: "Decides esperar otro dato. Las reservas, mientras tanto, no esperan a nadie.",
          luego: [{ en: 1, azar: [{ p: 55, id: 18313 }, { p: 45, id: 18311 }] }] } },
      ] },

    /* ===== 18400 Te dejan operar tu lectura del ciclo (media-alta) ===== */
    { id: 18400, min: 3, max: 6, empleado: true, t: "Te dejan operar tu lectura del ciclo",
      x: "El director de inversiones lee tus informes y te ofrece una parte del fondo para operar tu tesis. Si gana, es mérito tuyo. Si pierde, también.",
      o: [
        { t: "Una posición grande y concentrada", d: { car: 3, ene: -3, deja: "l8_operaste_tesis",
          msg: "Pones casi todo el cupo en una sola idea. Por primera vez, tu lectura del ciclo tiene precio de mercado.",
          luego: [{ en: 1, s: "cri", azar: [{ p: 35, id: 18410, bueno: true }, { p: 30, id: 18411 }, { p: 35, id: 18412, bueno: false }] }] } },
        { t: "Una posición chica, con límite de pérdida", d: { cri: 3, ene: -1, deja: "l8_operaste_tesis",
          msg: "Usas un tercio del cupo y fijas dónde te sales. El director dice «prudente» en un tono difícil de leer.",
          luego: [{ en: 1, azar: [{ p: 40, id: 18411 }, { p: 35, id: 18410, bueno: true }, { p: 25, id: 18413 }] }] } },
        { t: "Rechazarlo: tu trabajo es pensar", d: { cri: 1, car: -2, ene: 2,
          msg: "Dices que un economista que opera deja de ver con claridad. Suena sabio. También suena a miedo.",
          luego: [{ en: 1, azar: [{ p: 50, id: 18413 }, { p: 50, id: 18414 }] }] } },
      ] },

    /* ===== 18500 El gobierno te pide firmar un plan (alta) ===== */
    { id: 18500, min: 4, max: 6, t: "El gobierno te pide firmar un plan",
      x: "El ministerio de finanzas arma un plan para frenar la inflación y quiere economistas del sector privado en su consejo asesor. Tu nombre está en la lista.",
      o: [
        { t: "Aceptar y firmar el plan", d: { rep: 3, red: 4, ene: -4, deja: "l8_firmaste_plan",
          msg: "Pones tu firma al lado de la del ministro. Tu teléfono suena el doble desde esa tarde.",
          luego: [{ en: 2, s: "cri", azar: [{ p: 35, id: 18510, bueno: true }, { p: 40, id: 18511, bueno: false }, { p: 25, id: 18512 }] }] } },
        { t: "Asesorar sin poner tu firma", d: { red: 3, cri: 2, ene: -3,
          msg: "Vas a las reuniones, opinas y no firmas. El ministro acepta con la sonrisa de quien ya tomó nota.",
          luego: [{ en: 2, azar: [{ p: 35, id: 18513 }, { p: 30, id: 18510 }, { p: 20, id: 18511 }, { p: 15, id: 18512 }] }] } },
        { t: "Declinar y analizarlo desde fuera", d: { rep: 2, ene: 1, deja: "l8_criticaste_plan",
          msg: "Agradeces y declinas. Tu siguiente informe trae el plan desarmado pieza por pieza.",
          luego: [{ en: 1, azar: [{ p: 55, id: 18514 }, { p: 45, id: 18510 }] }] } },
      ] },

    /* ===== 18600 Tu mayor cliente quiere otro número (alta) ===== */
    { id: 18600, min: 4, max: 6, t: "Tu mayor cliente quiere otro número",
      x: "El banco que más te paga va a colocar bonos y tu pronóstico de recesión le estorba. Te piden «revisar» el escenario antes del informe trimestral.",
      o: [
        { t: "Sostener el número tal cual", d: { cri: 3, rep: 4, ene: -2, deja: "l8_sostuviste_numero",
          msg: "Respondes que el número es el número. Del otro lado, un silencio de esos que se facturan.",
          luego: [{ en: 1, s: "rep", azar: [{ p: 35, id: 18610, bueno: true }, { p: 35, id: 18611, bueno: false }, { p: 30, id: 18612 }] }] } },
        { t: "Suavizar el texto, no el número", d: { cri: 1, red: 2, rep: -1,
          msg: "Donde decía recesión ahora dice «desaceleración marcada». El número no se mueve; el tono, bastante.",
          luego: [{ en: 1, azar: [{ p: 40, id: 18614 }, { p: 35, id: 18612 }, { p: 25, id: 18613 }] }] } },
        { t: "Cambiarlo: el banco paga las cuentas", d: { cash: 5000, rep: -3, cri: -2, deja: "l8_cambiaste_numero",
          msg: "La recesión pasa a ser un escenario de riesgo en la página once. El banco renueva el contrato esa semana.",
          luego: [{ en: 1, azar: [{ p: 40, id: 18613, bueno: false }, { p: 35, id: 18614 }, { p: 25, id: 18612 }] }] } },
      ] },
  ],

  escenas: [
    /* ===== 18000 Tu primer pronóstico con firma ===== */
    { id: 18010, empleado: true, por: "Publicaste tu primer pronóstico de inflación", t: "El dato salió a tu favor",
      x: "El dato oficial salió y tu número quedó entre los más cercanos del mes. Un cliente de la firma pregunta quién lo hizo.",
      o: [
        { t: "Escribir una nota con tu método", d: { cri: 3, red: 3, ene: -3,
          msg: "Tres páginas sobre cómo llegaste ahí. El cliente la reenvía a gente que no conoces.",
          luego: [{ en: 1, azar: [{ p: 65, id: 18015, bueno: true }, { p: 35, id: 18016 }] }] } },
        { t: "Dejar que el número hable", d: { rep: 2, ene: 1,
          msg: "No dices nada. El cliente le pregunta a tu jefe, y tu jefe se lleva el mérito con una sonrisa." } },
        { t: "Pedirle a tu jefe la columna del mes", d: { car: 3, ene: -2,
          msg: "Te la da, con una advertencia: ahora se va a notar cuando falles." } },
      ] },
    { id: 18011, empleado: true, por: "Publicaste tu primer pronóstico de inflación", t: "Fallaste por mucho y con firma",
      x: "El dato salió muy lejos de tu número. Los que se pegaron al consenso fallaron poco. Tú fallaste sin compañía y con tu nombre al pie.",
      o: [
        { t: "Escribir una nota explicando el error", d: { cri: 4, rep: -1, ene: -3,
          msg: "Explicas qué supuesto se rompió y por qué. Duele escribirlo. Se lee bien.",
          luego: [{ en: 1, s: "cri", azar: [{ p: 50, id: 18015, bueno: true }, { p: 50, id: 18016 }] }] } },
        { t: "Volver al consenso el mes siguiente", d: { rep: 1, cri: -2,
          msg: "Tu siguiente pronóstico sale idéntico al de todos. Tu jefe respira aliviado." } },
        { t: "Revisar el modelo en silencio", d: { mod: 4, ene: -2,
          msg: "Encuentras el supuesto roto un domingo a medianoche. No se lo cuentas a nadie." } },
      ] },
    { id: 18012, por: "Publicaste tu primer pronóstico de inflación", t: "Nadie leyó tu pronóstico",
      x: "Revisas las estadísticas del informe. Tu sección la abrieron cuatro personas, y una eras tú.",
      o: [
        { t: "Escribir más corto y con titular", d: { rep: 2, ene: -1,
          msg: "Una idea por párrafo y un titular que se entiende. Las lecturas se triplican, partiendo de casi nada." } },
        { t: "Mandárselo directo a diez clientes", d: { red: 4, ene: -2,
          msg: "Lo mandas uno por uno. Dos contestan. Uno quiere un café." } },
        { t: "Aceptar que el informe es para el archivo", d: { ene: 2, car: -1,
          msg: "Lo escribes en la mitad del tiempo. Nadie nota la diferencia, que es justo el problema." } },
      ] },
    { id: 18013, empleado: true, por: "Acercaste tu primer pronóstico al consenso", t: "Fallaron todos juntos",
      x: "El dato sorprendió a todo el mercado. Tu número, pegado al consenso, falló como los demás. Tu modelo original había acertado.",
      o: [
        { t: "Enseñarle a tu jefe la versión original", d: { cri: 2, rep: -1,
          msg: "La mira y dice: «la próxima, publícala». Muy fácil decirlo ahora." } },
        { t: "Archivarla con fecha y aprender", d: { cri: 3, ene: -1,
          msg: "Guardas la versión original con fecha. La próxima vez que dudes, la vas a abrir." } },
        { t: "Consolarte: fallar en grupo no cuesta", d: { ene: 2, cri: -2,
          msg: "Es verdad, no cuesta nada. Tampoco paga nada." } },
      ] },
    { id: 18014, por: "Publicaste un pronóstico con un rango muy ancho", t: "Tu rango no le sirve a nadie",
      x: "Un cliente te escribe: necesita un número para su presupuesto y en tu rango cabe cualquier cosa. Te pide que te mojes.",
      o: [
        { t: "Darle tu número central y defenderlo", d: { cri: 3, red: 2, ene: -1,
          msg: "Le das un número y sus razones. Lo usa en su presupuesto y te lo agradece con un correo seco." } },
        { t: "Explicarle la incertidumbre en escenarios", d: { mod: 3, rep: 1, ene: -2,
          msg: "Tres escenarios con su probabilidad cada uno. Le gusta más de lo que esperabas." } },
        { t: "Mantener el rango: así es la economía", d: { rep: -3,
          msg: "Le respondes con una frase de manual. No vuelve a escribir." } },
      ] },
    { id: 18015, empleado: true, por: "Escribiste una nota sobre tu pronóstico", t: "Un fondo quiere tu lectura cada mes",
      x: "Un fondo leyó tu nota y pide recibir tu lectura todos los meses, antes que nadie. Tu firma no tiene ese producto.",
      o: [
        { t: "Proponerle a tu jefe venderlo", d: { car: 4, cash: 2000, ene: -2,
          msg: "Tu jefe le pone precio y te deja el producto. Por fin tienes un lector que paga." } },
        { t: "Mandársela gratis, como favor", d: { red: 5,
          msg: "El fondo agradece. Un favor a un fondo es una moneda que se cobra años después." } },
        { t: "Decir que no quieres compromisos", d: { ene: 2, red: -2,
          msg: "Declinas con educación. El fondo encuentra a otro que le escriba cada mes." } },
      ] },
    { id: 18016, empleado: true, por: "Escribiste una nota sobre tu pronóstico", t: "Tu jefe quiere ver todo antes",
      x: "Desde aquella nota, todo lo que escribes pasa primero por el escritorio de tu jefe. Dice que es por cuidar la marca de la firma.",
      o: [
        { t: "Aceptar el filtro y escribir mejor", d: { cri: 2, ene: -1,
          msg: "Tus textos vuelven con tachones. Algunos tienen razón, cosa que molesta más." } },
        { t: "Pedir firmar tus notas con tu nombre", d: { car: 2, rep: 2, red: -2,
          msg: "Te lo concede a medias: tu nombre va, pero en letra pequeña y al final." } },
      ] },

    /* ===== 18100 La curva se invirtió ===== */
    { id: 18110, por: "Mandaste una nota anunciando recesión", t: "Llegó la recesión y alguien guardó tu nota",
      x: "La economía se frenó como decía la curva. Un director encontró tu nota vieja y la reenvió a toda la firma con tu nombre arriba.",
      o: [
        { t: "Pedir un puesto en estrategia", d: { car: 5, ene: -2,
          msg: "Te mueven a estrategia. Ahora tu trabajo es tener razón a tiempo, que es bastante más difícil." } },
        { t: "Agradecer y no hacer ruido", d: { rep: 3, red: 2,
          msg: "Contestas con una línea. La humildad de quien acertó se recuerda más que el acierto." } },
        { t: "Escribir la siguiente: cuándo se sale", d: { cri: 4, rep: 2, ene: -3,
          msg: "Ya nadie manda emojis de sueño. Ahora todos leen, y eso pesa." } },
      ] },
    { id: 18111, por: "Advertiste de una recesión que no llegaba", t: "Un año y la recesión no llega",
      x: "La curva sigue invertida, la economía sigue creciendo y en la mesa ya te apodan «Recesión». Los que compraron ganaron.",
      o: [
        { t: "Sostener la tesis: el rezago es largo", d: { cri: 3, rep: -2, ene: -2,
          msg: "Explicas que la curva avisa con meses de ventaja, a veces muchos. Te escuchan con cara de paciencia.",
          luego: [{ en: 1, s: "cri", azar: [{ p: 55, id: 18115, bueno: true }, { p: 45, id: 18116, bueno: false }] }] } },
        { t: "Admitir que te adelantaste", d: { rep: 1, cri: 1,
          msg: "Dices que te adelantaste. Es cierto, y suena peor de lo que es." } },
        { t: "No volver a hablar del ciclo", d: { ene: 2, cri: -2, car: -1,
          msg: "Nadie te lo vuelve a sacar. Tampoco te vuelven a preguntar nada." } },
      ] },
    { id: 18112, empleado: true, por: "Advertiste que la curva anunciaba recesión", t: "Tu jefe presentó tu lectura",
      x: "En el comité trimestral, tu jefe presenta la curva invertida como su gran advertencia del año. Tu gráfico, con otro color.",
      o: [
        { t: "Hablarlo en privado con tu jefe", d: { rep: 1, red: -1,
          msg: "Te dice que en un equipo las ideas son de todos. Las suyas, sobre todo." } },
        { t: "Dejarlo pasar: la idea ya llegó", d: { cri: 2, ene: 1, car: -1,
          msg: "La firma se protege gracias a tu gráfico. Nadie lo sabe, pero la firma está protegida." } },
        { t: "Reenviar tu correo original al comité", d: { rep: 3, red: -4, car: 1,
          msg: "La fecha del correo habla por ti. Tu jefe no te habla en un mes." } },
      ] },
    { id: 18113, por: "Viste venir la recesión y no quedó por escrito", t: "Llegó la recesión sin tu firma",
      x: "La recesión llegó y la mesa perdió fuerte. Tú la viste venir, pero no hay un solo papel que lo diga.",
      o: [
        { t: "Escribir desde ahora todo lo que ves", d: { cri: 3, ene: -1,
          msg: "Cada lectura queda en un correo con fecha. Por si acaso, y por ti." } },
        { t: "Contar que lo viste venir", d: { rep: -3,
          msg: "«Yo lo sabía», sin papel, es la frase menos creída del sector." } },
        { t: "Comprar en la caída con tu cuenta", d: { cash: 2500, cri: 2, ene: -2,
          msg: "Ya que no lo dijiste, al menos lo operas. Compras cuando todos venden." } },
      ] },
    { id: 18114, por: "Viste la curva invertida y no dijiste nada", t: "La fiesta siguió un año más",
      x: "La economía no se frenó. La mesa ganó, hubo bonos para todos y tu silencio pasó por prudencia.",
      o: [
        { t: "Celebrar con el resto", d: { ene: 3, cash: 1500,
          msg: "Cobras el bono sin culpa. La curva sigue invertida, por cierto." } },
        { t: "Seguir vigilando la curva por tu cuenta", d: { cri: 3, ene: -1,
          msg: "Llevas una hoja con la curva de cada semana. Nadie te la pidió, y por eso la entiendes." } },
      ] },
    { id: 18115, por: "Sostuviste tu tesis de recesión contra la mesa", t: "Llegó, tarde y fuerte",
      x: "La recesión por fin llegó, mucho después de tu nota. Los que se reían ahora te preguntan qué viene.",
      o: [
        { t: "Contestarles con la siguiente lectura", d: { cri: 4, rep: 4, car: 2, ene: -2, deja: "l8_razon_temprano",
          msg: "No cobras la deuda; das la lectura siguiente. Eso, en la mesa, se nota más que cualquier reclamo." } },
        { t: "Recordarles quién se reía", d: { rep: -1, ene: 2, deja: "l8_razon_temprano",
          msg: "Lo disfrutas cinco minutos. Ellos lo recuerdan cinco años." } },
      ] },
    { id: 18116, empleado: true, por: "Sostuviste tu tesis de recesión contra la mesa", t: "Te quitan el tema del ciclo",
      x: "Pasó otro año sin recesión. Tu jefe te pide que dejes el ciclo a otros y vuelvas a lo operativo.",
      o: [
        { t: "Aceptarlo y seguir la curva en privado", d: { cri: 2, car: -2, ene: 1,
          msg: "De día haces lo operativo. De noche actualizas la curva. Alguna vez va a tener razón." } },
        { t: "Pedir cambio a otra área", d: { car: 1, red: 2, ene: -2,
          msg: "Te vas a un área donde nadie conoce tu apodo de la mesa. Al menos por un tiempo." } },
      ] },

    /* ===== 18200 El dato oficial no cuadra ===== */
    { id: 18210, por: "Publicaste tu propio índice de precios", t: "Tu índice se volvió referencia",
      x: "Medios, fondos y hasta alguna embajada citan tu índice cada mes. Mantenerlo te come los fines de semana.",
      o: [
        { t: "Cobrar a los que lo usan", d: { cash: 4000, red: -2, deja: "l8_indice_referencia",
          msg: "Los fondos pagan sin chistar. Los medios dejan de citarte y citan al que lo da gratis." } },
        { t: "Mantenerlo gratis y público", d: { rep: 5, ene: -4, deja: "l8_indice_referencia",
          msg: "Sigues cada domingo con la hoja de precios. Tu nombre ya circula sin que lo empujes." } },
        { t: "Cedérselo a una universidad", d: { red: 3, rep: 2, ene: 3,
          msg: "Un grupo de estudiantes lo mantiene ahora. Tu nombre queda en la metodología, que nadie lee." } },
      ] },
    { id: 18211, por: "Pusiste en duda el dato oficial de inflación", t: "Te llama alguien del gobierno",
      x: "Una voz amable de un ministerio te sugiere que tus números «generan zozobra» y que sería bueno revisarlos.",
      o: [
        { t: "Seguir publicando, con más método", d: { cri: 2, rep: 3, ene: -3,
          msg: "Documentas cada precio con fecha y lugar. Si van a discutir, que discutan con la hoja.",
          luego: [{ en: 1, s: "rep", azar: [{ p: 55, id: 18215, bueno: true }, { p: 45, id: 18216, bueno: false }] }] } },
        { t: "Dejar de publicar sin explicar por qué", d: { rep: -3, ene: 2,
          msg: "El índice desaparece. Tus lectores sacan sus conclusiones, y no son sobre la inflación." } },
        { t: "Publicarlo solo para clientes privados", d: { cash: 2000, red: 2, rep: -1,
          msg: "El número sigue existiendo, pero detrás de una clave. La zozobra ahora la pagan tus clientes." } },
      ] },
    { id: 18212, por: "Dudaste del dato oficial de inflación", t: "El banco central corrige la serie",
      x: "Meses después, el banco central revisa la inflación hacia arriba sin hacer ruido. Tu número estaba más cerca que el suyo.",
      o: [
        { t: "Señalarlo en tu próximo informe", d: { rep: 3, red: -1,
          msg: "Un párrafo, sin adjetivos. Lo leen los que tenían que leerlo." } },
        { t: "Ajustar tus modelos y callar", d: { mod: 3, cri: 2,
          msg: "Rehaces las series con el dato corregido. Ganar en silencio también es ganar." } },
        { t: "Explicárselo a tus clientes en una llamada", d: { red: 3, ene: -2,
          msg: "Una hora de llamada con gráficos. Dos clientes te piden que los avises antes la próxima vez." } },
      ] },
    { id: 18213, por: "Usaste el dato oficial aunque dudabas de él", t: "Un cliente perdió con el dato oficial",
      x: "Un cliente ajustó sus contratos al dato oficial siguiendo tu informe. Ahora la inflación real se los come y te pregunta por tu nota al pie.",
      o: [
        { t: "Asumir que debiste decirlo más claro", d: { cri: 3, red: 2, rep: -1,
          msg: "Le dices que la duda merecía más que una nota al pie. Se queda, con menos confianza." } },
        { t: "Señalarle la nota al pie", d: { rep: -3, ene: 1,
          msg: "Técnicamente lo advertiste. Técnicamente, pierdes al cliente." } },
        { t: "Ayudarle a renegociar los contratos", d: { red: 4, rep: 2, ene: -4,
          msg: "Tres semanas de reuniones con sus proveedores. No cobras, pero el cliente no se olvida." } },
      ] },
    { id: 18214, por: "Le llevaste tu índice a alguien del banco central", t: "Tu contacto quiere tus números",
      x: "El técnico del banco central te escribe por fin: quiere tu hoja de precios cada mes, en privado. No dice para qué.",
      o: [
        { t: "Mandársela: el dato público mejora", d: { red: 4, cri: 2, ene: -1,
          msg: "Cada mes, tu hoja viaja al banco central. Meses después, el dato oficial se parece más al tuyo." } },
        { t: "Pedir a cambio hablar con su equipo", d: { red: 2, mod: 3, car: 2, ene: -2,
          msg: "Te reciben una tarde. Aprendes más de la serie oficial que en toda la carrera." } },
        { t: "Dejar de mandarla", d: { ene: 1, red: -2,
          msg: "Si no te dicen para qué, no les das nada. El contacto deja de escribir." } },
      ] },
    { id: 18215, por: "Seguiste publicando tu índice tras la llamada", t: "La prensa extranjera cita tu índice",
      x: "Una agencia internacional usa tu índice para explicar la inflación del país. Ya no es tan fácil llamarte para que lo revises.",
      o: [
        { t: "Dar entrevistas y explicar el método", d: { rep: 5, red: 3, ene: -3,
          msg: "Explicas el método tres veces por semana. El índice ya no depende de ti, depende de que lo usen." } },
        { t: "Seguir con perfil bajo", d: { cri: 2, ene: 1,
          msg: "No das entrevistas. El índice habla por ti y no se cansa." } },
      ] },
    { id: 18216, por: "Seguiste publicando tu índice tras la llamada", t: "Se cierran las puertas oficiales",
      x: "Ninguna institución pública vuelve a invitarte. Dos clientes que dependen de contratos con el gobierno se van sin explicar.",
      o: [
        { t: "Buscar clientes que valoren lo independiente", d: { red: 3, ene: -3, cash: -1500,
          msg: "Te cuesta un trimestre flaco. Los que llegan pagan por lo mismo que te cerró las puertas." } },
        { t: "Pausar el índice un tiempo", d: { rep: -2, ene: 2,
          msg: "Lo pausas sin anunciarlo. Tus lectores lo notan antes que el ministerio." } },
      ] },

    /* ===== 18300 El ancla cambiaria no aguanta ===== */
    { id: 18310, por: "Avisaste a tus clientes de una devaluación", t: "Devaluaron y tus clientes estaban cubiertos",
      x: "El tipo de cambio saltó en una noche. Tus clientes cubiertos amanecieron tranquilos y ahora quieren saber qué viene.",
      o: [
        { t: "Armarles el escenario del después", d: { cri: 3, cash: 3000, ene: -3,
          msg: "Inflación, salarios y tasas para los próximos meses. Te leen como se lee un parte del tiempo antes de salir." } },
        { t: "Cobrar la próxima lectura como servicio", d: { cash: 5000, car: 2, red: -1,
          msg: "Pagan sin regatear. El que acierta una devaluación puede cobrar la siguiente pregunta." } },
        { t: "Pedirles que te recomienden", d: { red: 5, ene: -1,
          msg: "Cada cliente cubierto le cuenta a otros dos. En la plaza, tu nombre empieza a ir con la palabra «avisó»." } },
      ] },
    { id: 18311, por: "Anticipaste una devaluación que tardaba", t: "El ancla aguantó más de la cuenta",
      x: "Pasó un año y el tipo de cambio sigue fijo. Cubrirse costó dinero y los que no se cubrieron se ríen en las reuniones.",
      o: [
        { t: "Sostener la lectura con datos nuevos", d: { cri: 3, rep: -2, ene: -2,
          msg: "Actualizas reservas, deuda y brecha. El número sigue diciendo lo mismo, aunque nadie quiera oírlo.",
          luego: [{ en: 1, s: "cri", azar: [{ p: 55, id: 18315, bueno: true }, { p: 45, id: 18316, bueno: false }] }] } },
        { t: "Reconocer que el gobierno tenía más caja", d: { cri: 2, rep: 1,
          msg: "Encontraste un préstamo que no estaba en tus cuentas. Lo dices. Te creen más por eso." } },
        { t: "Cambiar de tesis y no volver al tema", d: { rep: -2, ene: 2,
          msg: "Dejas de hablar del tipo de cambio. Si se rompe, que lo anuncie otro." } },
      ] },
    { id: 18312, por: "Avisaste a tus clientes de una devaluación", t: "Un cliente te acusa de sembrar pánico",
      x: "Un cliente grande dice que tu aviso circuló, que sus acreedores se asustaron y que le subieron las tasas por tu culpa.",
      o: [
        { t: "Mostrarle que el aviso fue privado", d: { cri: 1, rep: 2, red: -1,
          msg: "Le enseñas la lista de destinatarios. El que lo filtró era de su propia empresa." } },
        { t: "Disculparte y bajar el tono", d: { red: 2, rep: -1, cri: -1,
          msg: "Le pides disculpas por algo que no hiciste. Se queda, y la próxima vez avisarás más bajito." } },
        { t: "Dejarlo ir", d: { cash: -2000, rep: 1, ene: 2,
          msg: "Pierdes la cuenta y ganas paz. Tu lectura no cambia de opinión por un cliente." } },
      ] },
    { id: 18313, por: "Viste venir la devaluación y no avisaste", t: "Devaluaron y nadie estaba cubierto",
      x: "El salto llegó de madrugada. Tus clientes con deuda en dólares ven crecer lo que deben y te llaman todos el mismo día.",
      o: [
        { t: "Ayudarles a reestructurar la deuda", d: { cri: 2, red: 3, cash: 2000, ene: -5,
          msg: "Semanas de hojas de cálculo con bancos al teléfono. Salvas a la mayoría, a medias." } },
        { t: "Explicar que nadie podía saberlo", d: { rep: -4, ene: 1,
          msg: "Lo dices con convicción. Un cliente saca tu informe de hace meses, donde las reservas ya caían." } },
        { t: "Admitir que lo viste y no lo dijiste", d: { cri: 3, rep: -2, red: -2,
          msg: "Duele y no lo arregla. Dos clientes se van; los que se quedan ya saben que dirás la verdad." } },
      ] },
    { id: 18314, por: "Te cubriste de la devaluación sin avisar a nadie", t: "Tus clientes saben que te cubriste",
      x: "Devaluaron. En una cena alguien comenta que tú estabas en dólares desde hacía meses. Tus clientes no lo estaban.",
      o: [
        { t: "Explicar que era tu ahorro personal", d: { rep: -3, red: -2,
          msg: "Es cierto, y no ayuda. Tu ahorro personal sabía algo que tu informe no decía." } },
        { t: "Ofrecerles asesoría gratis para salir", d: { rep: 2, ene: -4, cash: -1500,
          msg: "Trabajas gratis un trimestre. Lo que ganaste con los dólares se va en eso, más o menos." } },
        { t: "No dar explicaciones", d: { rep: -5, ene: 2,
          msg: "No dices nada. Tu silencio dice bastante." } },
      ] },
    { id: 18315, por: "Sostuviste tu tesis de devaluación un año más", t: "El ancla por fin se rompió",
      x: "La devaluación llegó mucho después de tu primer aviso. Los que se rieron ahora te llaman para entender qué viene.",
      o: [
        { t: "Atenderlos a todos, sin reproches", d: { red: 5, rep: 3, ene: -3, deja: "l8_razon_temprano",
          msg: "Contestas cada llamada con la lectura siguiente. Los que se reían ahora son clientes." } },
        { t: "Cobrar caro la consulta", d: { cash: 5000, red: -2, deja: "l8_razon_temprano",
          msg: "Tener razón antes que nadie tiene precio. Lo fijas tú y lo pagan." } },
      ] },
    { id: 18316, por: "Sostuviste tu tesis de devaluación un año más", t: "Te llaman alarmista profesional",
      x: "Otro año sin devaluación. En la plaza ya te apodan «Devaluación» y un cliente cancela su contrato.",
      o: [
        { t: "Revisar qué se te escapó", d: { cri: 4, mod: 2, ene: -2,
          msg: "Encuentras la fuente de dólares que el gobierno tenía escondida. La próxima vez la vas a buscar primero." } },
        { t: "Insistir, que ya falta poco", d: { rep: -3, cri: -1,
          msg: "Lo repites en cada reunión. Puede que tengas razón. Ya nadie lo va a comprobar contigo." } },
      ] },

    /* ===== 18400 Te dejan operar tu lectura del ciclo ===== */
    { id: 18410, empleado: true, por: "Operaste tu propia lectura del ciclo", t: "El ciclo giró como dijiste",
      x: "Tu tesis se cumplió y la posición ganó. El comité ya hace cuentas de lo que podrías hacer con más dinero.",
      o: [
        { t: "Pedir más capital para la siguiente", d: { car: 5, cash: 5000, ene: -4,
          msg: "Te dan el triple de cupo. Ahora cada lectura del ciclo pesa como una casa.",
          luego: [{ en: 1, s: "cri", azar: [{ p: 50, id: 18415, bueno: true }, { p: 50, id: 18416, bueno: false }] }] } },
        { t: "Cobrar el bono y volver a escribir", d: { cash: 5000, ene: 2,
          msg: "Cobras y vuelves a tus informes. Una victoria limpia vale más si no la arriesgas." } },
        { t: "Repartir el mérito con el equipo", d: { red: 4, rep: 2, cash: 2000,
          msg: "Nombras a cada uno en el comité. Ganas menos bono y más gente que te va a cuidar." } },
      ] },
    { id: 18411, empleado: true, por: "Operaste tu propia lectura del ciclo", t: "Tenías razón, pero tarde",
      x: "El mercado fue en contra unas semanas, riesgo cerró tu posición y después todo se movió como decías. Ganar tarde no paga.",
      o: [
        { t: "Pedir otra oportunidad con más margen", d: { cri: 2, car: 1, ene: -2,
          msg: "El director te da otro intento, más chico. Ahora sabes que el tiempo es parte de la tesis." } },
        { t: "Aceptar que el tiempo también cuenta", d: { cri: 4, ene: 1,
          msg: "Anotas en tu cuaderno: tener razón y tenerla a tiempo son dos cosas distintas." } },
        { t: "Quejarte de riesgo con el director", d: { rep: -2, red: -3, ene: -1,
          msg: "Riesgo hizo su trabajo. Ahora todos saben que tú no lo entiendes." } },
      ] },
    { id: 18412, empleado: true, por: "Operaste tu lectura del ciclo con una posición grande", t: "La posición se hundió",
      x: "El ciclo no giró. La posición perdió lo que el comité tolera y un poco más. Te citan el lunes a primera hora.",
      o: [
        { t: "Asumirlo y presentar qué falló", d: { cri: 4, rep: 1, car: -3,
          msg: "Llevas el error ordenado en tres láminas. Te quitan el cupo y te dejan el respeto." } },
        { t: "Defender que la tesis sigue viva", d: { cri: 1, rep: -3, car: -2,
          msg: "Puede que siga viva. El cupo, en cambio, ya no." } },
        { t: "Volver a los informes y no operar más", d: { ene: 2, car: -2,
          msg: "Vuelves al papel, donde las pérdidas no se cobran. Duermes, al menos." } },
      ] },
    { id: 18413, empleado: true, por: "Te ofrecieron operar tu propia lectura del ciclo", t: "Otro operó tu tesis",
      x: "Un gestor del fondo leyó tu informe, operó tu tesis con más tamaño que tú y ganó. Su bono tiene tu análisis adentro.",
      o: [
        { t: "Pedirle una parte del crédito", d: { rep: 1, car: 1, red: -2,
          msg: "Te lo reconoce en el comité, de pasada. Su bono no se entera." } },
        { t: "Proponer que paguen cada idea usada", d: { cash: 2500, car: 2, red: -1,
          msg: "El director acepta un esquema raro pero justo. Los gestores te miran con algo de recelo." } },
        { t: "Alegrarte: tu análisis funciona", d: { cri: 2, red: 3, ene: 1,
          msg: "Un gestor que gana con tus ideas es un gestor que te va a leer siempre." } },
      ] },
    { id: 18414, empleado: true, por: "No quisiste operar tu lectura del ciclo", t: "El director deja de leerte",
      x: "El director de inversiones ya no pide tus informes. Dice que prefiere lecturas de gente que se juega algo.",
      o: [
        { t: "Volver a pedir el cupo", d: { car: 2, ene: -2,
          msg: "Te lo da, con una sonrisa de quien sabía que volverías." } },
        { t: "Buscar lectores fuera del fondo", d: { red: 4, car: -1, ene: -2,
          msg: "Empiezas a mandar tu lectura a gente de otras firmas. Te leen con más ganas que en casa." } },
        { t: "Aceptarlo con calma", d: { ene: 3, car: -2,
          msg: "Escribes para el archivo. El archivo no discute ni se juega nada." } },
      ] },
    { id: 18415, empleado: true, por: "Pediste más capital para operar el ciclo", t: "Tu estrategia se vuelve producto",
      x: "Tu lectura del ciclo ganó dos veces seguidas. El fondo quiere ofrecerla a sus clientes como estrategia propia, con tu nombre.",
      o: [
        { t: "Aceptar y ponerle tu nombre", d: { car: 6, rep: 4, cash: 6000, ene: -4,
          msg: "Tu lectura ya tiene folleto. Lo que antes era una opinión, ahora es una promesa a clientes." } },
        { t: "Aceptar sin tu nombre en la portada", d: { car: 3, cash: 4000, ene: -2,
          msg: "La estrategia sale con el nombre del fondo. Si falla, no te persigue. Si gana, tampoco." } },
      ] },
    { id: 18416, empleado: true, por: "Pediste más capital para operar el ciclo", t: "La segunda apuesta salió mal",
      x: "Con el triple de cupo, el ciclo tardó en girar. La pérdida borra la ganancia anterior y deja un hueco.",
      o: [
        { t: "Cerrar y dar la cara al comité", d: { cri: 4, car: -3, rep: 1,
          msg: "Cierras antes de que te cierren. El comité valora el gesto más que el resultado." } },
        { t: "Aguantar, que el ciclo ya viene", d: { cri: -2, car: -5, cash: -3000,
          msg: "Aguantas un trimestre más. Riesgo no aguanta tanto como tú." } },
      ] },

    /* ===== 18500 El gobierno te pide firmar un plan ===== */
    { id: 18510, por: "Te llamaron a asesorar un plan contra la inflación", t: "El plan está funcionando",
      x: "La inflación cede mes tras mes y la prensa de afuera ya habla del plan como caso de estudio.",
      o: [
        { t: "Escribir por qué funcionó", d: { cri: 3, rep: 3, ene: -2,
          msg: "Separas lo que fue diseño de lo que fue suerte. La parte de suerte es más larga de lo que el ministro quisiera." } },
        { t: "Usarlo para conseguir clientes", d: { cash: 5000, red: 3, rep: -1,
          msg: "Cada reunión empieza hablando del plan. Los clientes llegan; algunos colegas te miran de reojo." } },
        { t: "Señalar lo que todavía puede salir mal", d: { cri: 4, red: -2,
          msg: "Mientras todos celebran, escribes sobre el déficit. Nadie te invita a la celebración." } },
      ] },
    { id: 18511, por: "Asesoraste un plan del gobierno contra la inflación", t: "El plan se cayó",
      x: "La inflación volvió con fuerza y el plan se desarma. La prensa publica la lista del consejo asesor y tu nombre está en ella.",
      o: [
        { t: "Dar la cara y explicar qué falló", d: { cri: 3, rep: -1, ene: -4,
          msg: "Vas a una entrevista y explicas en qué te equivocaste y en qué no te escucharon.",
          luego: [{ en: 1, s: "rep", azar: [{ p: 55, id: 18515, bueno: true }, { p: 45, id: 18516, bueno: false }] }] } },
        { t: "Guardar silencio hasta que pase", d: { rep: -4, ene: 1,
          msg: "No pasa. Tu nombre queda en cada artículo sobre el fracaso, sin tu versión al lado." } },
        { t: "Recordar que advertiste los riesgos", d: { rep: -2, red: -3,
          msg: "Sacas un correo donde lo advertías. El ministerio filtra otro donde lo aplaudías." } },
      ] },
    { id: 18512, por: "Asesoraste un plan del gobierno contra la inflación", t: "Tus clientes dudan de ti",
      x: "Un fondo extranjero cancela una reunión: no sabe si tu lectura es tuya o del ministerio. Otros dos preguntan lo mismo, con más tacto.",
      o: [
        { t: "Publicar tus conflictos de interés", d: { rep: 4, ene: -2,
          msg: "Pones en tu sitio con quién trabajas y en qué. Te creen más, aunque sabe raro escribirlo." } },
        { t: "Renunciar al consejo asesor", d: { rep: 3, red: -4,
          msg: "Dejas el consejo con una carta corta. Los clientes vuelven. El ministro no." } },
        { t: "Ignorarlo: los buenos clientes se quedan", d: { cash: -2000, ene: 1,
          msg: "Algunos se quedan. Los que se van eran los que pagaban mejor." } },
      ] },
    { id: 18513, por: "Asesoraste un plan del gobierno sin firmarlo", t: "Te escuchan y hacen lo contrario",
      x: "En el consejo te escuchan, toman nota y deciden otra cosa. Tu nombre sigue en la página del ministerio.",
      o: [
        { t: "Pedir que retiren tu nombre", d: { rep: 2, red: -3,
          msg: "Lo retiran a la semana, sin comentarios. Tu nombre deja de ser decorado." } },
        { t: "Seguir: algo de lo tuyo llega", d: { cri: 2, red: 3, ene: -3,
          msg: "De cada diez cosas que dices, una se aplica. Aprendes cómo se decide de verdad en un ministerio." } },
        { t: "Contar en tus informes lo que viste", d: { rep: 3, red: -5,
          msg: "Lo cuentas con cuidado, sin nombres. Igual saben de dónde salió." } },
      ] },
    { id: 18514, por: "Declinaste asesorar el plan contra la inflación", t: "Tu análisis molesta en el ministerio",
      x: "Tu informe señala tres agujeros del plan. El ministro responde en televisión sin nombrarte, pero todos saben a quién.",
      o: [
        { t: "Contestar con datos, en tu informe", d: { cri: 3, rep: 4, red: -2,
          msg: "Respondes con tablas, no con adjetivos. El debate sube de nivel y tu nombre con él." } },
        { t: "No contestar y esperar los datos", d: { cri: 2, ene: 1,
          msg: "Los datos tardan, pero llegan. Tú no tienes que decir nada; ellos hablan." } },
        { t: "Ir a televisión a responder", d: { rep: 2, red: 3, ene: -4,
          msg: "Te invitan esa misma noche. Ganas audiencia y pierdes el poco acceso que te quedaba al ministerio." } },
      ] },
    { id: 18515, por: "Diste la cara cuando el plan se cayó", t: "La plaza respeta que dieras la cara",
      x: "Eres de los pocos del consejo que explicó en público qué falló. Te buscan para hablar del siguiente intento.",
      o: [
        { t: "Ayudar, esta vez con condiciones", d: { cri: 3, rep: 4, red: 3, ene: -3,
          msg: "Pides metas públicas y un plazo para revisarlas. Te las dan. Por primera vez, firmas sin miedo, con tu propio texto." } },
        { t: "Declinar: ya pagaste una vez", d: { ene: 3, rep: 2,
          msg: "Dices que no con respeto. Tu nombre queda asociado a la honestidad y no al fracaso." } },
      ] },
    { id: 18516, por: "Diste la cara cuando el plan se cayó", t: "Un cliente grande se va por el ruido",
      x: "Tu entrevista fue buena, pero tu nombre sigue en los titulares. Tu cliente más grande decide tomar distancia.",
      o: [
        { t: "Aceptarlo y reconstruir la cartera", d: { cash: -3000, red: 3, ene: -3,
          msg: "Un año de cafés y reuniones. Los clientes nuevos te conocen por la entrevista, no por el plan." } },
        { t: "Ir a hablar con el cliente en persona", d: { red: 2, rep: 1, ene: -2,
          msg: "Te escucha una hora. Se va igual, pero promete volver cuando pase el ruido." } },
      ] },

    /* ===== 18600 Tu mayor cliente quiere otro número ===== */
    { id: 18610, por: "Sostuviste tu número frente a tu mayor cliente", t: "El banco se fue y llegaron otros",
      x: "El banco no renovó. Pero la historia circuló, y tres fondos te escriben porque quieren un número que nadie pueda comprar.",
      o: [
        { t: "Subir tus tarifas con los nuevos", d: { cash: 6000, rep: 2, red: -1,
          msg: "Pagan más por lo mismo de siempre: que el número sea tuyo." } },
        { t: "Repartir: ningún cliente tan grande otra vez", d: { cri: 4, cash: 3000, ene: -2,
          msg: "Pones un tope a lo que puede pesar un cliente. Lo aprendiste por las malas." } },
        { t: "Contar la historia en un foro", d: { rep: 4, red: 3, ene: -2,
          msg: "La cuentas sin nombres. Todos adivinan el banco. Te invitan a tres foros más." } },
      ] },
    { id: 18611, por: "Sostuviste tu número frente a tu mayor cliente", t: "El banco se fue y no llegó nadie",
      x: "El banco no renovó y nadie más tocó la puerta. Tus ingresos bajan a la mitad y el siguiente informe trimestral se acerca.",
      o: [
        { t: "Bajar costos y aguantar", d: { cash: -4000, cri: 2, ene: -3,
          msg: "Cancelas suscripciones y oficinas. Aguantas, con menos y con el número intacto.",
          luego: [{ en: 1, azar: [{ p: 55, id: 18615, bueno: true }, { p: 45, id: 18612 }] }] } },
        { t: "Buscar trabajo dentro de un banco", d: { car: -3, cash: 3000, ene: 2,
          msg: "Te contratan rápido. Te piden que tu lectura sea la de la casa, cosa que ya conoces." } },
        { t: "Volver a llamar al banco", d: { rep: -4, cash: 2000,
          msg: "Te reciben. El siguiente informe sale con una recesión que más bien parece una pausa." } },
      ] },
    { id: 18612, por: "Te pidieron cambiar tu pronóstico de recesión", t: "Tu escenario se cumplió",
      x: "La economía se frenó como decía tu primer borrador. Los bonos del banco cayeron y sus compradores buscan a quién culpar.",
      o: [
        { t: "Publicar el borrador original con fecha", d: { rep: 4, red: -4,
          msg: "Lo pones en tu sitio. Todo el mercado entiende lo que pasó, incluido el banco." } },
        { t: "Callar y atender a tus clientes", d: { cri: 3, cash: 2000, ene: -2,
          msg: "Te dedicas a lo que viene. Lo que pasó, ya lo saben los que tienen que saberlo." } },
        { t: "Ofrecerle al banco ayuda con el daño", d: { red: 4, cash: 3000, rep: -1,
          msg: "El banco acepta, sin mencionar nada. Cobras por arreglar lo que avisaste." } },
      ] },
    { id: 18613, por: "Cambiaste tu pronóstico a pedido de un cliente", t: "Un periodista compara tus versiones",
      x: "Un periodista consiguió tu borrador y el informe final. Publica las dos páginas lado a lado, con el logo del banco al centro.",
      o: [
        { t: "Reconocerlo y explicar la presión", d: { rep: -3, cri: 3, red: -3,
          msg: "Lo dices todo. El banco te demanda y algunos colegas, en voz baja, te dan la razón." } },
        { t: "Decir que el borrador era un borrador", d: { rep: -5, ene: 1,
          msg: "Es cierto y no convence. Los borradores no suelen tener la palabra recesión en el título." } },
        { t: "No responder", d: { rep: -4, ene: -2,
          msg: "La nota circula una semana. Tu nombre, bastante más." } },
      ] },
    { id: 18614, por: "Ajustaste tu informe al gusto de tu mayor cliente", t: "El banco vuelve con otro pedido",
      x: "Quedaron contentos. Ahora quieren que presentes el escenario a sus inversores, con su logo al lado del tuyo.",
      o: [
        { t: "Aceptar y presentar", d: { cash: 4000, rep: -2, ene: -2,
          msg: "Presentas con su logo detrás. Los inversores te miran como se mira a un vendedor.",
          luego: [{ en: 1, azar: [{ p: 50, id: 18616, bueno: false }, { p: 50, id: 18612 }] }] } },
        { t: "Aceptar, pero con tu número original", d: { rep: 3, cri: 2, red: -3,
          msg: "Llegas con la recesión de vuelta en la lámina. Al banco no le gusta. A los inversores, sí." } },
        { t: "Declinar: un favor ya fue bastante", d: { rep: 1, cash: -2000,
          msg: "Dices que no. El banco renueva igual, pero por menos." } },
      ] },
    { id: 18615, por: "Aguantaste con menos y sin cambiar tu número", t: "Un fondo de afuera te descubre",
      x: "Un fondo extranjero lleva un año leyendo tus informes en silencio. Quiere contratarte como su lectura del país.",
      o: [
        { t: "Aceptar con exclusividad", d: { cash: 8000, car: 4, red: -2,
          msg: "Un solo cliente otra vez, pero esta vez quiere tu número tal cual. Lo pone por escrito." } },
        { t: "Aceptar, sin exclusividad", d: { cash: 5000, red: 3, rep: 2,
          msg: "Pagan menos, pero tu nombre sigue libre. Sabes cuánto vale eso." } },
      ] },
    { id: 18616, por: "Presentaste tu pronóstico con el logo de un banco", t: "Los inversores te reclaman",
      x: "La economía se frenó más de lo que dijiste en esa presentación. Dos inversores del banco te escriben pidiendo explicaciones.",
      o: [
        { t: "Mostrarles tu número original", d: { rep: 1, red: -4, cri: 2,
          msg: "Les enseñas lo que pensabas de verdad. Te creen a ti y dejan de creerle al banco." } },
        { t: "Remitirlos al banco", d: { rep: -3, ene: 1,
          msg: "Respondes con el teléfono del banco. Ellos responden borrándote de su lista." } },
      ] },
  ],

  opciones: [
    { escena: 23, t: "Calcular primero dónde debería asentarse la moneda",
      d: { cri: 5, mod: 2, ene: -4, msg: "Antes de tocar un modelo estimas el tipo de cambio de equilibrio. Llegas tarde a todo, pero con el número que piden." } },
    { escena: 54, t: "Medir la brecha con el dólar de la calle primero",
      d: { cri: 4, cash: 1500, ene: -3, msg: "Comparas la tasa oficial con la de la calle y mueves la mitad al mejor precio. Pierdes la mañana; ganas el margen." } },
    { escena: 30, t: "Leer si es recesión o pánico antes de comprar",
      d: { cri: 4, cash: 1000, ene: -3, msg: "Revisas empleo, crédito y tasas. Es pánico, no recesión: compras tarde y más caro que los valientes." } },
    { escena: 19, t: "Dar tu pronóstico del ciclo con número y fecha",
      d: { rep: 5, red: 3, car: -2, ene: -2, msg: "Lo dices al aire con número y fecha. Te citan en todas partes. Si fallas, también te van a citar." } },
  ],

  finales: [
    { id: "l8_tu_numero", huellas: ["l8_contra_consenso", "l8_sostuviste_numero"], t: "Tu número, con tu nombre",
      x: "Publicaste lejos del consenso desde el primer informe y no moviste tu pronóstico cuando lo pidió el cliente que más pagaba. Fallaste a veces, pero siempre con tu número." },
    { id: "l8_consenso", huellas: ["l8_con_consenso", "l8_cambiaste_numero"], t: "Cerca del consenso, lejos del riesgo",
      x: "Acercaste tu primer pronóstico al de todos y, años después, cambiaste otro para no perder un cliente. Nunca fallaste sin compañía. Tampoco acertaste sin ella." },
  ],
};
