/* El Analista: escenas propias de la carrera de Ingeniería (lote 10).
   Ids 20000-20999. Cada raíz usa su centena: raíz 20N00 -> consecuencias 20N10 a 20N14
   (segundo nivel) y 20N20 a 20N21 (tercer nivel, hojas).
   Tramos de cargo: planta 0-2, parque solar 0-3, constructora del compañero 1-5,
   autopista 2-4, refinería 2-5, carretera de peaje 3-6, central hidroeléctrica 4-6. */
module.exports = {
  carrera: "ing",

  huellas: {
    l10_sala_maquinas: "Te metiste en la sala de máquinas en una visita a planta",
    l10_rehiciste_produccion: "Rehiciste el cálculo de producción de un parque solar",
    l10_frenaste_desembolso: "Frenaste un desembolso hasta ver la obra con tus ojos",
    l10_inventario_obra: "Contaste tú las máquinas de una obra en quiebra",
    l10_tesis_refineria: "Leíste la parada de una refinería antes que el mercado",
    l10_llamaste_planta: "Llamaste a alguien de dentro de una refinería",
    l10_oferta_tecnica: "Bajaste una oferta con el costo real del pavimento",
    l10_constructora: "Pusiste tus ahorros en una constructora pequeña",
    l10_exigiste_geologia: "Exigiste el estudio geológico completo de un túnel",
    l10_lideraste_central: "Lideraste el financiamiento de una central en la montaña",
  },

  /* ===================== RAÍCES PROPIAS ===================== */
  propias: [
    /* ---- 20000 La visita a la planta (0-2) ---- */
    { id: 20000, min: 0, max: 2, empleado: true, t: "La visita a la planta",
      x: "Acompañas al equipo a la planta que van a financiar. En el recorrido oyes un compresor que suena peor de lo que dice el informe técnico.",
      o: [
        { t: "Meterte en la sala de máquinas a preguntar", d: { cri: 4, red: 2, ene: -2, deja: "l10_sala_maquinas",
          msg: "El jefe de mantenimiento te habla media hora. La gerencia te mira desde la puerta, sin ninguna gracia.",
          luego: [{ en: 1, s: "cri", azar: [{ p: 25, id: 20010 }, { p: 30, id: 20011 }, { p: 25, id: 20012, bueno: false }, { p: 20, id: 20013, bueno: true }] }] } },
        { t: "Anotarlo y ponerlo en el informe con tacto", d: { cri: 2, rep: 2,
          msg: "Una línea discreta en la página nueve. Tu jefe la lee, levanta una ceja y la deja.",
          luego: [{ en: 1, azar: [{ p: 35, id: 20010 }, { p: 40, id: 20013 }, { p: 25, id: 20014 }] }] } },
        { t: "Quedarte con la presentación de la gerencia", d: { ene: 2, red: 1,
          msg: "Café, diapositivas y un almuerzo bueno. El compresor sigue sonando, pero ya no en tu cabeza.",
          luego: [{ en: 1, azar: [{ p: 55, id: 20010 }, { p: 45, id: 20014 }] }] } },
      ] },

    /* ---- 20100 El número técnico no cuadra (0-3) ---- */
    { id: 20100, min: 0, max: 3, empleado: true, t: "El número técnico no cuadra",
      x: "El modelo del parque solar supone una producción que el estudio de radiación no respalda. Lo sacas de cabeza y te da bastante menos.",
      o: [
        { t: "Rehacer el cálculo de producción y llevarlo al VP", d: { mod: 4, cri: 3, ene: -3, deja: "l10_rehiciste_produccion",
          msg: "Una noche con radiación, pérdidas y degradación de paneles. Tu número sale casi un décimo por debajo del modelo.",
          luego: [{ en: 2, azar: [{ p: 25, id: 20110 }, { p: 35, id: 20111 }, { p: 20, id: 20112 }, { p: 20, id: 20113 }] }] } },
        { t: "Meter un caso conservador en el modelo, sin avisar", d: { mod: 2, rep: -1,
          msg: "Bajas la producción en una pestaña escondida. Si alguien la encuentra, tendrás que explicarla.",
          luego: [{ en: 2, azar: [{ p: 30, id: 20114 }, { p: 30, id: 20111 }, { p: 40, id: 20113 }] }] } },
        { t: "Confiar en el ingeniero independiente: para eso cobra", d: { ene: 2, cri: -1,
          msg: "Su informe tiene sellos y firmas. El tuyo, una servilleta. Lo dejas así.",
          luego: [{ en: 2, azar: [{ p: 45, id: 20111 }, { p: 55, id: 20113 }] }] } },
      ] },

    /* ---- 20200 La obra va atrasada (2-4) ---- */
    { id: 20200, min: 2, max: 4, empleado: true, t: "La obra va atrasada",
      x: "El constructor de la autopista pide el siguiente desembolso. El informe dice que va casi al día; las fotos de la obra dicen otra cosa.",
      o: [
        { t: "Frenar el desembolso hasta ir a la obra", d: { cri: 4, red: -3, ene: -2, deja: "l10_frenaste_desembolso",
          msg: "Un día entero en botas recorriendo tramos. El atraso real es el doble del que dice el informe.",
          luego: [{ en: 1, s: "cri", azar: [{ p: 35, id: 20210 }, { p: 30, id: 20211, bueno: true }, { p: 35, id: 20212 }] }] } },
        { t: "Desembolsar con un hito: si no se cumple, se corta", d: { cri: 2, rep: 2,
          msg: "El constructor firma la condición sin leerla mucho. Tú la lees tres veces.",
          luego: [{ en: 1, azar: [{ p: 15, id: 20210 }, { p: 35, id: 20211 }, { p: 30, id: 20212 }, { p: 20, id: 20213 }] }] } },
        { t: "Desembolsar: el cronograma tiene holgura", d: { red: 3, ene: 1,
          msg: "El constructor te da las gracias por teléfono. Suena aliviado, demasiado aliviado.",
          luego: [{ en: 2, azar: [{ p: 30, id: 20211 }, { p: 35, id: 20212 }, { p: 35, id: 20213 }] }] } },
      ] },

    /* ---- 20300 La parada de la refinería (2-5) ---- */
    { id: 20300, min: 2, max: 5, empleado: true, t: "La parada de la refinería",
      x: "Una refinería grande anuncia un mes de parada por mantenimiento. Por cómo es esa unidad por dentro, sabes que un mes no alcanza.",
      o: [
        { t: "Armar la tesis y llevarla a la mesa", d: { mod: 3, car: 3, ene: -3, deja: "l10_tesis_refineria",
          msg: "Calculas horas de trabajo, repuestos y precedentes. La mesa toma una posición pequeña sobre el margen de refinación.",
          luego: [{ en: 1, s: "cri", azar: [{ p: 40, id: 20310, bueno: true }, { p: 35, id: 20311, bueno: false }, { p: 25, id: 20313 }] }] } },
        { t: "Llamar a un excompañero que trabaja en esa planta", d: { red: 2, cri: -2, deja: "l10_llamaste_planta",
          msg: "Te cuenta más de lo que debería: faltan piezas que no llegan. Cuelgas sabiendo demasiado.",
          luego: [{ en: 1, azar: [{ p: 45, id: 20312 }, { p: 35, id: 20310 }, { p: 20, id: 20311 }] }] } },
        { t: "Dejarlo pasar: no es tu sector en la mesa", d: { ene: 2,
          msg: "Lo comentas en el almuerzo y nadie le presta atención. Tú tampoco, después del postre.",
          luego: [{ en: 1, azar: [{ p: 50, id: 20310 }, { p: 50, id: 20311 }] }] } },
      ] },

    /* ---- 20400 La carretera que conoces (3-6) ---- */
    { id: 20400, min: 3, max: 6, t: "Una carretera con grietas",
      x: "Tu equipo puja por una carretera de peaje. El vendedor jura que el pavimento aguanta diez años; por las grietas que viste, aguanta cuatro.",
      o: [
        { t: "Bajar la oferta con el costo de repavimentar", d: { cri: 4, mod: 2, deja: "l10_oferta_tecnica",
          msg: "Metes la rehabilitación en el año cuatro. Tu oferta queda bastante por debajo de lo que esperaba el vendedor.",
          luego: [{ en: 1, azar: [{ p: 25, id: 20410 }, { p: 35, id: 20411 }, { p: 20, id: 20413 }, { p: 20, id: 20414 }] }] } },
        { t: "Ofertar fuerte: el plan es repavimentar y subir tarifa", d: { car: 3, rep: 2, ene: -2,
          msg: "Ofertas al tope. Tu tesis: repavimentar pronto y negociar la tarifa con el concedente.",
          luego: [{ en: 1, s: "cri", azar: [{ p: 40, id: 20410, bueno: true }, { p: 35, id: 20412, bueno: false }, { p: 25, id: 20413 }] }] } },
        { t: "Retirarte de la puja", d: { ene: 2, car: -1,
          msg: "Te bajas a tiempo. El comité no entiende por qué dejas ir un activo que tú mismo trajiste.",
          luego: [{ en: 1, azar: [{ p: 65, id: 20411 }, { p: 35, id: 20414 }] }] } },
      ] },

    /* ---- 20500 La constructora de tu compañero (1-5) ---- */
    { id: 20500, min: 1, max: 5, t: "La constructora de tu compañero",
      x: "Un compañero de la facultad tiene una constructora pequeña y va a una licitación municipal. Te pide que le armes la oferta y entres en la sociedad.",
      o: [
        { t: "Entrar en la sociedad con tus ahorros", d: { cash: -6000, ene: -3, deja: "l10_constructora",
          msg: "Pones tus ahorros y tus fines de semana. Él pone la maquinaria y la paciencia con el municipio.",
          luego: [{ en: 1, s: "cri", azar: [{ p: 30, id: 20510, bueno: true }, { p: 30, id: 20511 }, { p: 25, id: 20512, bueno: false }, { p: 15, id: 20513 }] }] } },
        { t: "Armarle la oferta sin poner dinero", d: { mod: 3, red: 3, ene: -3, cash: 1000,
          msg: "Le haces el cómputo de cantidades y el flujo de caja. Te paga con una cena y una parte pequeña si gana.",
          luego: [{ en: 1, azar: [{ p: 40, id: 20510 }, { p: 30, id: 20511 }, { p: 30, id: 20514 }] }] } },
        { t: "Decirle que no, con cariño", d: { ene: 2, red: -2,
          msg: "Le explicas que no te da el tiempo. Lo entiende, o eso dice.",
          luego: [{ en: 2, azar: [{ p: 35, id: 20510 }, { p: 65, id: 20514 }] }] } },
      ] },

    /* ---- 20600 La central en la montaña (4-6) ---- */
    { id: 20600, min: 4, max: 6, t: "Una central en la montaña",
      x: "Te ofrecen liderar el financiamiento de una central hidroeléctrica. El estudio geológico cubre solo la mitad del túnel y el gobierno quiere firmar ya.",
      o: [
        { t: "Exigir el estudio completo antes de comprometerte", d: { cri: 5, red: -3, car: -2, deja: "l10_exigiste_geologia",
          msg: "Pides seis meses de perforaciones. El ministerio pone mala cara y otros bancos huelen la oportunidad.",
          luego: [{ en: 2, azar: [{ p: 20, id: 20610 }, { p: 35, id: 20612 }, { p: 45, id: 20613 }] }] } },
        { t: "Liderarlo con una reserva grande para imprevistos", d: { car: 5, rep: 3, ene: -4, deja: "l10_lideraste_central",
          msg: "Firmas con una reserva para imprevistos que el sponsor odia. Tu nombre va primero en la portada.",
          luego: [{ en: 2, s: "cri", azar: [{ p: 35, id: 20610, bueno: false }, { p: 25, id: 20611 }, { p: 40, id: 20612, bueno: true }] }] } },
        { t: "Pasar: demasiada montaña y demasiada política", d: { ene: 3, cri: 2,
          msg: "Declinas con una carta educada. Otro banco toma el mandato antes de que se seque la tinta.",
          luego: [{ en: 2, azar: [{ p: 55, id: 20613 }, { p: 45, id: 20614 }] }] } },
      ] },
  ],

  /* ===================== CONSECUENCIAS ===================== */
  escenas: [
    /* ===== 20000 La visita a la planta ===== */
    { id: 20010, por: "Oíste un compresor dudoso en una visita a planta", t: "El compresor se paró", empleado: true,
      x: "Seis meses después, el compresor que oíste se paró. La planta va a media marcha y el banco pregunta quién vio qué en la visita.",
      o: [
        { t: "Contar lo que viste, con fecha y detalle", d: { rep: 3, cri: 3, red: -2,
          msg: "Lo cuentas tal cual. Alguien del equipo queda mal parado y no te lo perdona tan rápido.",
          luego: [{ en: 1, azar: [{ p: 50, id: 20020 }, { p: 50, id: 20021 }] }] } },
        { t: "Ofrecerte a volver a la planta con el técnico", d: { cri: 4, car: 2, ene: -4,
          msg: "Dos días entre grasa y planos. Vuelves con un plan de reparación que el banco acepta casi sin tocar." } },
        { t: "No decir nada: no era tu papel", d: { ene: 2, cri: -3,
          msg: "El comité culpa al ingeniero independiente. Tú duermes bien y aprendes algo de ti que no te gusta." } },
      ] },
    { id: 20011, por: "Hablaste con mantenimiento en una visita a planta", t: "El jefe de mantenimiento te escribe", empleado: true,
      x: "Te manda fotos y bitácoras que la gerencia no subió al data room. Te pide que no digas de dónde salieron.",
      o: [
        { t: "Pasárselo a tu jefe sin revelar la fuente", d: { cri: 3, rep: 2,
          msg: "Tu jefe usa las bitácoras para exigir una reserva de mantenimiento. Nadie pregunta de dónde salieron. Todavía." } },
        { t: "Pedirle que lo mande por los canales formales", d: { rep: 3, red: -2,
          msg: "No vuelve a escribir. Las bitácoras nunca llegan al data room y tú duermes en paz con media verdad." } },
        { t: "Archivar el correo sin abrir los adjuntos", d: { ene: 1, cri: -2,
          msg: "Lo que no sabes no te compromete, dicen. Lo que no sabes tampoco te ayuda, pero eso no lo dicen." } },
      ] },
    { id: 20012, por: "Hiciste preguntas incómodas en una visita a planta", t: "El cliente se quejó de tu visita", empleado: true,
      x: "El director de la planta llamó a tu jefe: dice que alguien del banco anduvo interrogando a su gente. Tu jefe te pide explicaciones.",
      o: [
        { t: "Explicar lo del compresor con calma", d: { cri: 2, rep: 2,
          msg: "Tu jefe escucha, asiente y te pide que la próxima vez se lo digas a él antes que a mantenimiento." } },
        { t: "Pedir disculpas y prometer que no se repite", d: { rep: -2, red: 2, ene: 1,
          msg: "El cliente queda contento. Tú te quedas con la duda y con un compresor sonando en la memoria." } },
      ] },
    { id: 20013, por: "Señalaste un equipo dudoso en una visita a planta", t: "Tu nota terminó en el contrato", empleado: true,
      x: "El banco exigió una reserva para reponer el compresor antes del desembolso. El cliente refunfuñó y firmó.",
      o: [
        { t: "Dejar que tu jefe se lleve el crédito", d: { red: 3, car: 1,
          msg: "Tu jefe lo cuenta en comité como idea suya. Luego te invita un café y te pone en el proyecto siguiente." } },
        { t: "Decir en comité que la observación fue tuya", d: { rep: 3, car: 2, red: -2,
          msg: "Lo dices sin adornos. El comité toma nota; tu jefe también, de otra forma." } },
      ] },
    { id: 20014, por: "Oíste un compresor dudoso en una visita a planta", t: "El compresor aguantó",
      x: "Pasaron dos años y el compresor sigue andando. La planta paga a tiempo y el ruido que oíste resultó ser solo eso, ruido.",
      o: [
        { t: "Preguntarle al técnico por qué aguantó", d: { cri: 3, red: 2, ene: -1,
          msg: "Le cambiaron los rodamientos al mes siguiente. Era ruido de repuesto viejo, no de falla. Lo anotas." } },
        { t: "Olvidarlo y seguir", d: { ene: 2,
          msg: "Una preocupación menos. No todo lo que suena raro se rompe." } },
      ] },
    { id: 20020, por: "Contaste lo que viste en la planta", t: "Ahora todas las visitas son tuyas", empleado: true,
      x: "Tu jefe decide que a partir de ahora vas a todas las visitas técnicas. Muchas horas de carretera y mucha atención del comité.",
      o: [
        { t: "Aceptarlas todas y hacerte la fama", d: { cri: 4, car: 3, ene: -5,
          msg: "Conoces medio país desde el asiento de una camioneta. En comité, cuando hablas de una planta, se callan." } },
        { t: "Pedir que roten entre el equipo", d: { red: 3, car: -1, ene: 2,
          msg: "Repartes la carga y enseñas a otros a mirar. Pierdes algo de brillo propio y ganas aliados." } },
      ] },
    { id: 20021, por: "Contaste lo que viste en la planta", t: "El equipo te hace el vacío", empleado: true,
      x: "Quien hizo la visita contigo quedó mal frente al comité. Ahora no te copia en los correos y almuerza con todos menos contigo.",
      o: [
        { t: "Buscar la conversación de frente", d: { red: 3, ene: -2,
          msg: "Una conversación incómoda en la escalera. No quedan amigos, pero vuelven los correos." } },
        { t: "Dejar que el tiempo lo arregle", d: { red: -3, ene: 1,
          msg: "El tiempo arregla poco. Pasas un trimestre enterándote de las cosas por caminos laterales." } },
      ] },

    /* ===== 20100 El número técnico no cuadra ===== */
    { id: 20110, por: "Corregiste el cálculo de un parque solar", t: "El ingeniero independiente se ofende", empleado: true,
      x: "El ingeniero independiente se enteró de que alguien del equipo junior le corrigió el cálculo. Llamó al VP para quejarse de tu tono.",
      o: [
        { t: "Pedirle una llamada y comparar supuestos", d: { cri: 3, red: 3, ene: -2,
          msg: "Él usó un año de radiación excepcional. Lo corrige sin admitirlo. Aceptas el empate." } },
        { t: "Sostener tu número y que lo resuelva el VP", d: { rep: 2, red: -3,
          msg: "El VP lo resuelve a tu favor, pero el ingeniero te tiene en la mira para siempre." } },
      ] },
    { id: 20111, por: "Dudaste de la producción de un parque solar", t: "El parque produce lo que temías", empleado: true,
      x: "Primer año: el parque produce bastante menos de lo previsto. La cobertura de la deuda queda justa y los bancos piden explicaciones.",
      o: [
        { t: "Proponer usar la reserva y estirar el calendario", d: { cri: 4, car: 2, ene: -3,
          msg: "Te toca la llamada con los bancos. Llevas el cálculo de producción corregido y un plan de pagos nuevo.",
          luego: [{ en: 1, s: "mod", azar: [{ p: 55, id: 20120, bueno: true }, { p: 45, id: 20121, bueno: false }] }] } },
        { t: "Dejar que lo manejen los senior", d: { ene: 2, car: -1,
          msg: "Lo ves desde lejos. Aprendes cómo se renegocia una deuda, pero no sales en ninguna foto." } },
      ] },
    { id: 20112, por: "Corregiste el cálculo de un parque solar", t: "El sponsor quiere sacarte del equipo", empleado: true,
      x: "El dueño del proyecto vio tu cálculo de producción y dice que asusta a los bancos. Le pide al VP que te saquen del deal.",
      o: [
        { t: "Pedirle al VP que defienda tu número", d: { rep: 3, red: -2, ene: -2,
          msg: "El VP te defiende a medias: sigues en el equipo, pero ya no vas a las reuniones con el sponsor." } },
        { t: "Ofrecer un rango en vez de un solo número", d: { cri: 3, mod: 2, red: 2,
          msg: "Un caso base y uno prudente. El sponsor respira y los bancos eligen el prudente. Todos contentos, menos el sponsor." } },
      ] },
    { id: 20113, por: "Dudaste de la producción de un parque solar", t: "El parque produce de más", empleado: true,
      x: "Año de sol excepcional: el parque supera el caso base. Nadie recuerda las dudas, salvo quien las tuvo.",
      o: [
        { t: "Revisar si fue suerte o si tu cálculo falló", d: { mod: 3, cri: 3, ene: -1,
          msg: "Dos tercios fueron suerte. El otro tercio, un supuesto de pérdidas que tenías mal. Lo corriges." } },
        { t: "Celebrar con el equipo y olvidarlo", d: { red: 3, ene: 2,
          msg: "Brindis en la terraza. Del cálculo nadie habla, que es la mejor forma de que no te lo recuerden." } },
      ] },
    { id: 20114, por: "Escondiste un caso conservador en un modelo", t: "Encontraron tu pestaña escondida", empleado: true,
      x: "Revisando el modelo, el VP da con tu caso conservador. Pregunta por qué está ahí y por qué nadie lo sabía.",
      o: [
        { t: "Explicarlo con el cálculo en la mano", d: { mod: 2, cri: 2, rep: -1,
          msg: "El VP te da la razón en el número y te la quita en la forma. Las dos cosas quedan anotadas." } },
        { t: "Decir que era una prueba y borrarla", d: { rep: -3, ene: 1,
          msg: "Borras la pestaña. El VP no te cree del todo y empieza a revisar tus archivos con lupa." } },
      ] },
    { id: 20120, por: "Propusiste un plan para el parque que producía poco", t: "Los bancos firman el ajuste", empleado: true,
      x: "Los bancos aceptan usar la reserva y estirar dos cuotas. El sponsor te manda un mensaje corto: gracias.",
      o: [
        { t: "Pedir que el ajuste lleve un informe trimestral", d: { cri: 3, rep: 2, ene: -2,
          msg: "Te toca escribirlo. Aburrido, útil y con tu nombre en cada página." } },
        { t: "Cerrar el tema y pasar al siguiente proyecto", d: { car: 2, ene: 1,
          msg: "Lo das por resuelto. Tu jefe también, y te lo nota en la evaluación." } },
      ] },
    { id: 20121, por: "Propusiste un plan para el parque que producía poco", t: "Un banco se planta", empleado: true,
      x: "Uno de los bancos rechaza el ajuste y exige que el sponsor ponga más capital. El sponsor dice que la idea fue tuya.",
      o: [
        { t: "Sostener el plan y sumar a los otros bancos", d: { cri: 3, red: 2, ene: -4,
          msg: "Dos bancos de tres te apoyan. El tercero cede a cambio de una comisión. Sales con ojeras y el proyecto vivo." } },
        { t: "Retirarte y dejarlo a los socios", d: { rep: -2, ene: 2,
          msg: "Los socios lo resuelven sin ti. En la siguiente renegociación no te invitan." } },
      ] },

    /* ===== 20200 La obra va atrasada ===== */
    { id: 20210, por: "Le pusiste condiciones a una obra atrasada", t: "El constructor amenaza con parar", empleado: true,
      x: "Sin el desembolso, el constructor dice que no puede pagar la nómina y que el lunes para la obra. Ya llamó a tu jefe y al ministerio.",
      o: [
        { t: "Desembolsar solo lo que se midió en sitio", d: { cri: 4, car: 2, ene: -3,
          msg: "Pagas lo que tu gente midió con cinta y nivel. Se queja, pero la obra no se para." } },
        { t: "Sostener el freno completo", d: { rep: 2, red: -4,
          msg: "La obra se para nueve días. Luego vuelve, más ordenada y con mucho rencor." } },
        { t: "Ceder y desembolsar todo", d: { red: 2, cri: -3,
          msg: "La obra sigue y el atraso también. El informe del mes siguiente vuelve a decir que van casi al día." } },
      ] },
    { id: 20211, por: "Financiaste una autopista que iba atrasada", t: "La obra recupera el ritmo", empleado: true,
      x: "El constructor metió un segundo turno y recuperó buena parte del atraso. En la reunión de seguimiento te mira como esperando algo.",
      o: [
        { t: "Reconocerlo delante de todos", d: { red: 4, rep: 1,
          msg: "Le das el crédito en voz alta. La relación mejora y los informes empiezan a llegar más honestos." } },
        { t: "Pedirle que lo sostenga tres meses más", d: { cri: 2, red: -1,
          msg: "Ni una sonrisa. Tienes razón y lo sabes, pero el constructor también sabe contar." } },
      ] },
    { id: 20212, por: "Financiaste una autopista que iba atrasada", t: "Sobrecosto: alguien tiene que ponerlo", empleado: true,
      x: "El atraso trajo sobrecosto y la obra necesita más dinero del previsto. El sponsor dice que lo cubre el banco; el banco, que el sponsor.",
      o: [
        { t: "Armar una solución repartida entre los dos", d: { cri: 3, mod: 3, car: 2, ene: -4,
          msg: "Un tramo de deuda nueva contra más capital del sponsor. Nadie queda contento, que es como se sabe que es justo.",
          luego: [{ en: 2, s: "mod", azar: [{ p: 60, id: 20220, bueno: true }, { p: 40, id: 20221, bueno: false }] }] } },
        { t: "Exigir que lo ponga todo el sponsor", d: { rep: 2, red: -3,
          msg: "El sponsor pone su parte a regañadientes y saca de tu banco otro proyecto que tenía con ustedes." } },
      ] },
    { id: 20213, por: "Financiaste una autopista que iba atrasada", t: "El constructor quiebra a mitad de obra", empleado: true,
      x: "El constructor entró en concurso. Hay maquinaria parada en la vía, obreros sin cobrar y un tramo a medio asfaltar.",
      o: [
        { t: "Ir a la obra y armar el inventario", d: { cri: 4, rep: 3, ene: -5, deja: "l10_inventario_obra",
          msg: "Una semana contando máquinas, metros y deudas. Tu inventario es el que usan todos para negociar." } },
        { t: "Llamar a otro constructor del gremio", d: { red: 3, car: 2, cri: -1,
          msg: "Uno que conoces toma la obra con sobreprecio. Caro, pero la vía se mueve en un mes." } },
        { t: "Dejarlo en manos de los abogados", d: { ene: 1, car: -2,
          msg: "Los abogados tardan un año. La maquinaria se oxida mientras tanto, y tu nombre en el proyecto también." } },
      ] },
    { id: 20220, por: "Repartiste el sobrecosto de una autopista", t: "La autopista abre con atraso", empleado: true,
      x: "Abre meses tarde, pero el tráfico de los primeros meses supera lo previsto. El tramo nuevo de deuda se paga antes de tiempo.",
      o: [
        { t: "Usar el caso para pedir el próximo proyecto grande", d: { car: 4, red: 2, ene: -2,
          msg: "Lo cuentas en comité con datos. Te dan el siguiente, más grande y más difícil." } },
        { t: "Quedarte con la lección y seguir", d: { cri: 3, ene: 2,
          msg: "Lo anotas: un atraso bien repartido no mata un proyecto. Siguiente." } },
      ] },
    { id: 20221, por: "Repartiste el sobrecosto de una autopista", t: "El sponsor no pone su parte", empleado: true,
      x: "Llegó la fecha y el sponsor no aportó su capital. El tramo nuevo de deuda queda colgando y tu comité quiere un culpable.",
      o: [
        { t: "Ejecutar las garantías del sponsor", d: { rep: 3, red: -4, ene: -3,
          msg: "El banco se queda con las acciones del sponsor, y con media autopista. Tú, con un enemigo de por vida." } },
        { t: "Darle tres meses más", d: { red: 2, cri: -2, car: -2,
          msg: "Pide otros tres. Y otros tres. Tu comité deja de preguntar por la autopista y empieza a preguntar por ti." } },
      ] },

    /* ===== 20300 La parada de la refinería ===== */
    { id: 20310, por: "Viste venir que una refinería tardaría más", t: "La parada se alarga", empleado: true,
      x: "La refinería anuncia que la parada se alarga dos meses. El margen de refinación se dispara y en la mesa no se habla de otra cosa.",
      o: [
        { t: "Escribir una nota sobre cómo leer las paradas", d: { cri: 3, rep: 3, ene: -2,
          msg: "Una nota corta: cómo se lee una parada desde la ingeniería. La mesa la circula y ahora te consultan cada anuncio." } },
        { t: "Callarte y seguir con lo tuyo", d: { ene: 1, car: -1,
          msg: "Lo dejas pasar. La próxima vez que una refinería anuncie algo, nadie va a pensar en preguntarte." } },
      ] },
    { id: 20311, por: "Viste venir que una refinería tardaría más", t: "La refinería arrancó a tiempo", empleado: true,
      x: "Contra tu pronóstico, la refinería arrancó en la fecha. Trajeron las piezas en avión, a un costo que tu cálculo no contemplaba.",
      o: [
        { t: "Revisar qué se te escapó", d: { cri: 4, mod: 2, ene: -1,
          msg: "Con márgenes altos, pagar el avión sale barato. La física no era el problema; el precio sí." } },
        { t: "Defender que la tesis era buena y fue mala suerte", d: { rep: -2, ene: 1,
          msg: "Nadie te discute. Tampoco nadie te vuelve a pedir una tesis de refinación." } },
      ] },
    { id: 20312, por: "Llamaste a alguien de dentro de una refinería", t: "Cumplimiento quiere saber", empleado: true,
      x: "Alguien de la mesa mencionó tu llamada a la planta. Cumplimiento te cita para preguntar qué te dijeron y con quién lo compartiste.",
      o: [
        { t: "Contarlo todo, con nombres y fechas", d: { rep: -2, cri: 3, red: -3,
          msg: "Te ponen una anotación en el expediente. Tu excompañero deja de contestarte el teléfono." } },
        { t: "Decir que fue una conversación social", d: { rep: -3, ene: -2,
          msg: "Te miran largo. No hay sanción, pero tu nombre queda en una lista que nadie quiere tener.",
          luego: [{ en: 1, azar: [{ p: 55, id: 20320 }, { p: 45, id: 20321 }] }] } },
      ] },
    { id: 20313, por: "Armaste una tesis sobre una refinería", t: "Una mesa de materias primas te quiere", empleado: true,
      x: "Una trader de materias primas vio tu tesis y te invita a almorzar. Busca a alguien que entienda las plantas por dentro.",
      o: [
        { t: "Escucharla y dejar la puerta abierta", d: { red: 4, car: 1,
          msg: "Dos horas de refinerías, buques y diferenciales de precio. Te vas con su número y ganas de volver." } },
        { t: "Contárselo a tu jefe para negociar", d: { car: 3, red: -2, cash: 2000,
          msg: "Tu jefe iguala parte de lo que insinuaste. La trader se entera y no vuelve a escribir." } },
      ] },
    { id: 20320, por: "Le dijiste a cumplimiento que fue una charla social", t: "Aparecieron tus mensajes", empleado: true,
      x: "Revisando los teléfonos de la mesa aparecieron tus mensajes con la planta. Ya no es una charla: es tu palabra contra tus mensajes.",
      o: [
        { t: "Admitirlo y aceptar la sanción", d: { rep: -5, car: -4, cri: 3,
          msg: "Te congelan el bono del año y te sacan de la mesa. Conservas el empleo y la lección." } },
        { t: "Sostener tu versión hasta el final", d: { rep: -8, car: -6, ene: -4,
          msg: "Te quitan la firma en operaciones y te pasan a un escritorio sin pantalla. La historia corre por el sector." } },
      ] },
    { id: 20321, por: "Le dijiste a cumplimiento que fue una charla social", t: "El caso quedó archivado", empleado: true,
      x: "Cumplimiento cerró el caso sin sanción. Tu excompañero, en cambio, perdió el puesto en la refinería por hablar de más.",
      o: [
        { t: "Llamarle y ofrecer ayuda", d: { red: 2, cri: 2, ene: -2,
          msg: "Le ayudas a buscar otro trabajo. No te lo agradece mucho, pero acepta la ayuda." } },
        { t: "No volver a llamarle", d: { red: -3, ene: 1,
          msg: "Lo dejas ir. A veces lo ves en redes, ya en otra empresa, y pasas rápido." } },
      ] },

    /* ===== 20400 Una carretera con grietas ===== */
    { id: 20410, por: "Pujaste por una carretera de peaje", t: "La carretera es tuya",
      x: "Ganaron la puja. Ahora hay que operarla: casetas, cuadrillas, sensores y un concedente que llama todas las semanas.",
      o: [
        { t: "Meterte en la operación en persona", d: { cri: 3, car: 3, ene: -5,
          msg: "Aprendes cuánto cuesta un kilómetro de bacheo de noche. El activo rinde y tú duermes menos." } },
        { t: "Contratar un operador y mirar los números", d: { mod: 3, ene: 1,
          msg: "El operador cobra caro y cumple. En el tablero todo se ve verde, que no siempre es lo mismo que estar verde." } },
      ] },
    { id: 20411, por: "Le pusiste precio a las grietas de una carretera", t: "Otro fondo se la llevó",
      x: "Un fondo extranjero se llevó la carretera pagando bastante más de lo que tú querías poner. En la industria comentan que te faltó apetito.",
      o: [
        { t: "Ofrecerle al ganador tu análisis del pavimento", d: { red: 4, rep: 2, cash: 3000,
          msg: "Te lo agradecen con un café y luego con un encargo pagado: quieren que les asesores la rehabilitación." } },
        { t: "Esperar y ver", d: { cri: 2, ene: 2,
          msg: "Esperas. No es lo más heroico, pero el tiempo suele hablar por las grietas.",
          luego: [{ en: 3, azar: [{ p: 60, id: 20420 }, { p: 40, id: 20421 }] }] } },
      ] },
    { id: 20412, por: "Ofertaste al tope por una carretera con grietas", t: "El pavimento cede antes de tiempo",
      x: "El pavimento cedió antes de lo que prometía hasta tu plan. Hay que repavimentar ya, con el flujo de peajes todavía flojo.",
      o: [
        { t: "Pedir capital nuevo al comité", d: { cri: 2, car: -2, ene: -3,
          msg: "El comité aprueba el capital con caras largas. La carretera queda nueva y tu retorno, viejo." } },
        { t: "Renegociar el calendario con los bancos", d: { mod: 3, red: 2, ene: -4,
          msg: "Estiras la deuda dos años. Los bancos cobran caro el favor, pero nadie pone capital nuevo." } },
        { t: "Repavimentar por tramos", d: { cri: 3, rep: -2,
          msg: "Arreglas lo peor y dejas el resto. Los usuarios se quejan en la radio; el flujo aguanta." } },
      ] },
    { id: 20413, por: "Pujaste por una carretera de peaje", t: "El gobierno congela los peajes",
      x: "Hay elecciones y el gobierno anuncia que congela los peajes de tu carretera. El contrato dice que no puede; el ministro dice que sí.",
      o: [
        { t: "Ir a arbitraje con el contrato en la mano", d: { rep: 3, red: -4, ene: -3,
          msg: "El arbitraje tarda y cuesta, pero el contrato aguanta. El ministro no te saluda en los eventos." } },
        { t: "Cambiar tarifa congelada por más años de concesión", d: { cri: 4, red: 3, car: 2,
          msg: "Cambias tarifa de hoy por años de mañana. Ganas menos rápido y más seguro." } },
      ] },
    { id: 20414, por: "No quisiste pagar de más por una carretera", t: "El vendedor vuelve a llamar",
      x: "El proceso se cayó: nadie pagó lo que el vendedor quería. Ahora te llama directo, con un precio más bajo y un tono más amable.",
      o: [
        { t: "Comprarla al precio nuevo", d: { car: 4, cri: 2, ene: -3,
          msg: "Compras con la rehabilitación descontada. Esta vez el número técnico y el del modelo dicen lo mismo." } },
        { t: "Apretar por más descuento", d: { cri: 2, rep: 1, red: -3,
          msg: "El vendedor cuelga. Una semana después llama otra vez, menos amable. Cierras, con la relación gastada." } },
      ] },
    { id: 20420, por: "Esperaste a que las grietas hablaran", t: "Al ganador se le hundió el pavimento",
      x: "El pavimento cede en tres tramos, como calculaste. El fondo que pagó de más busca quien le compre la carretera con descuento.",
      o: [
        { t: "Volver a pujar, ahora barato", d: { car: 5, cri: 3, ene: -3,
          msg: "Compras la misma carretera por bastante menos. En el sector cuentan la historia con tu nombre." } },
        { t: "Dejarlo pasar: el activo quedó dañado", d: { cri: 2, ene: 1,
          msg: "Otro la compra y la arregla. Tú te quedas con tener razón, que no paga cuotas." } },
      ] },
    { id: 20421, por: "Esperaste a que las grietas hablaran", t: "El pavimento aguantó",
      x: "El ganador repavimentó antes de tiempo y la carretera rinde más de lo que creías. Tu número fue prudente; el de ellos, correcto.",
      o: [
        { t: "Estudiar qué hicieron distinto", d: { cri: 4, mod: 2, ene: -2,
          msg: "Usaron un asfalto modificado que descartaste por caro. Caro al principio, barato a la larga. Anotado." } },
        { t: "Sostener que tu número era el bueno", d: { rep: -2, ene: 1,
          msg: "Lo explicas en comité como suerte ajena. Te escuchan con cortesía y poca fe." } },
      ] },

    /* ===== 20500 La constructora de tu compañero ===== */
    { id: 20510, por: "Tu compañero de facultad fue a una licitación", t: "Tu compañero ganó la obra",
      x: "La constructora ganó la licitación. La obra arranca en un mes, le falta capital de trabajo y alguien que controle costos. Te llama primero.",
      o: [
        { t: "Montarle un control de costos semanal", d: { mod: 2, red: 3, ene: -3,
          msg: "Lo usa durante toda la obra y lo copia en las siguientes. Tú pierdes varios domingos." } },
        { t: "Prestarle capital de trabajo a corto plazo", d: { cash: 1000, red: 2, cri: -1,
          msg: "Le prestas para arrancar. Te devuelve a los seis meses, con un interés modesto y una botella." } },
        { t: "Recomendarle a alguien de tu red", d: { red: 2, ene: 1,
          msg: "Le pasas el contacto de un ingeniero de costos. Le va bien; a ti te llega solo el agradecimiento." } },
      ] },
    { id: 20511, por: "Ayudaste a armar una oferta de obra pública", t: "La obra se come el margen",
      x: "El acero subió a mitad de obra y el margen de la constructora se evaporó. Tu compañero pregunta qué se hace ahora.",
      o: [
        { t: "Buscar la cláusula de reajuste del contrato", d: { cri: 3, red: 2, ene: -3,
          msg: "Había una cláusula de reajuste que nadie había leído. Tú sí. Recuperan la mitad del golpe." } },
        { t: "Terminar a pérdida y cuidar el nombre", d: { rep: 4, cash: -2000, ene: -2,
          msg: "Terminan a tiempo y perdiendo. El municipio lo nota y los invita a la siguiente licitación." } },
      ] },
    { id: 20512, por: "Pusiste tus ahorros en una constructora pequeña", t: "El municipio no paga",
      x: "La obra se entregó hace cuatro meses y el municipio no ha pagado. La constructora tiene nómina, proveedores y tu dinero adentro.",
      o: [
        { t: "Ir a cobrar en persona con tu compañero", d: { red: 2, ene: -4, cash: 2000,
          msg: "Tres visitas, dos funcionarios y una firma. Cobran la mitad y la promesa del resto.",
          luego: [{ en: 1, azar: [{ p: 50, id: 20520 }, { p: 50, id: 20521 }] }] } },
        { t: "Venderle la factura a un fondo con descuento", d: { mod: 3, cri: 2, cash: 1500,
          msg: "Cobras hoy menos de lo que valía ayer. Es caro, pero la nómina sale el viernes." } },
        { t: "Esperar: el municipio siempre paga, tarde", d: { cash: -2000, ene: -1,
          msg: "Paga, sí. Año y medio después y sin intereses. La constructora sobrevive raspando." } },
      ] },
    { id: 20513, por: "Pusiste tus ahorros en una constructora pequeña", t: "Te ofrece la mitad de la empresa",
      x: "La constructora creció y tu compañero quiere que la mitad sea tuya. A cambio: más capital y que lleves tú las finanzas.",
      o: [
        { t: "Aceptar y llevar las finanzas de noche", d: { cash: -5000, cri: 3, car: 2, ene: -5,
          msg: "Ahora tienes dos trabajos y un balance lleno de maquinaria. Cuando una obra sale bien, sale muy bien." } },
        { t: "Quedarte con una parte pequeña", d: { cash: 3000, ene: 1,
          msg: "Él busca a otra persona para las finanzas. Tú cobras dividendos y conservas los domingos." } },
      ] },
    { id: 20514, por: "Tu compañero de facultad fue a una licitación", t: "Perdió la licitación por poco",
      x: "Tu compañero perdió por muy poco. El ganador ofertó tan bajo que en el gremio apuestan cuándo va a abandonar la obra.",
      o: [
        { t: "Prepararle la oferta para cuando la abandonen", d: { mod: 3, red: 3, ene: -2,
          msg: "El ganador abandona a los cinco meses y la oferta ya está lista. Tu compañero se queda con la obra." } },
        { t: "Decirle que se olvide de la obra pública", d: { cri: 2, red: -2,
          msg: "Le hablas de márgenes finos y pagos tarde. Te escucha, asiente y vuelve a licitar el mes siguiente." } },
      ] },
    { id: 20520, por: "Fuiste a cobrarle en persona a un municipio", t: "El municipio pagó el resto",
      x: "Llegó el resto del pago, tarde y sin disculpas. Tu compañero propone ir ahora por una obra más grande.",
      o: [
        { t: "Ir por la obra grande con él", d: { cri: 2, car: 3, ene: -4,
          msg: "Arman una oferta seria para una escuela entera. Tu nombre va en el contrato, al lado del suyo." } },
        { t: "Salirte con tu parte y tu ganancia", d: { cash: 6000, red: -1,
          msg: "Recuperas lo que pusiste y algo más. Tu compañero te despide con un abrazo y un poco de pena." } },
      ] },
    { id: 20521, por: "Fuiste a cobrarle en persona a un municipio", t: "Llegó un alcalde nuevo",
      x: "Hubo elecciones y el alcalde nuevo dice que esa deuda es de la gestión anterior. La constructora se queda sin aire.",
      o: [
        { t: "Demandar al municipio", d: { rep: 2, cash: -2000, ene: -4,
          msg: "El juicio va lento, pero va. Tu dinero, mientras tanto, duerme en un expediente." } },
        { t: "Cerrar la constructora en orden", d: { cash: -5000, cri: 3, red: 2,
          msg: "Pagan primero a la gente y al final a ustedes. Pierdes lo que pusiste y conservas a tu compañero." } },
      ] },

    /* ===== 20600 Una central en la montaña ===== */
    { id: 20610, por: "Te metiste en el financiamiento de una central", t: "La tuneladora dio con una falla",
      x: "La tuneladora encontró una falla geológica que nadie esperaba. La obra se frena y el costo sube con cada semana parada.",
      o: [
        { t: "Rediseñar el trazado del túnel", d: { cri: 4, car: 3, ene: -5,
          msg: "Un mes con geólogos y bancos. El túnel da un rodeo y la central sigue viva, más cara y más tarde.",
          luego: [{ en: 2, s: "cri", azar: [{ p: 55, id: 20620, bueno: true }, { p: 45, id: 20621, bueno: false }] }] } },
        { t: "Pedir al gobierno que asuma el sobrecosto", d: { rep: 2, red: -3, ene: -2,
          msg: "El gobierno acepta la mitad. La otra mitad la ponen el sponsor y tu paciencia." } },
      ] },
    { id: 20611, por: "Lideraste el financiamiento de una central", t: "El gobierno nuevo no quiere la central",
      x: "Las elecciones trajeron un gobierno que llama a la central un capricho del anterior. Quiere revisar el contrato entero.",
      o: [
        { t: "Defender el contrato en público", d: { rep: 3, red: -4, ene: -3,
          msg: "Das entrevistas con el contrato en la mano. El gobierno retrocede, pero te tiene en una lista." } },
        { t: "Negociar en privado una tarifa más baja", d: { cri: 3, red: 3, car: -1,
          msg: "Bajas un poco la tarifa a cambio de plazo. El proyecto gana menos y sobrevive al gobierno." } },
      ] },
    { id: 20612, por: "Te metiste en el financiamiento de una central", t: "La central da su primera energía",
      x: "Con retraso y sobre presupuesto, la central entra en operación. En la inauguración el ministro corta la cinta y te busca para la foto.",
      o: [
        { t: "Ir a la foto", d: { rep: 3, red: 4,
          msg: "Sales en todos los periódicos al lado del ministro. Útil hasta que el ministro deja de serlo." } },
        { t: "Quedarte con los ingenieros en la sala de control", d: { cri: 3, red: 2, ene: 1,
          msg: "Ves subir la carga en las pantallas. Nadie te fotografía y es el mejor día del año." } },
      ] },
    { id: 20613, por: "No firmaste a ciegas el túnel de una central", t: "Otro banco se quedó el mandato",
      x: "Otro banco tomó el mandato con condiciones más blandas y el ministerio lo anunció a lo grande. En tu comité preguntan qué pasó.",
      o: [
        { t: "Explicar el riesgo geológico con mapas", d: { cri: 3, rep: 2, ene: -2,
          msg: "Llevas los cortes geológicos al comité. Lo entienden. Igual te recuerdan que los mapas no facturan." } },
        { t: "Ir por el siguiente proyecto del ministerio", d: { red: 3, car: 2, ene: -3,
          msg: "Le pides cita al viceministro. Te recibe, toma nota y te promete la próxima licitación." } },
      ] },
    { id: 20614, por: "Le pasaste a otro banco una central difícil", t: "Te llaman para salvar el túnel",
      x: "La central tiene problemas y el banco que se quedó el mandato busca a alguien que entienda de túneles. Te llaman a ti.",
      o: [
        { t: "Asesorarles con un honorario alto", d: { cash: 8000, cri: 2, red: 2, ene: -3,
          msg: "Cobras caro y lo vales. Les ordenas el plan de contingencia en tres semanas." } },
        { t: "Decirles que no: por algo pasaste", d: { rep: 2, red: -2,
          msg: "Les deseas suerte. En el sector se comenta que leíste la montaña antes que nadie." } },
      ] },
    { id: 20620, por: "Rediseñaste el túnel de una central", t: "El rodeo funcionó",
      x: "El túnel nuevo esquiva la falla y la central entra en operación con un año de retraso. Los bancos cobran todas sus cuotas.",
      o: [
        { t: "Escribir el caso para el comité de riesgos", d: { cri: 4, rep: 3, ene: -2,
          msg: "Tu informe se vuelve lectura obligatoria para cualquiera que quiera financiar una montaña." } },
        { t: "Pedir el siguiente proyecto difícil", d: { car: 5, ene: -3,
          msg: "Te dan una presa más grande y un geólogo de cabecera. Tu agenda ya no tiene huecos." } },
      ] },
    { id: 20621, por: "Rediseñaste el túnel de una central", t: "La reserva no alcanzó",
      x: "El rodeo costó más de lo que nadie había previsto. Los bancos piden más capital al sponsor y el sponsor pide tu cabeza.",
      o: [
        { t: "Reestructurar la deuda con los bancos", d: { mod: 4, cri: 3, ene: -6,
          msg: "Meses de hojas de cálculo y reuniones. La central sobrevive con otra deuda y tú con otra arruga." } },
        { t: "Dejar que el sponsor busque otro banco líder", d: { rep: -4, car: -3, ene: 3,
          msg: "Te apartas del proyecto. Vuelves a dormir, pero en el sector cuentan la historia sin tus razones." } },
      ] },
  ],

  /* ===================== OPCIONES «SOLO TÚ» ===================== */
  opciones: [
    { escena: 34, t: "Estimarlo de cabeza por órdenes de magnitud", d: { cri: 4, mod: 2, rep: -1,
      msg: "Partes la pregunta en cuatro números redondos. Aciertas el orden de magnitud y fallas el detalle; alguien lo nota." } },
    { escena: 102, t: "Ir a ver la planta en vez de quedarte en el data room", d: { cri: 5, red: 2, mod: -2, ene: -4,
      msg: "Un día en la planta te dice más que cien archivos. Los cien archivos, eso sí, quedan sin leer." } },
    { escena: 108, t: "Tasar tú las plantas que respaldan el bono", d: { cri: 4, mod: 3, ene: -4, cash: -1500,
      msg: "Viajas, ves las plantas y calculas cuánto cuesta reponerlas. Sabes dónde está el piso; el viaje lo pagas tú." } },
    { escena: 42, t: "Ordenarlos en una matriz de severidad y probabilidad", d: { mod: 3, cri: 3, rep: -1, ene: -2,
      msg: "Dos ejes, ocho puntos y tres en rojo. El comité agradece el orden; alguien dice que parece un manual de seguridad." } },
  ],

  finales: [
    { id: "l10_botas", huellas: ["l10_sala_maquinas", "l10_frenaste_desembolso"], t: "Botas antes que modelo",
      x: "Te metiste en salas de máquinas y frenaste desembolsos hasta ver la obra. Tus modelos tenían menos celdas que los de otros y muchas más visitas." },
    { id: "l10_obras", huellas: ["l10_constructora", "l10_oferta_tecnica"], t: "Tus obras, tu balance",
      x: "Pusiste tus ahorros en una constructora y pujaste con el costo del asfalto en la cabeza. Aprendiste que una obra buena sale muy bien y la mala te la llevas puesta." },
  ],
};
