/* El Analista: escenas propias de la carrera de Contaduría (id "con"), lote 9.
   Ids 19000-19999. Cada raíz propia usa su centena: raíz 19N00 -> consecuencias 19N01 a 19N09.
   Las raíces son directas (no chequeos), así que cada consecuencia está escrita
   para valer con cualquiera de las opciones que la sortean. */
module.exports = {
  carrera: "con",

  huellas: {
    l9_rastreaste: "Rastreaste una partida vieja que todos daban por buena",
    l9_dejaste_partida: "Dejaste una partida sin explicar porque siempre estuvo ahí",
    l9_destapaste: "Le llevaste al socio un desvío de fondos de un cliente",
    l9_no_cambiaste_fecha: "Te negaste a moverle la fecha a un contrato",
    l9_creativo: "Le moviste la fecha a un contrato para cuidar al cliente",
    l9_priorizaste: "Priorizaste por riesgo una temporada de cierres",
    l9_cierres_a_fuerza: "Sacaste cinco cierres a la fuerza con el equipo amanecido",
    l9_recortaste_pruebas: "Recortaste pruebas en los clientes que nadie miraba",
    l9_contaste: "Exigiste contar de nuevo un inventario que no estaba",
    l9_carta_vendedor: "Aceptaste un inventario fantasma con una carta del vendedor",
    l9_rectificaste: "Rectificaste una deducción antes de que la encontraran",
    l9_salvedad: "Firmaste con una salvedad que nadie quería leer",
    l9_firmaste_limpio: "Firmaste limpio con un juicio grande encima",
    l9_cartera: "Compraste entera la cartera de un auditor que se retiraba",
  },

  propias: [
    /* ===== 19100 Una partida en tránsito (Pasante a Analista) ===== */
    { id: 19100, min: 0, max: 2, empleado: true, t: "Una partida en tránsito de hace ocho meses",
      x: "Conciliando los bancos de un cliente, encuentras un depósito registrado que nunca llegó al banco. Tu supervisor dice que siempre ha estado ahí.",
      o: [
        { t: "Rastrearla hasta el origen, aunque no te toque", d: { cri: 5, rep: 2, ene: -4, deja: "l9_rastreaste",
          msg: "Tres noches entre extractos y comprobantes. Llegas a un asiento manual sin soporte y a una firma que no reconoces.",
          luego: [{ en: 1, s: "cri", azar: [{ p: 35, id: 19101 }, { p: 30, id: 19102 }, { p: 25, id: 19104, bueno: true }, { p: 10, id: 19103, bueno: false }] }] } },
        { t: "Anotarla en el papel de trabajo y seguir", d: { cri: 2, ene: -1,
          msg: "La dejas escrita con fecha y monto. Si alguien pregunta, consta. Si nadie pregunta, también.",
          luego: [{ en: 1, azar: [{ p: 40, id: 19102 }, { p: 30, id: 19103 }, { p: 20, id: 19101 }, { p: 10, id: 19104 }] }] } },
        { t: "Hacer como tu supervisor: siempre ha estado ahí", d: { ene: 3, cri: -2, deja: "l9_dejaste_partida",
          msg: "La partida sigue donde estaba. Tú sigues con la siguiente cuenta, que también cuadra a la fuerza.",
          luego: [{ en: 1, azar: [{ p: 45, id: 19103 }, { p: 30, id: 19101 }, { p: 25, id: 19102 }] }] } },
      ] },

    /* ===== 19200 El cliente quiere ser creativo ===== */
    { id: 19200, min: 1, max: 3, empleado: true, t: "El cliente quiere ser creativo",
      x: "Último día del año. El gerente de un cliente pide registrar ya un contrato que se firma en enero. «Es lo mismo, solo cambia la fecha», dice.",
      o: [
        { t: "Negarte y dejarlo por escrito", d: { rep: 4, cri: 3, red: -3, deja: "l9_no_cambiaste_fecha",
          msg: "Mandas un correo con la norma citada y copia al socio. El gerente responde con un «entendido» helado.",
          luego: [{ en: 1, azar: [{ p: 45, id: 19202 }, { p: 35, id: 19203 }, { p: 20, id: 19201 }] }] } },
        { t: "Proponer explicarlo en las notas, sin mover la fecha", d: { mod: 3, cri: 3, red: 1,
          msg: "El ingreso queda en enero y el contrato, contado en una nota. Todos ceden un poco y nadie queda feliz.",
          luego: [{ en: 1, azar: [{ p: 45, id: 19203 }, { p: 30, id: 19201 }, { p: 25, id: 19202 }] }] } },
        { t: "Aceptarlo: el socio pidió cuidar al cliente", d: { red: 3, car: 2, rep: -3, deja: "l9_creativo",
          msg: "El contrato entra en diciembre. El gerente te manda una caja de chocolates. Nunca te había mandado nada.",
          luego: [{ en: 1, s: "cri", azar: [{ p: 35, id: 19201 }, { p: 30, id: 19204, bueno: false }, { p: 20, id: 19203, bueno: true }, { p: 15, id: 19202 }] }] } },
      ] },

    /* ===== 19300 Cinco cierres el mismo mes ===== */
    { id: 19300, min: 2, max: 4, empleado: true, t: "Cinco cierres el mismo mes",
      x: "Enero. Cinco clientes cierran a la vez, tu equipo tiene la mitad de la gente y el socio quiere todo listo para el quince.",
      o: [
        { t: "Priorizar por riesgo y avisar que dos se atrasan", d: { cri: 5, rep: 1, car: -2, deja: "l9_priorizaste",
          msg: "Le dices al socio cuáles salen y cuáles no. Frunce el ceño, pero firma tu calendario.",
          luego: [{ en: 1, azar: [{ p: 40, id: 19304 }, { p: 30, id: 19303 }, { p: 15, id: 19301 }, { p: 15, id: 19302 }] }] } },
        { t: "Sacarlos todos con el equipo amanecido", d: { car: 4, ene: -8, red: -2, deja: "l9_cierres_a_fuerza",
          msg: "Cinco cierres el quince, a las cuatro de la mañana. El socio te felicita. El equipo no dice nada.",
          luego: [{ en: 1, azar: [{ p: 45, id: 19301 }, { p: 35, id: 19303 }, { p: 20, id: 19302 }] }] } },
        { t: "Recortar pruebas en los clientes chicos", d: { ene: 3, car: 2, cri: -3, deja: "l9_recortaste_pruebas",
          msg: "Muestras más chicas y menos confirmaciones en los clientes que nadie mira. Todo sale a tiempo.",
          luego: [{ en: 1, azar: [{ p: 45, id: 19302 }, { p: 20, id: 19304 }, { p: 20, id: 19303 }, { p: 15, id: 19301 }] }] } },
      ] },

    /* ===== 19400 El inventario que no está ===== */
    { id: 19400, min: 3, max: 5, t: "El inventario que no está en la bodega",
      x: "Due diligence para un comprador. En los libros hay el doble de inventario que en la bodega. El vendedor dice que el resto viene en camino.",
      o: [
        { t: "Exigir otro conteo con el comprador presente", d: { cri: 5, ene: -4, red: -2, deja: "l9_contaste",
          msg: "El vendedor protesta, el comprador te apoya y el conteo se come un sábado entero.",
          luego: [{ en: 1, s: "cri", azar: [{ p: 35, id: 19404, bueno: true }, { p: 35, id: 19402 }, { p: 30, id: 19401 }] }] } },
        { t: "Descontarlo del precio en tu informe", d: { mod: 4, cri: 2,
          msg: "Pones el inventario dudoso en cero y bajas el valor. El informe sale a tiempo y sin pelea.",
          luego: [{ en: 1, azar: [{ p: 50, id: 19401 }, { p: 25, id: 19402 }, { p: 25, id: 19403 }] }] } },
        { t: "Aceptarlo con una carta firmada del vendedor", d: { red: 3, ene: 2, cri: -3, deja: "l9_carta_vendedor",
          msg: "El vendedor firma la carta en cinco minutos. Demasiado rápido, piensas, y la archivas igual.",
          luego: [{ en: 1, azar: [{ p: 55, id: 19403 }, { p: 45, id: 19401 }] }] } },
      ] },

    /* ===== 19500 Fiscalización de tres años ===== */
    { id: 19500, min: 2, max: 5, t: "Fiscalización de tres años",
      x: "El fisco cita a un cliente por tres años de declaraciones que preparó tu equipo. En uno hay una deducción que hoy no aprobarías.",
      o: [
        { t: "Rectificar antes de que la encuentren", d: { cri: 4, rep: 3, red: -2, deja: "l9_rectificaste",
          msg: "El cliente paga la diferencia con recargo y te mira como si el recargo lo hubieras inventado tú.",
          luego: [{ en: 1, azar: [{ p: 40, id: 19501 }, { p: 35, id: 19504 }, { p: 25, id: 19503 }] }] } },
        { t: "Defender la deducción con la mejor lectura de la ley", d: { mod: 3, cri: 2, ene: -3,
          msg: "Armas un escrito de doce páginas con tres sentencias. Es buen argumento. Falta saber si alcanza.",
          luego: [{ en: 1, s: "cri", azar: [{ p: 40, id: 19502, bueno: true }, { p: 35, id: 19503, bueno: false }, { p: 25, id: 19501 }] }] } },
        { t: "Negociar con el fiscalizador un acuerdo global", d: { red: 4, cri: -1,
          msg: "Una reunión, dos cafés y un acuerdo que nadie celebra. El cliente paga algo y la deducción ni se menciona.",
          luego: [{ en: 1, azar: [{ p: 40, id: 19502 }, { p: 35, id: 19501 }, { p: 25, id: 19503 }] }] } },
      ] },

    /* ===== 19600 Firmar o no firmar ===== */
    { id: 19600, min: 4, max: 6, t: "Firmar o no firmar",
      x: "Firmas la auditoría de un cliente grande. La gerencia se niega a reservar plata para un juicio que puede perder. El informe vence el viernes.",
      o: [
        { t: "Firmar con una salvedad: falta reservar el juicio", d: { rep: 5, cri: 3, red: -4, deja: "l9_salvedad",
          msg: "Tu informe dice, en un párrafo seco, que los números no reflejan el juicio. El directorio lo lee tres veces.",
          luego: [{ en: 1, azar: [{ p: 35, id: 19601 }, { p: 30, id: 19604 }, { p: 20, id: 19602 }, { p: 15, id: 19603 }] }] } },
        { t: "Firmar limpio y contar el juicio en una nota", d: { cri: 2, red: 1,
          msg: "La opinión sale limpia y el juicio queda contado en las notas, para quien las lea. Casi nadie las lee.",
          luego: [{ en: 1, azar: [{ p: 40, id: 19603 }, { p: 40, id: 19602 }, { p: 20, id: 19601 }] }] } },
        { t: "Firmar limpio: el juicio es ganable", d: { cash: 4000, red: 3, rep: -2, deja: "l9_firmaste_limpio",
          msg: "Firmas el jueves, un día antes. La gerencia te invita a almorzar y pide la botella cara.",
          luego: [{ en: 1, azar: [{ p: 50, id: 19603 }, { p: 40, id: 19602 }, { p: 10, id: 19601 }] }] } },
      ] },

    /* ===== 19700 Una cartera de clientes en venta (Director a Socio) ===== */
    { id: 19700, min: 5, max: 6, t: "Un auditor se retira y vende su cartera",
      x: "Un colega veterano se jubila y te ofrece sus clientes: veinte empresas que cierran cada año y que solo cambiarían de auditor a disgusto.",
      o: [
        { t: "Comprarla entera", d: { cash: -10000, car: 5, ene: -4, deja: "l9_cartera",
          msg: "Firmas, pagas y heredas veinte clientes, con sus archivos y sus mañas.",
          luego: [{ en: 1, azar: [{ p: 35, id: 19703 }, { p: 30, id: 19702 }, { p: 20, id: 19701 }, { p: 15, id: 19704 }] }] } },
        { t: "Revisar cliente por cliente y comprar los buenos", d: { cash: -5000, cri: 4, ene: -3, red: -1,
          msg: "Te quedas con doce. El colega se ofende un poco por los ocho que dejaste.",
          luego: [{ en: 1, azar: [{ p: 45, id: 19703 }, { p: 25, id: 19704 }, { p: 15, id: 19702 }, { p: 15, id: 19701 }] }] } },
        { t: "Declinar y crecer con tus propios clientes", d: { ene: 3, cri: 1,
          msg: "Le deseas buen retiro. La cartera se la queda otro colega, más rápido de lo que esperabas.",
          luego: [{ en: 1, azar: [{ p: 50, id: 19704 }, { p: 50, id: 19705 }] }] } },
      ] },
  ],

  escenas: [
    /* ===== consecuencias de 19100 ===== */
    { id: 19101, empleado: true, por: "Te topaste con una partida en tránsito vieja", t: "La partida tenía dueño",
      x: "Aquella partida no era un error. Alguien de la tesorería del cliente se transfiere plata poco a poco, y el patrón ya está a la vista.",
      o: [
        { t: "Llevárselo al socio con los papeles", d: { rep: 3, cri: 2, ene: -3, deja: "l9_destapaste",
          msg: "El socio lee en silencio, pasa las hojas dos veces y cierra la puerta de su oficina.",
          luego: [{ en: 1, s: "rep", azar: [{ p: 55, id: 19105, bueno: true }, { p: 45, id: 19106, bueno: false }] }] } },
        { t: "Comentárselo primero a tu supervisor", d: { red: 2, cri: 1,
          msg: "Tu supervisor palidece: firmó esa conciliación tres años seguidos. Te pide unos días para «ordenarlo»." } },
        { t: "No es tu cliente ni tu problema", d: { ene: 2, rep: -4,
          msg: "Cierras el archivo. Meses después lo descubre otro, y tu nombre aparece en la hoja de revisión." } },
      ] },
    { id: 19102, por: "Te topaste con una partida en tránsito vieja", t: "Era un depósito duplicado",
      x: "La partida era un depósito registrado dos veces por un auxiliar que ya no trabaja ahí. Aburrido, inocente y ocho meses inflando la caja.",
      o: [
        { t: "Proponer el ajuste y un control para que no se repita", d: { cri: 3, rep: 2, ene: -2,
          msg: "El ajuste sale en una línea. El control nuevo, en dos páginas que el cliente sí adopta." } },
        { t: "Proponer el ajuste y nada más", d: { ene: 1, cri: 1,
          msg: "Ajuste hecho, caja corregida. Nadie lo vuelve a mencionar, que en auditoría es casi un aplauso." } },
      ] },
    { id: 19103, empleado: true, por: "Te topaste con una partida en tránsito vieja", t: "Control de calidad pregunta por la partida",
      x: "La revisión de calidad de la firma toma ese encargo al azar y pregunta por qué nadie investigó una partida de ocho meses.",
      o: [
        { t: "Asumir que debiste insistir", d: { rep: 1, cri: 3, car: -2,
          msg: "Lo dices sin adornos. El revisor anota «el equipo» en vez de tu nombre, lo cual es un favor." } },
        { t: "Señalar que tu supervisor dio la orden", d: { rep: -2, red: -4, car: 1,
          msg: "Es cierto y queda en el acta. Tu supervisor no vuelve a pedirte nada, ni a darte nada." } },
      ] },
    { id: 19104, empleado: true, por: "Te topaste con una partida en tránsito vieja", t: "El cliente quiere contratarte",
      x: "El gerente de finanzas de aquel cliente vio cómo trabajas y te ofrece un puesto en su equipo. Más sueldo y ningún cierre ajeno.",
      o: [
        { t: "Aceptar y pasarte al otro lado", d: { cash: 3000, car: 2, red: 2, cri: -1,
          msg: "Ahora preparas los papeles que otros revisan. Sabes exactamente qué van a buscar." } },
        { t: "Quedarte en la firma a seguir aprendiendo", d: { cri: 3, red: 2,
          msg: "Le dices que por ahora no. Te deja la puerta abierta y su número en tu agenda." } },
      ] },
    { id: 19105, por: "Le llevaste al socio un desvío de fondos", t: "El cliente pide que te quedes",
      x: "El cliente recuperó parte de lo desviado y despidió a quien lo hizo. Ahora pide que seas tú quien revise su tesorería en cada cierre.",
      o: [
        { t: "Aceptar y quedarte con el cliente", d: { car: 4, rep: 3, cash: 1500, ene: -2,
          msg: "Te asignan el cliente de forma fija. Es tu primer encargo con tu nombre en la carpeta." } },
        { t: "Pedir rotar a otro cliente", d: { cri: 2, red: 2, ene: 1,
          msg: "Prefieres no quedar como la pieza de un solo caso. El socio lo entiende y lo anota, para bien." } },
      ] },
    { id: 19106, empleado: true, por: "Le llevaste al socio un desvío de fondos", t: "El cliente era amigo del socio",
      x: "El socio arregló el asunto en privado, sin informe y sin ruido. A ti te sacaron del encargo con una palmada en la espalda.",
      o: [
        { t: "Dejarlo así y aprender la lección", d: { cri: 3, ene: -2, red: -1,
          msg: "Aprendes cómo funciona la firma por dentro. No te gusta lo que aprendes, pero lo aprendes." } },
        { t: "Pedir que conste por escrito lo que encontraste", d: { rep: 4, red: -4, car: -2,
          msg: "Te mandan un correo de dos líneas que lo reconoce. Lo guardas en tres lugares distintos." } },
      ] },

    /* ===== consecuencias de 19200 ===== */
    { id: 19201, por: "Un cliente te pidió adelantar un ingreso", t: "Otro auditor mira aquel cierre",
      x: "El cliente cambió de auditor y la firma nueva revisa el cierre de aquel año. Pregunta quién decidió cómo se registró el contrato de enero.",
      o: [
        { t: "Mostrar tus papeles de trabajo tal cual", d: { rep: 2, cri: 2, ene: -2,
          msg: "Tus papeles dicen lo que pasó, con fecha. Lo que digan de ti depende de lo que hiciste." } },
        { t: "Dejar que responda tu firma", d: { ene: 1, red: -1,
          msg: "Sale una carta de un párrafo cuidadoso. No sabes bien qué dice, y prefieres no saberlo." } },
      ] },
    { id: 19202, empleado: true, por: "Un cliente te pidió adelantar un ingreso", t: "El cliente se va con otra firma",
      x: "Aquel gerente convenció al directorio de cambiar de auditor. El socio te pregunta, sin mirarte, si valía la pena.",
      o: [
        { t: "Decir que sí, y explicar por qué", d: { rep: 3, cri: 2, car: -2,
          msg: "Explicas la norma otra vez. El socio asiente despacio. La facturación del año no asiente." } },
        { t: "Decir que la próxima vez lo harías distinto", d: { red: 2, car: 1, rep: -2,
          msg: "El socio queda tranquilo. Tú no tanto: no sabes bien qué quisiste decir." } },
      ] },
    { id: 19203, por: "Un cliente te pidió adelantar un ingreso", t: "Aquel gerente ahora es director",
      x: "El gerente del contrato de enero ahora dirige las finanzas de otra empresa. Te llama: necesita un auditor en quien confiar.",
      o: [
        { t: "Ir a la reunión y llevarte el encargo", d: { car: 4, cash: 2000, red: 3, ene: -2,
          msg: "El encargo es tuyo. Cuando llega el contrato firmado, nadie en la oficina se lo esperaba." } },
        { t: "Preguntarle por qué confía en ti", d: { cri: 3, red: 2,
          msg: "Te lo dice con franqueza. Lo que oyes te dice más de ti que cualquier evaluación anual." } },
      ] },
    { id: 19204, empleado: true, por: "Le moviste la fecha a un contrato", t: "El regulador pide los papeles de aquel cierre",
      x: "El regulador investiga al cliente por adelantar ingresos. Pide los papeles de trabajo de aquel año, y tu nombre está en la revisión.",
      o: [
        { t: "Cooperar y contar lo que pasó", d: { cri: 3, ene: -4,
          msg: "Cuentas la conversación del último día del año, palabra por palabra. Te escuchan sin interrumpir.",
          luego: [{ en: 1, s: "rep", azar: [{ p: 55, id: 19205, bueno: true }, { p: 45, id: 19206, bueno: false }] }] } },
        { t: "Decir que seguiste instrucciones del socio", d: { rep: -4, red: -3, ene: -2,
          msg: "Es verdad. El socio dice que no lo recuerda así. Ahora hay dos versiones y un solo problema." } },
      ] },
    { id: 19205, por: "Contaste al regulador cómo se movió una fecha", t: "Te citan como testigo y nada más",
      x: "El expediente sigue contra el cliente. A ti te toman declaración, te dan las gracias y te dejan ir con una advertencia en tu legajo.",
      o: [
        { t: "Seguir como si nada hubiera pasado", d: { ene: 2, rep: -1,
          msg: "Vuelves a tus cierres. La advertencia sigue en el legajo, esperando a que alguien la lea." } },
        { t: "Contar el caso en la firma como lección", d: { rep: 3, red: 2, ene: -1,
          msg: "Lo cuentas en la capacitación anual, sin nombres. Los pasantes toman nota. Los socios, no tanto." } },
      ] },
    { id: 19206, por: "Contaste al regulador cómo se movió una fecha", t: "Te suspenden la matrícula seis meses",
      x: "El colegio profesional decide que debiste negarte. Seis meses sin poder firmar nada, y en la firma te mandan a trabajo de escritorio.",
      o: [
        { t: "Usar los seis meses para estudiar", d: { cri: 5, ene: 2, car: -3,
          msg: "Lees normas que nunca habías leído enteras. Vuelves con la matrícula limpia y menos ganas de ser flexible." } },
        { t: "Apelar la sanción", d: { cash: -2000, ene: -3, rep: 1,
          msg: "La apelación tarda más que la sanción. Ganas en el papel cuando ya no importa." } },
      ] },

    /* ===== consecuencias de 19300 ===== */
    { id: 19301, empleado: true, por: "Pasaste una temporada de cinco cierres", t: "Tu mejor asistente renuncia",
      x: "Se va a una empresa con horario de oficina. Te lo dice en el pasillo, con la carta ya firmada y cara de alivio.",
      o: [
        { t: "Pedirle la verdad sobre la temporada", d: { cri: 3, red: 2, ene: -1,
          msg: "Te la dice. Duele un poco, y te sirve más que cualquier evaluación de desempeño." } },
        { t: "Pelear con el socio un aumento para retenerle", d: { red: 1, car: -2, ene: -2,
          msg: "Se queda un año más. El resto del equipo se entera del aumento y hace cuentas." } },
        { t: "Desearle suerte y repartir su trabajo", d: { ene: -3, red: 1,
          msg: "Repartes su carga entre los demás. El próximo enero va a ser más largo." } },
      ] },
    { id: 19302, empleado: true, por: "Pasaste una temporada de cinco cierres", t: "La revisión elige un cliente chico",
      x: "La revisión interna de calidad escoge uno de los clientes chicos de aquel enero. Piden ver las muestras y las confirmaciones.",
      o: [
        { t: "Responder tú por cada papel", d: { rep: 2, cri: 2, ene: -3,
          msg: "Respondes por todo, incluso por lo que no hiciste. El revisor anota cada cosa con letra pequeña.",
          luego: [{ en: 1, s: "rep", azar: [{ p: 50, id: 19305, bueno: true }, { p: 50, id: 19306, bueno: false }] }] } },
        { t: "Que responda quien preparó cada papel", d: { red: -3, ene: 1,
          msg: "Cada asistente defiende lo suyo, unos mejor que otros. Todos notan que no estabas en la sala." } },
      ] },
    { id: 19303, empleado: true, por: "Pasaste una temporada de cinco cierres", t: "El socio te da el cliente grande",
      x: "El cliente más grande de la oficina cambia de gerente de encargo y el socio te elige. Más horas, más visibilidad y más formas de equivocarte.",
      o: [
        { t: "Aceptar y llevarte a tu equipo", d: { car: 5, cash: 2000, ene: -4,
          msg: "Tu equipo se muda contigo al cliente grande. Mismas caras, otro tamaño de problema." } },
        { t: "Aceptar con la condición de tener más gente", d: { car: 3, cri: 2, red: -1,
          msg: "El socio te da dos personas más y te recuerda que ahora no hay excusas." } },
      ] },
    { id: 19304, por: "Pasaste una temporada de cinco cierres", t: "Un cliente se sintió atendido a medias",
      x: "El gerente de uno de los clientes de aquel enero dice que lo atendieron a medias y pide otro equipo para este año.",
      o: [
        { t: "Ir a verlo y escuchar la queja entera", d: { red: 3, rep: 2, ene: -2,
          msg: "Una hora de reproches con café frío. Al final te pide que sigas, pero con más visitas." } },
        { t: "Aceptar el cambio sin pelear", d: { ene: 2, car: -2,
          msg: "Otro equipo se queda con el cliente. Tú te quedas con un enero menos y una cuenta menos." } },
      ] },
    { id: 19305, por: "Respondiste por todo en una revisión de calidad", t: "El revisor te pone de ejemplo",
      x: "En el informe anual de calidad, tu encargo aparece como ejemplo de cómo se responde a una observación. El socio lo reenvía a toda la oficina.",
      o: [
        { t: "Aprovechar y pedir el ascenso", d: { car: 4, red: -1,
          msg: "Lo pides con el informe impreso en la mano. El socio sonríe: dice que lo estaba esperando." } },
        { t: "Agradecerlo y seguir igual", d: { rep: 3, ene: 1,
          msg: "No dices nada. En la siguiente asignación, tu nombre aparece primero en la lista." } },
      ] },
    { id: 19306, por: "Respondiste por todo en una revisión de calidad", t: "La observación queda en tu legajo",
      x: "La revisión concluye que las pruebas fueron insuficientes y la observación queda a tu nombre. Tu ascenso de este año se congela.",
      o: [
        { t: "Rehacer tú las pruebas del cliente", d: { cri: 4, ene: -4,
          msg: "Las rehaces en tus fines de semana. El legajo no cambia, pero el siguiente revisor lo nota." } },
        { t: "Pedir que se reparta la responsabilidad", d: { car: 1, red: -3, rep: -1,
          msg: "Se reparte. Tu ascenso se descongela a medias y el equipo te saluda un poco menos." } },
      ] },

    /* ===== consecuencias de 19400 ===== */
    { id: 19401, por: "Revisaste un inventario que no cuadraba", t: "El comprador cierra y vuelve por más",
      x: "La compra se cerró a un precio que al comprador le pareció justo. Te escribe para darte las gracias y ofrecerte otro encargo.",
      o: [
        { t: "Aceptar el encargo nuevo", d: { cash: 3000, car: 3, ene: -3,
          msg: "Otro data room, otra bodega, otro vendedor que jura que todo está ahí." } },
        { t: "Aceptarlo con honorarios más altos", d: { cash: 4500, red: -2,
          msg: "Acepta con una mueca. Ahora te paga más y va a revisar cada línea de tu factura." } },
      ] },
    { id: 19402, por: "Revisaste un inventario que no cuadraba", t: "El vendedor se levanta de la mesa",
      x: "La operación se cayó. El vendedor dice que lo trataron como a un ladrón y el comprador no sabe si darte las gracias o la culpa.",
      o: [
        { t: "Explicarle al comprador lo que se ahorró", d: { rep: 3, cri: 2,
          msg: "Le pones en una hoja lo que habría pagado por mercancía que no existía. Deja de dudar." } },
        { t: "Ofrecerle revisar el siguiente candidato sin cobrar", d: { red: 4, ene: -4,
          msg: "Trabajas gratis un mes. El comprador no lo olvida, y tu contador personal tampoco." } },
      ] },
    { id: 19403, por: "Revisaste un inventario que no cuadraba", t: "Después del cierre, falta mercancía",
      x: "Seis meses después de la compra, el comprador cuenta la bodega. Falta casi la mitad del inventario que estaba en el balance.",
      o: [
        { t: "Dar la cara con tus papeles", d: { cri: 2, ene: -4,
          msg: "Llevas tu informe y tus notas de la bodega. Todo lo que hiciste, y también lo que no.",
          luego: [{ en: 1, s: "rep", azar: [{ p: 45, id: 19405, bueno: true }, { p: 55, id: 19406, bueno: false }] }] } },
        { t: "Dejar que lo resuelvan los abogados", d: { cash: -3000, rep: -3, ene: 1,
          msg: "Tu abogado contesta todo por escrito y cobra por hora. El comprador saca sus conclusiones." } },
      ] },
    { id: 19404, por: "Exigiste contar de nuevo un inventario", t: "Te buscan para encontrar lo escondido",
      x: "Se corrió la voz del conteo del sábado. Dos fondos te llaman para que revises sus próximas compras antes de firmar.",
      o: [
        { t: "Tomar los dos encargos", d: { cash: 5000, car: 3, ene: -6,
          msg: "Dos compras a la vez, dos bodegas y dos vendedores nerviosos. Duermes en los aviones." } },
        { t: "Tomar uno y hacerlo a fondo", d: { cash: 2500, rep: 3, cri: 2,
          msg: "Eliges el más enredado. Encuentras dos cosas que el vendedor esperaba que no vieras." } },
      ] },
    { id: 19405, por: "Diste la cara por un inventario faltante", t: "Tus papeles te salvan",
      x: "Tu informe advertía el riesgo en una línea que nadie leyó. El juez sí la leyó. El pleito sigue, pero ya no contra ti.",
      o: [
        { t: "Ofrecerte como perito para el comprador", d: { cash: 3000, rep: 3, ene: -3,
          msg: "Ahora te pagan por explicar ante un juez lo que el vendedor escondió. Lo mismo, con toga enfrente." } },
        { t: "Salir del caso y no volver a pensarlo", d: { ene: 3, cri: 1,
          msg: "Guardas la copia de aquella línea en tu escritorio. Te recuerda para qué sirve escribir todo." } },
      ] },
    { id: 19406, por: "Diste la cara por un inventario faltante", t: "Te nombran en la demanda",
      x: "El comprador demanda al vendedor y, por si acaso, también a ti. Tu seguro profesional cubre una parte; tu sueño, ninguna.",
      o: [
        { t: "Pelear hasta el final", d: { cash: -4000, ene: -5, rep: 2,
          msg: "Dos años de audiencias. Te sacan del caso al final, más por cansancio que por justicia." } },
        { t: "Llegar a un acuerdo y cerrar el capítulo", d: { cash: -6000, ene: 2, rep: -2,
          msg: "Pagas para que se acabe. En la plaza se comenta, en voz baja, que pagaste." } },
      ] },

    /* ===== consecuencias de 19500 ===== */
    { id: 19501, por: "Te tocó una fiscalización a un cliente", t: "El cliente quiere que pagues el recargo",
      x: "El cliente dice que el criterio fue de tu equipo y que el recargo y los intereses los debería pagar quien lo aconsejó: tú.",
      o: [
        { t: "Pagar una parte y conservar al cliente", d: { cash: -3000, red: 3, rep: 1,
          msg: "Pagas la mitad. El cliente se queda, y ahora lee tus correos con lupa." } },
        { t: "Negarte: la declaración la firmó él", d: { rep: 2, red: -3, car: -1,
          msg: "Tienes razón en el papel. El cliente se va a fin de año, también en el papel." } },
      ] },
    { id: 19502, por: "Te tocó una fiscalización a un cliente", t: "La fiscalización se cierra a favor",
      x: "El fisco cierra el expediente sin ajustes mayores. El cliente, con alivio, quiere que lleves los impuestos de todo su grupo.",
      o: [
        { t: "Aceptar todo el grupo", d: { cash: 4000, car: 3, ene: -4,
          msg: "Seis empresas más, seis calendarios fiscales y un cliente que ahora te llama los domingos." } },
        { t: "Aceptar solo lo que puedes atender bien", d: { cash: 2000, rep: 2, cri: 1,
          msg: "Tomas dos de las seis. El cliente se sorprende, y le gusta más que si hubieras dicho que sí a todo." } },
      ] },
    { id: 19503, por: "Te tocó una fiscalización a un cliente", t: "La misma deducción en otros clientes",
      x: "Revisas y encuentras el mismo criterio en las declaraciones de otros cuatro clientes. Si el fisco tira del hilo, tira de todos.",
      o: [
        { t: "Avisarles a todos y proponer rectificar", d: { rep: 4, cri: 3, red: -3, ene: -3,
          msg: "Cuatro llamadas incómodas en un día. Ninguno te agradece en la llamada.",
          luego: [{ en: 1, azar: [{ p: 50, id: 19505 }, { p: 50, id: 19506 }] }] } },
        { t: "Esperar a ver si el fisco lo encuentra", d: { ene: 2, rep: -2, cri: -1,
          msg: "Dejas las cuatro carpetas en el último cajón. Cada vez que suena el teléfono, piensas en ellas." } },
      ] },
    { id: 19504, por: "Rectificaste una deducción antes de que la vieran", t: "Te invitan a hablar ante el gremio",
      x: "El colegio de contadores se enteró de cómo manejaste la fiscalización y te invita a dar una charla sobre rectificar a tiempo.",
      o: [
        { t: "Dar la charla y contar el caso sin nombres", d: { rep: 4, red: 4, ene: -2,
          msg: "Sala llena. Tres asistentes te piden la presentación y uno te pide trabajo." } },
        { t: "Declinar: el cliente no querría", d: { cri: 2, ene: 1, red: -1,
          msg: "El cliente nunca se entera de que lo protegiste. Es lo que tiene proteger bien." } },
      ] },
    { id: 19505, por: "Avisaste a tus clientes de un error tuyo", t: "Los clientes se quedan",
      x: "Tres de los cuatro rectificaron y se quedaron. Dicen que nunca un asesor les había avisado de un error propio antes de que lo encontraran otros.",
      o: [
        { t: "Convertirlo en una revisión anual para todos", d: { cash: 2500, rep: 3, ene: -3,
          msg: "Lo ofreces como servicio. Lo que empezó como disculpa termina en factura recurrente." } },
        { t: "Agradecer y seguir sin hacer ruido", d: { red: 3, ene: 1,
          msg: "Te recomiendan sin que se lo pidas. Es la publicidad más barata que vas a tener." } },
      ] },
    { id: 19506, por: "Avisaste a tus clientes de un error tuyo", t: "Dos clientes se van con otro asesor",
      x: "Dos de los cuatro rectificaron y luego se fueron. Uno lo dice claro: prefiere un asesor que no se equivoque, aunque no avise.",
      o: [
        { t: "Aceptarlo y revisar tu método", d: { cri: 4, car: -2,
          msg: "Rehaces tu lista de revisión entera. Es más larga y más aburrida, y no deja pasar nada." } },
        { t: "Llamarlos para despedirte bien", d: { red: 2, ene: -1,
          msg: "Uno te agradece la llamada. El otro no contesta, pero escucha el mensaje completo." } },
      ] },

    /* ===== consecuencias de 19600 ===== */
    { id: 19601, por: "Firmaste la auditoría de un cliente con un juicio", t: "El cliente cambia de auditor",
      x: "El directorio decidió que necesita «una mirada fresca» y cambia de auditor. Te enteras por la licitación, como cualquiera.",
      o: [
        { t: "Despedirte con una carta cordial", d: { red: 2, car: -2, ene: 1,
          msg: "Una carta corta y sin reproches. El presidente del directorio te contesta a mano." } },
        { t: "Llamar a un consejero y preguntar qué pasó", d: { cri: 3, red: -1, car: -2,
          msg: "Te lo cuenta con más detalle del que querías. Aprendes a qué le temía la gerencia." } },
      ] },
    { id: 19602, por: "Firmaste la auditoría de un cliente con un juicio", t: "La empresa pierde el juicio",
      x: "La sentencia salió en contra. El golpe va al balance de este año y los bancos acreedores llaman para preguntar quién sabía qué.",
      o: [
        { t: "Mostrar lo que firmaste y por qué", d: { cri: 3, ene: -4,
          msg: "Pones tu informe sobre la mesa. Para algunos es una defensa; para otros, una confesión.",
          luego: [{ en: 1, s: "rep", azar: [{ p: 50, id: 19605, bueno: true }, { p: 50, id: 19606, bueno: false }] }] } },
        { t: "Dejar que hable el abogado de la firma", d: { cash: -3000, rep: -2, ene: 1,
          msg: "El abogado habla mucho y dice poco. Los bancos anotan que no hablaste." } },
      ] },
    { id: 19603, por: "Firmaste la auditoría de un cliente con un juicio", t: "La empresa gana el juicio",
      x: "Ganaron. La gerencia te recuerda en cada reunión que tenía razón, y pregunta si tus honorarios también podrían ser más optimistas.",
      o: [
        { t: "Sostener que la duda era legítima", d: { cri: 3, rep: 1, red: -2,
          msg: "Ganar no quiere decir que no se pudiera perder. Lo explicas una vez y no lo repites." } },
        { t: "Ofrecer un descuento para cuidar la relación", d: { cash: -2000, red: 4,
          msg: "El descuento calma a la gerencia. El próximo año piden otro, por costumbre." } },
      ] },
    { id: 19604, por: "Firmaste con una salvedad que nadie quería", t: "Los bancos piden tu firma",
      x: "Te llaman empresas que nunca te habían buscado: sus bancos les pidieron un auditor que no firme cualquier cosa.",
      o: [
        { t: "Tomar todos los que puedas", d: { cash: 6000, car: 4, ene: -6,
          msg: "Duplicas la cartera en un año. El equipo no se duplica, y se nota en enero." } },
        { t: "Elegir con cuidado a quién auditas", d: { cash: 3000, rep: 3, cri: 2,
          msg: "Dices que no a la mitad. Los que aceptas saben que tu firma no viene incluida en el precio." } },
      ] },
    { id: 19605, por: "Mostraste lo que firmaste de un juicio perdido", t: "El regulador archiva tu parte",
      x: "El regulador revisó tus papeles y concluyó que lo que sabías estaba dicho donde tenía que estar. Tu parte del expediente se archiva.",
      o: [
        { t: "Seguir con tus clientes como siempre", d: { rep: 3, ene: 2,
          msg: "Nadie te felicita, que es como se celebra en esta profesión. Tus clientes renuevan." } },
        { t: "Usar el caso para subir tus honorarios", d: { cash: 3000, rep: 1, red: -2,
          msg: "Tu firma ya pasó por un regulador sin rasguños. Lo cobras, y algunos clientes lo pagan." } },
      ] },
    { id: 19606, por: "Mostraste lo que firmaste de un juicio perdido", t: "Una multa con tu nombre",
      x: "El regulador concluye que la opinión debió advertir más. Te multa a ti y a la firma, y la noticia sale en la prensa del sector.",
      o: [
        { t: "Pagar y dar una entrevista explicándolo", d: { cash: -5000, rep: 1, ene: -3,
          msg: "Pagas y explicas. La entrevista sale recortada, pero tu explicación sobrevive en un párrafo." } },
        { t: "Pagar en silencio y esperar que pase", d: { cash: -5000, rep: -3, ene: 1,
          msg: "Pasa, como todo. Tarda dos licitaciones perdidas en pasar." } },
      ] },

    /* ===== consecuencias de 19700 ===== */
    { id: 19701, por: "Le compraste la cartera a un auditor retirado", t: "La mitad de los clientes se va",
      x: "Sin el veterano, varios clientes descubren que cambiar de auditor no era tan difícil. Se van uno tras otro, con mucha educación.",
      o: [
        { t: "Visitar a los que quedan, uno por uno", d: { red: 4, car: 1, ene: -4,
          msg: "Un café por cliente. Ninguno más se va, y aprendes por qué se fueron los otros." } },
        { t: "Bajar honorarios para frenar la fuga", d: { cash: -3000, red: 2, rep: -1,
          msg: "La fuga se frena. Los que se quedan aprendieron que tus precios se negocian." } },
      ] },
    { id: 19702, por: "Le compraste la cartera a un auditor retirado", t: "Un cliente heredado trae sorpresa",
      x: "Revisando a un cliente de la cartera, descubres que el veterano firmó tres años de inventarios sin contarlos ni una vez.",
      o: [
        { t: "Rehacer la auditoría y contárselo al cliente", d: { cri: 4, rep: 3, ene: -5,
          msg: "Cuentas lo que nunca se contó. El cliente escucha con una cara que no sabes leer.",
          luego: [{ en: 1, s: "rep", azar: [{ p: 50, id: 19706, bueno: true }, { p: 50, id: 19707, bueno: false }] }] } },
        { t: "Hacerlo bien desde este año y no mirar atrás", d: { ene: 1, cri: -1, rep: -1,
          msg: "Desde este cierre se cuenta todo. Lo de antes queda donde estaba, firmado por otro." } },
      ] },
    { id: 19703, por: "Le compraste la cartera a un auditor retirado", t: "La cartera paga sola",
      x: "Pasó el primer ciclo completo y casi todos renovaron. Ingresos que llegan en cada cierre, sin pitch y sin licitación.",
      o: [
        { t: "Contratar un gerente y delegar", d: { cash: 4000, ene: 4, cri: -1,
          msg: "El gerente atiende y tú revisas. Por primera vez en años, tienes tardes libres." } },
        { t: "Atenderlos en persona para que no se vayan", d: { cash: 6000, red: 3, ene: -5,
          msg: "Cada cliente te ve dos veces al año. Ninguno se va. Tú tampoco te vas de vacaciones." } },
      ] },
    { id: 19704, por: "Te ofrecieron la cartera de un auditor retirado", t: "Una firma grande quiere integrarte",
      x: "Una firma internacional busca crecer en tu plaza y te ofrece integrar tus clientes a los suyos, con permanencia obligada por tres años.",
      o: [
        { t: "Aceptar y quedarte como socio local", d: { cash: 25000, car: 3, red: 2, ene: -3,
          msg: "Firmas. Cambia el logo de las hojas, el sistema de horas y el nombre de quien decide." } },
        { t: "Decir que no: lo tuyo es tuyo", d: { rep: 2, ene: 2, red: -1,
          msg: "Te dan la mano y te dicen que la oferta vence. Tus clientes ni se enteran." } },
      ] },
    { id: 19705, por: "Declinaste la cartera de un auditor retirado", t: "El que compró la cartera no da abasto",
      x: "El colega que se quedó con aquella cartera no da abasto y te ofrece pasarte una parte, ya revisada y a buen precio.",
      o: [
        { t: "Aceptar la parte revisada", d: { cash: -3000, car: 3, ene: -2,
          msg: "Te quedas con los clientes que él ya ordenó. Pagas menos y heredas menos sorpresas." } },
        { t: "Seguir con lo tuyo", d: { ene: 2, cri: 1,
          msg: "Le recomiendas a un colega más joven. Él te debe una, y el colega joven también." } },
      ] },
    { id: 19706, por: "Rehiciste una auditoría heredada", t: "El cliente se queda contigo",
      x: "El cliente agradeció la franqueza, ajustó sus inventarios y renovó por cinco años. Lo cuenta en cada almuerzo de su gremio.",
      o: [
        { t: "Aprovechar el boca a boca", d: { cash: 4000, car: 2, ene: -3,
          msg: "Llegan tres empresas del mismo gremio. Todas quieren al auditor que cuenta inventarios." } },
        { t: "Dejar que el trabajo hable solo", d: { rep: 3, ene: 1,
          msg: "No haces nada. El cliente sigue hablando por ti, que es mejor que hablar tú." } },
      ] },
    { id: 19707, por: "Rehiciste una auditoría heredada", t: "El cliente demanda al veterano",
      x: "El cliente demanda al auditor jubilado por los años sin contar, y a ti te citan como testigo de lo que encontraste.",
      o: [
        { t: "Declarar con tus papeles, sin adornos", d: { rep: 3, red: -3, ene: -3,
          msg: "Dices lo que encontraste y nada más. El veterano no te vuelve a saludar en el colegio." } },
        { t: "Pedir que te excusen por haber comprado la cartera", d: { red: 1, rep: -2,
          msg: "Te excusan por conflicto de interés. El cliente lo toma como que elegiste bando." } },
      ] },
  ],

  opciones: [
    { escena: 102, t: "Conciliar la caja contra los bancos antes que todo", d: { cri: 6, mod: 2, ene: -5,
      msg: "Cuadras caja contra extractos y aparecen dos cuentas que nadie mencionó. Para lo demás, ya no te alcanza el tiempo." } },
    { escena: 42, t: "Fijar un umbral de importancia y aplicarlo a todos", d: { cri: 5, rep: 3, red: -3,
      msg: "Suben tres hallazgos de ocho, sin excepciones. Dos del equipo sienten que el suyo era el importante." } },
    { escena: 23, t: "Remedir partida por partida lo que está en dólares", d: { mod: 4, cri: 4, car: 2, ene: -6,
      msg: "Separas lo que de verdad está en dólares de lo que solo lo parece. Tardas el doble y tu balance es el único que cuadra." } },
    { escena: 29, t: "Entregarlo con índice y referencias, como un auditor", d: { rep: 5, cri: 3, ene: -5, red: -2,
      msg: "Les entregas los papeles como te gustaría recibirlos. Terminan en dos días, y uno pregunta, con recelo, quién te enseñó." } },
  ],

  finales: [
    { id: "l9_cuadra", huellas: ["l9_rastreaste", "l9_salvedad"], t: "El número que no cuadra",
      x: "Rastreaste partidas que todos daban por buenas y firmaste con salvedad cuando nadie quería leerla. Ganaste menos que otros y te creyeron más que a nadie." },
    { id: "l9_creativo", huellas: ["l9_creativo", "l9_firmaste_limpio"], t: "Contabilidad creativa",
      x: "Le moviste la fecha a un contrato y firmaste limpio con un juicio encima. Los números siempre te cuadraron a tiempo. Lo demás fue cuadrando a plazos." },
  ],
};
