/* Lote 7: escenas de oficina. Ids 17000-17999, prefijo l7_. */
module.exports = {
  huellas: {
    l7_dolares_al_vuelo: "Moviste tus ahorros el mismo día del control cambiario",
    l7_cambista: "Te metiste a cambiar dólares para otros",
    l7_emigraste: "Te mudaste a Miami por un trabajo",
    l7_te_quedaste: "Rechazaste Miami para quedarte con tu red",
    l7_socio_de_cena: "Compraste una empresa con alguien de una cena",
    l7_plata_ajena: "Te pusiste a manejar el dinero de un amigo",
    l7_el_del_no: "Le dijiste que no al comité y tuviste razón",
    l7_la_que_triplico: "Dejaste pasar la empresa que triplicó",
    l7_maestro: "Formaste a un analista que ahora decide solo",
    l7_divulgador: "Les enseñaste finanzas a tus amigos sin tecnicismos",
  },

  escenas: [
    /* ===== 54: Controles de cambio de un día para otro ===== */
    { id: 17001, por: "Moviste tus ahorros el día del control cambiario", t: "El que te cambió los dólares vuelve a llamar",
      x: "El intermediario de aquella mañana tiene una propuesta: cambiar para otros y quedarte con una comisión. Dice que es fácil y que nadie pregunta.",
      o: [
        { t: "Aceptar: una comisión no le hace daño a nadie", d: { cash: 3000, cri: -3, rep: -2, deja: "l7_cambista",
          msg: "Empiezas con los conocidos de tus conocidos. El dinero entra rápido y en efectivo.",
          luego: [{ en: 1, azar: [{ p: 55, id: 17006 }, { p: 45, id: 17007 }] }] } },
        { t: "Rechazarlo con educación", d: { cri: 3, red: -1, msg: "Le dices que no es lo tuyo. Te desea suerte con un tono que no te gusta." } },
        { t: "Pasarle clientes sin meterte tú", d: { red: 2, cash: 800, rep: -1, msg: "Le mandas a dos conocidos y te llega una propina. Técnicamente no hiciste nada. Técnicamente." } },
      ] },
    { id: 17002, por: "Moviste tus ahorros el día del control cambiario", t: "El banco quiere saber de dónde salió",
      x: "El banco revisa las cuentas que se movieron aquella semana. Te piden papeles del origen de tus fondos y te dan diez días.",
      o: [
        { t: "Juntar todo y entregarlo ordenado", d: { ene: -4, cri: 2, rep: 2, msg: "Tres noches buscando recibos viejos. Lo entregas completo y no vuelven a llamar." } },
        { t: "Pagarle a un gestor que lo resuelva", d: { cash: -1500, ene: 1, msg: "El gestor cobra caro y entrega a tiempo. Nunca sabrás qué papeles mandó." } },
        { t: "No contestar y esperar que se olviden", d: { rep: -3, cash: -2000, msg: "No se olvidan. Te congelan la cuenta un mes y desbloquearla cuesta una multa y una mañana entera." } },
      ] },
    { id: 17003, por: "Tardaste en mover tus ahorros durante el control", t: "Tus ahorros compran la mitad",
      x: "Un año después del control, lo que guardabas en moneda local alcanza para la mitad. Tu familia empieza a preguntarte qué hacer con lo suyo.",
      o: [
        { t: "Sentarte con tu familia y armar un plan", d: { ene: -3, cri: 3, red: 2, msg: "Una tarde de cuentas en la mesa del comedor. No recuperan lo perdido, pero dejan de perder." } },
        { t: "Admitir que tampoco lo viste venir", d: { rep: -1, cri: 2, red: 1, msg: "Les dices la verdad. Te miran raro un momento y luego te sirven más café." } },
        { t: "Comprar ya lo que ibas a comprar después", d: { cash: -1000, mod: 1, msg: "Adelantas las compras del año que viene. No es una estrategia, pero se le parece." } },
      ] },
    { id: 17004, por: "Pasaste por un control cambiario de un día a otro", t: "Levantan el control sin avisar",
      x: "Tan rápido como llegó, el control se cae. El dólar del mercado paralelo baja a la mitad y todo el mundo hace cuentas de lo que hizo aquel día.",
      o: [
        { t: "Comprar dólares ahora que están baratos", d: { cash: -1000, cri: 2, msg: "Compras una parte. Pagas algo de comisión y duermes mejor la próxima vez que suene la radio." } },
        { t: "Dejar todo como está", d: { ene: 2, msg: "No tocas nada. Ya te movieron bastante el piso este año." } },
        { t: "Escribir lo que aprendiste para la próxima", d: { cri: 4, ene: -2, msg: "Llenas dos páginas de lecciones. La próxima vez, que la habrá, sabrás a quién llamar primero." } },
      ] },
    { id: 17005, por: "Le consultaste a un abogado por el control cambiario", t: "El abogado necesita a alguien con números",
      x: "El abogado que consultaste te llama. Tiene clientes perdidos con la norma nueva y necesita a alguien que les haga las cuentas.",
      o: [
        { t: "Trabajar con él por honorarios", d: { cash: 3000, ene: -4, red: 3, msg: "Pasas las noches haciendo números ajenos. Cobras bien y conoces a media docena de empresarios asustados." } },
        { t: "Recomendarle a un colega", d: { red: 2, msg: "Le pasas el nombre de un colega. Los dos te deben un favor." } },
        { t: "Decirle que no tienes tiempo", d: { ene: 2, red: -1, msg: "No lo tienes, y es verdad. Él consigue a otro en una tarde." } },
      ] },
    { id: 17006, por: "Te metiste a cambiar dólares para otros", t: "El banco pregunta por unos depósitos",
      x: "Tu cuenta tiene más movimientos de los que explica tu sueldo. El banco te cita y el ejecutivo ya no sonríe como antes.",
      o: [
        { t: "Contar la verdad y cerrar el negocio", d: { cash: -3000, rep: -3, cri: 3, msg: "Pagas una multa, cierras el negocio y quedas en la lista de clientes a vigilar. Podría haber sido peor." } },
        { t: "Inventar una explicación creíble", d: { rep: -6, cash: -5000, msg: "La explicación no aguanta la segunda pregunta. Te cierran la cuenta y la noticia llega a tu oficina." } },
        { t: "Contratar un abogado antes de ir", d: { cash: -4000, rep: -1, ene: -3, msg: "El abogado convierte la cita en un trámite. Te cuesta lo que ganaste en tres meses de comisiones." } },
      ] },
    { id: 17007, por: "Te metiste a cambiar dólares para otros", t: "El negocio de los dólares se acaba solo",
      x: "Levantan el control y el mercado paralelo deja de existir de un día para otro. Tus clientes ya no te necesitan.",
      o: [
        { t: "Cerrar y guardar lo ganado", d: { cash: 2000, cri: 2, msg: "Te retiras con la ganancia y sin preguntas. De esas salidas hay pocas." } },
        { t: "Buscar otro negocio con los mismos clientes", d: { red: 3, rep: -2, ene: -2, msg: "Los contactos sirven para otras cosas. Algunas de esas cosas preferirías no saberlas." } },
      ] },

    /* ===== 55: Te ofrecen una visa de trabajo ===== */
    { id: 17051, empleado: true, por: "Te mudaste a Miami por un trabajo", t: "En Miami nadie te devuelve las llamadas",
      x: "Seis meses en la firma nueva y tu agenda de allá no sirve aquí. Te tratan bien, pero nadie te invita a las reuniones que importan.",
      o: [
        { t: "Ir a todos los eventos del sector", d: { ene: -5, red: 5, cash: -1000, msg: "Desayunos, cocteles, conferencias. A la décima tarjeta que das, alguien por fin se acuerda de tu nombre." } },
        { t: "Encerrarte a ser el mejor del equipo", d: { mod: 4, car: 3, red: -1, msg: "Tus modelos son los más limpios del piso. Lo notan. Las reuniones siguen sin invitarte." } },
        { t: "Proponer cubrir a los clientes de tu país", d: { car: 2, red: 2,
          msg: "Escribes la propuesta en una noche. Tu jefe la lee dos veces y dice que lo va a pensar.",
          luego: [{ en: 1, s: "red", azar: [{ p: 55, id: 17056, bueno: true }, { p: 45, id: 17057, bueno: false }] }] } },
      ] },
    { id: 17052, empleado: true, por: "Te mudaste a Miami por un trabajo", t: "El que te trajo se va de la firma",
      x: "El jefe que te contrató se va a la competencia y quiere llevarte. La firma te pide que te quedes y promete revisar tu sueldo.",
      o: [
        { t: "Irte con él", d: { car: 3, red: -2, cash: 2000, msg: "Cambias de edificio y de tarjeta. Él te presenta como su gente, que es bueno y es malo." } },
        { t: "Quedarte en la firma", d: { rep: 3, cash: 1000, msg: "Te quedas. La revisión de sueldo llega más corta de lo prometido y más larga de lo que temías." } },
        { t: "Usar la oferta para negociar", d: { cash: 3000, rep: -3, msg: "Consigues el aumento. También la fama de tener siempre otra oferta en el bolsillo." } },
      ] },
    { id: 17053, empleado: true, por: "Te mudaste a Miami por un trabajo", t: "Un cliente de tu país te busca afuera",
      x: "Un empresario que conocías de allá quiere sacar parte de su dinero del país. No conoce a nadie aquí, salvo a ti.",
      o: [
        { t: "Traerlo a la firma", d: { car: 4, rep: 2, msg: "Lo presentas en el comité como cliente tuyo. Por primera vez te sientas en la cabecera de una reunión." } },
        { t: "Atenderlo tú, por fuera de la firma", d: { cash: 3000, rep: -3, cri: -2, msg: "Cobras por fuera y sale bien, hasta que el área de cumplimiento pregunta por qué ese cliente te tutea." } },
        { t: "Recomendarle a otro asesor", d: { red: 2, msg: "Le pasas un nombre de confianza. No ganas nada hoy y él no se olvida." } },
      ] },
    { id: 17054, empleado: true, por: "Rechazaste Miami para quedarte con tu red", t: "La firma de Miami vuelve a escribir",
      x: "Un año después, la misma firma insiste. El sueldo es menor que el de antes, el cargo es más alto y aquí las cosas están más apretadas.",
      o: [
        { t: "Aceptar esta vez", d: { car: 4, red: -4, ene: -3, cash: 2000, deja: "l7_emigraste", msg: "Haces las maletas con un año de retraso. La red que defendiste se queda aquí, esperándote o no." } },
        { t: "Decir que no otra vez", d: { red: 2, rep: 1, msg: "Les das las gracias. Esta vez no te escriben para insistir." } },
        { t: "Enseñarle la oferta a tu jefe", d: { cash: 2000, rep: -2, car: 1, msg: "Tu jefe iguala parte de la oferta. Desde ese día te mira como a alguien con la maleta hecha." } },
      ] },
    { id: 17055, por: "Rechazaste Miami para quedarte con tu red", t: "Tu red te devuelve el favor",
      x: "Un contacto de años te trae un negocio que no le enseñó a nadie más. Dice que te lo trae a ti porque tú no te fuiste.",
      o: [
        { t: "Estudiarlo con calma", d: { cri: 3, cash: 2500, red: 2, msg: "Te tomas dos semanas. El negocio aguanta la revisión y tu contacto agradece que no lo apuraras." } },
        { t: "Cerrarlo rápido antes que otro", d: { cash: 4000, cri: -2, rep: -1, msg: "Cierras en tres días. Sale bien, aunque dos detalles del contrato los descubres después." } },
        { t: "Pasárselo a alguien que sepa más del tema", d: { red: 3, rep: 2, msg: "Lo refieres a quien de verdad conoce el sector. Ahora te deben dos personas en vez de una." } },
      ] },
    { id: 17056, empleado: true, por: "Propusiste cubrir a los clientes de tu país", t: "La mesa latinoamericana es tuya",
      x: "La firma aprueba tu propuesta y te pone a cargo de los clientes de la región. Por fin tu agenda de allá vale algo aquí.",
      o: [
        { t: "Armar el equipo con gente de allá", d: { red: 4, car: 3, ene: -3, msg: "Contratas a dos conocidos de tu país. Hablan tu idioma y conocen a los clientes por su apodo." } },
        { t: "Hacerlo todo tú al principio", d: { car: 4, ene: -6, cash: 2000, msg: "Viajas cada mes y duermes en aviones. Los números salen y tu espalda lo cobra." } },
      ] },
    { id: 17057, empleado: true, por: "Propusiste cubrir a los clientes de tu país", t: "Tu idea la ejecuta otro",
      x: "La firma aprueba la mesa latinoamericana y se la da a alguien con más años. A ti te piden que le pases tus contactos.",
      o: [
        { t: "Pasarle los contactos y colaborar", d: { red: 2, rep: 2, car: -1, msg: "Le das la agenda. Él te menciona en cada reunión, que no es lo mismo que el cargo." } },
        { t: "Pasarle los nombres y no los teléfonos", d: { rep: -3, red: 1, msg: "Él se da cuenta a la segunda semana. Tu jefe, a la tercera." } },
        { t: "Ofrecerle la idea a otra firma", d: { car: 2, ene: -3, red: -1, msg: "Mandas la propuesta a dos firmas rivales. Una contesta. La otra le cuenta a tu jefe." } },
      ] },

    /* ===== 56: Un socio del club te presenta a alguien ===== */
    { id: 17101, por: "Saludaste a media sala en una cena del club", t: "Uno de la cena se acuerda de ti",
      x: "Uno de los doce de aquella cena te escribe. Tú no recuerdas bien de qué hablaron, pero él sí, y quiere verte.",
      o: [
        { t: "Ir al café y escuchar", d: { red: 3, cash: 1500, ene: -2, msg: "Busca una segunda opinión sobre una compra y está dispuesto a pagarla. Te llevas el encargo." } },
        { t: "Mandarle tu presentación y ya", d: { car: 1, red: -1, msg: "Le mandas un documento de veinte páginas. Contesta con un pulgar arriba y nada más." } },
        { t: "Fingir que también te acuerdas", d: { red: 1, rep: -2, msg: "Lo saludas como a un viejo amigo. A los cinco minutos queda claro que lo confundes con otro." } },
      ] },
    { id: 17102, por: "Te quedaste con una conversación larga en el club", t: "Tu compañero de cena quiere comprar algo",
      x: "Aquel con quien hablaste toda la noche quiere comprar una empresa pequeña. Busca un socio que sepa de números y ponga algo de capital.",
      o: [
        { t: "Entrar con tu dinero", d: { cash: -6000, red: 3, deja: "l7_socio_de_cena",
          msg: "Pones tus ahorros y firmas. Él pone el resto y la confianza de una noche larga.",
          luego: [{ en: 2, s: "cri", azar: [{ p: 45, id: 17106, bueno: true }, { p: 55, id: 17107, bueno: false }] }] } },
        { t: "Entrar solo como asesor, por honorarios", d: { cash: 2500, cri: 2, msg: "Le haces los números y cobras. Si sale bien, te alegras. Si sale mal, también cobraste." } },
        { t: "Decir que no por ahora", d: { red: -1, ene: 1, msg: "Le dices que no es buen momento. Te contesta que nunca lo es y que te avisará de la próxima." } },
      ] },
    { id: 17103, por: "Conversaste en una cena de gente con capital", t: "Una frase tuya circula por el club",
      x: "Algo que dijiste en aquella cena se repite en el club. Lo citan como tuyo, y no siempre bien.",
      o: [
        { t: "Aclarar lo que dijiste de verdad", d: { rep: 2, red: -1, msg: "Lo explicas en el siguiente almuerzo. La frase pierde gracia y gana precisión." } },
        { t: "Dejar que circule", d: { rep: 2, red: 2, cri: -1, msg: "La versión exagerada es más memorable que la tuya. Te presentan como el de la frase." } },
        { t: "Escribir una columna con la idea completa", d: { rep: 4, ene: -3, msg: "La columna sale en un portal del sector. La lee menos gente que la que repetía la frase, pero mejor gente." } },
      ] },
    { id: 17104, por: "Te fuiste temprano de una cena del club", t: "Lo que se cerró después de que te fuiste",
      x: "La operación de la que se habló aquella noche se cerró. Entraron los que se quedaron hasta el final. Tú dormiste ocho horas.",
      o: [
        { t: "Llamar al organizador y pedir la próxima", d: { red: 2, rep: -1, msg: "Te dice que claro, que te avisa. Lo dice como quien lo ha dicho muchas veces." } },
        { t: "Aceptar que no todo es para ti", d: { ene: 3, cri: 1, msg: "Dormir ocho horas también es una inversión. Rinde menos, pero no se cae." } },
        { t: "Ir a la próxima cena y quedarte al final", d: { red: 4, ene: -4, msg: "La próxima vez apagas la luz con los últimos. Sales con dos teléfonos nuevos y ojeras." } },
      ] },
    { id: 17105, por: "Fuiste a una cena del club con gente de capital", t: "Uno de la cena está investigado",
      x: "Uno de los doce de aquella cena está investigado por fraude. Los que hicieron negocios con él andan nerviosos. Te preguntas qué tan cerca estuviste.",
      o: [
        { t: "Revisar si le prometiste algo", d: { cri: 3, ene: -2, msg: "Repasas correos y mensajes. Le diste tu tarjeta y nada más. Respiras." } },
        { t: "Ayudar a los conocidos afectados", d: { red: 3, ene: -3, rep: 1, msg: "Les ayudas a ordenar papeles. Nadie olvida quién apareció cuando las cosas se pusieron feas." } },
        { t: "Contar la historia en cada almuerzo", d: { red: 1, rep: -3, msg: "La cuentas tan seguido que alguien empieza a preguntarse por qué sabes tanto." } },
      ] },
    { id: 17106, por: "Compraste una empresa con alguien de una cena", t: "La empresa reparte sus primeras ganancias",
      x: "La empresa que compraron juntos cerró su segundo año con ganancias. Tu socio propone repartir y tú tienes que votar.",
      o: [
        { t: "Repartir y cobrar", d: { cash: 8000, red: 2, msg: "Cobras tu parte. Por primera vez el dinero que pusiste te devuelve algo sin pedir nada." } },
        { t: "Reinvertir para crecer", d: { cash: 2000, cri: 2, car: 1, msg: "Votas por crecer. Cobras poco hoy y la empresa abre un segundo local." } },
      ] },
    { id: 17107, por: "Compraste una empresa con alguien de una cena", t: "La empresa pide más capital",
      x: "La empresa que compraron juntos no despega. Tu socio dice que con otra ronda de dinero lo logran y te pide poner tu parte.",
      o: [
        { t: "Poner tu parte otra vez", d: { cash: -4000, ene: -3, msg: "Pones más. La empresa sobrevive otro año y tu socio te llama a las once de la noche con más ideas." } },
        { t: "No poner más aunque tu parte se achique", d: { cash: -1000, red: -2, cri: 2, msg: "Tu parte se encoge. Duele menos que seguir llenando un balde con agujeros." } },
        { t: "Venderle tu parte al socio con descuento", d: { cash: 3000, red: -3, msg: "Te compra por la mitad de lo que pusiste. Salen como amigos, más o menos." } },
      ] },

    /* ===== 60: La pizarra del comité ===== */
    { id: 17151, empleado: true, por: "Saliste al pizarrón del comité sin preparar", t: "El socio te llama otra vez al pizarrón",
      x: "En el comité de este mes, el socio te señala delante de todos y te pide que les expliques un concepto a los nuevos.",
      o: [
        { t: "Hacerlo de memoria", d: { rep: 3, cri: 1, msg: "Lo explicas en dos minutos y sin tropezar. Algún nuevo lo apunta palabra por palabra." } },
        { t: "Hacerlo con un caso real del equipo", d: { rep: 4, cri: 3, ene: -2, msg: "Usas una operación de la casa como ejemplo. El socio asiente, que en él es casi un aplauso." } },
        { t: "Pedir que lo haga otro esta vez", d: { rep: -2, ene: 2, msg: "El socio arquea una ceja y señala a otro. No te vuelve a llamar en un buen tiempo." } },
      ] },
    { id: 17152, empleado: true, por: "Saliste al pizarrón del comité sin preparar", t: "Te ganaste un apodo en la oficina",
      x: "Desde lo del pizarrón te dicen «el del pizarrón». Algunos lo dicen con cariño y otros con algo menos que cariño.",
      o: [
        { t: "Tomarlo con humor", d: { red: 3, msg: "Te ríes primero. El apodo dura una semana más y luego se gasta solo." } },
        { t: "Pedir que paren", d: { rep: -1, red: -1, msg: "Lo pides en serio. Paran delante de ti." } },
        { t: "Ofrecer repasos los viernes", d: { rep: 3, red: 2, ene: -3, msg: "Empiezas a dar repasos de media hora. Va gente. El apodo cambia de tono." } },
      ] },
    { id: 17153, empleado: true, por: "Pediste estudiar la pizarra y volver al otro día", t: "Tus apuntes circulan por el piso",
      x: "La hoja que armaste para estudiar aquella noche te la pidió un compañero. Ahora la tiene medio piso y nadie sabe de quién es.",
      o: [
        { t: "Ponerle tu nombre y mejorarla", d: { rep: 4, ene: -3, mod: 1, msg: "Sacas una versión mejor con tu nombre abajo. El socio la ve en el escritorio de un pasante y pregunta quién la hizo." } },
        { t: "Dejar que corra sin firma", d: { red: 2, msg: "Te da igual. A ti te sirvió y a ellos también." } },
        { t: "Pedir que no la compartan más", d: { rep: -2, red: -2, msg: "Lo pides por correo a todo el piso. La hoja sigue circulando, ahora con fama de prohibida." } },
      ] },
    { id: 17154, empleado: true, por: "Pediste estudiar la pizarra y volver al otro día", t: "Te dejaron fuera de la presentación grande",
      x: "El socio arma el equipo para una presentación con un cliente importante. Elige a los que respondieron rápido aquel día. Tú no estás.",
      o: [
        { t: "Pedirle un lugar directamente", d: { car: 1, rep: -1, msg: "Te escucha y te deja de suplente. Llevas el café y miras." } },
        { t: "Preparar un análisis por tu cuenta y mandarlo", d: { mod: 3, ene: -4,
          msg: "Pasas dos noches armando un anexo que nadie te pidió. Se lo mandas al socio sin comentario.",
          luego: [{ en: 1, s: "mod", azar: [{ p: 50, id: 17155, bueno: true }, { p: 50, id: 17156, bueno: false }] }] } },
        { t: "Aceptarlo y seguir con lo tuyo", d: { ene: 2, msg: "Habrá otras. Mientras tanto, nadie te pide nada a medianoche." } },
      ] },
    { id: 17155, empleado: true, por: "Mandaste al socio un análisis que nadie te pidió", t: "El socio usó tu análisis",
      x: "En la presentación, el socio proyecta tu anexo y lo explica como si fuera suyo. Al salir, te pide que vayas a la próxima.",
      o: [
        { t: "Ir y no decir nada del anexo", d: { car: 3, rep: 2, msg: "Vas. Nadie sabe que el anexo era tuyo salvo el socio, y es el único que importa." } },
        { t: "Decirle que te habría gustado presentarlo", d: { car: 2, rep: 1, red: -1, msg: "Te dice que la próxima la presentas tú. Lo cumple a medias." } },
      ] },
    { id: 17156, empleado: true, por: "Mandaste al socio un análisis que nadie te pidió", t: "Tu análisis se quedó en la bandeja",
      x: "El socio nunca contesta el correo. Meses después ves el archivo sin abrir en la carpeta compartida.",
      o: [
        { t: "Aprender a preguntar antes de hacer", d: { cri: 3, ene: 1, msg: "La próxima vez preguntas primero. Te ahorras dos noches y un orgullo herido." } },
        { t: "Reenviarlo con otro asunto", d: { rep: -1, car: 1, msg: "Lo reenvías. Esta vez lo abre, lo lee en diagonal y te da las gracias." } },
      ] },

    /* ===== 61: Rotar entre activos ===== */
    { id: 17201, por: "Rotaste entre activos durante todo un año", t: "El peaje de tanto movimiento",
      x: "Llega el estado de cuenta anual. Entre comisiones e impuestos por cada venta, se fue una tajada que no habías contado.",
      o: [
        { t: "Pagarle a un contador para ordenarlo", d: { cash: -1500, cri: 2, msg: "El contador lo ordena y te devuelve algo en impuestos. Menos de lo que cobra, pero algo." } },
        { t: "Cambiarte a un intermediario más barato", d: { cash: 1000, cri: 1, msg: "Mueves la cuenta a una plataforma que cobra la mitad. Lo que no cambia es lo que haces con ella." } },
        { t: "Seguir igual, que lo importante es acertar", d: { cash: -2000, mod: 1, msg: "Sigues rotando. Los peajes siguen llegando, puntuales como el alquiler." } },
      ] },
    { id: 17202, por: "Rotaste entre activos durante todo un año", t: "Vives pegado a la pantalla",
      x: "Revisas cotizaciones en la cena, en el ascensor y a medianoche. Duermes peor y no tienes claro si ganas más.",
      o: [
        { t: "Borrar la aplicación del teléfono", d: { ene: 5, cash: -500, msg: "Los primeros días buscas el ícono que ya no está. Luego duermes." } },
        { t: "Ponerte reglas y horarios", d: { cri: 3, ene: 2, msg: "Miras dos veces al día y punto. Te pierdes alguna subida y también alguna caída." } },
        { t: "Seguir así, que esto es el oficio", d: { ene: -5, mod: 2, msg: "Conoces cada movimiento del mercado y ninguno de tu cuerpo. El café ya no te hace nada." } },
      ] },
    { id: 17203, por: "Rotaste entre activos durante todo un año", t: "Un amigo quiere que le muevas su dinero",
      x: "Te vio moviéndote todo el año y cree que sabes algo. Quiere que hagas lo mismo con sus ahorros.",
      o: [
        { t: "Aceptar y manejárselo", d: { red: 2, ene: -3, deja: "l7_plata_ajena",
          msg: "Te da acceso a su cuenta. Desde ese día miras dos pantallas y duermes la mitad.",
          luego: [{ en: 1, azar: [{ p: 45, id: 17206 }, { p: 55, id: 17207 }] }] } },
        { t: "Decirle que no", d: { cri: 3, red: -1, msg: "Le dices que con dinero de amigos no. Se ofende un poco y luego entiende." } },
        { t: "Enseñarle a hacerlo él", d: { red: 2, ene: -2, cri: 1, msg: "Tres tardes de clases. Termina en un fondo que copia al mercado, que es lo que le habrías dicho al principio." } },
      ] },
    { id: 17204, por: "Te quedaste quieto en tu cartera todo un año", t: "Una caída fuerte y tú sin tocar nada",
      x: "A mitad de año el mercado cae fuerte. Tu cartera baja un tercio y todos a tu alrededor venden.",
      o: [
        { t: "Aguantar sin mirar", d: { cri: 3, ene: -3, cash: 2000, msg: "Aguantas con los dientes apretados. Un año después estás casi donde empezaste, que ya es ganar." } },
        { t: "Vender para dormir tranquilo", d: { cash: -3000, ene: 3, msg: "Vendes cerca del fondo. Duermes bien la primera semana y mal cuando ves el rebote." } },
        { t: "Comprar más con lo que tenías guardado", d: { cash: 4000, cri: 2, ene: -4, msg: "Compras con el estómago revuelto. La recuperación tarda, pero cuando llega te lleva más lejos." } },
      ] },
    { id: 17205, por: "Te quedaste quieto en tu cartera todo un año", t: "La cartera aburrida ganó",
      x: "Haces cuentas con amigos del sector. Tu cartera quieta le ganó a la de casi todos los que pasaron el año comprando y vendiendo.",
      o: [
        { t: "Contarlo en la próxima reunión", d: { rep: 2, red: -1, msg: "Lo cuentas con falsa modestia. Nadie te lo perdona del todo." } },
        { t: "Subir lo que apartas cada mes", d: { cri: 3, ene: 1, msg: "Pones más en lo mismo. Aburrido, constante, eficaz." } },
        { t: "No decir nada", d: { ene: 2, cri: 1, msg: "Te lo guardas. La mejor estrategia es la que nadie te pide explicar." } },
      ] },
    { id: 17206, por: "Te pusiste a manejar el dinero de un amigo", t: "A tu amigo le fue mejor que a ti",
      x: "Cierras el año y la cuenta de tu amigo rindió más que la tuya. Él está feliz y quiere poner más.",
      o: [
        { t: "Aceptar más dinero", d: { red: 3, ene: -3, cash: 1000, msg: "Aceptas. Te invita a cenar y te presenta a su cuñado, que también tiene ahorros." } },
        { t: "Devolverle el manejo ahora que va bien", d: { cri: 3, red: 1, msg: "Le devuelves la cuenta en su mejor momento. No entiende por qué, y es justo por eso." } },
      ] },
    { id: 17207, por: "Te pusiste a manejar el dinero de un amigo", t: "Le hiciste perder dinero a tu amigo",
      x: "Un mal trimestre y la cuenta de tu amigo pierde una buena parte. No te reclama, pero ya no te escribe como antes.",
      o: [
        { t: "Reponerle una parte de tu bolsillo", d: { cash: -3000, red: 2, rep: 1, msg: "Le devuelves una parte. Lo acepta en silencio y la amistad sobrevive, con una cicatriz." } },
        { t: "Explicarle que así son los mercados", d: { red: -3, cri: 1, msg: "Tienes razón y no sirve de nada. Te pide que le devuelvas el acceso a su cuenta." } },
        { t: "Devolverle el manejo y pedir perdón", d: { red: -1, ene: 2, msg: "Le devuelves todo y te disculpas. Te dice que no pasa nada, y pasa un poco." } },
      ] },

    /* ===== 62: El tablero de la negociación ===== */
    { id: 17251, por: "Cerraste un acuerdo con una contraparte difícil", t: "La contraparte quiere reabrir el acuerdo",
      x: "Un año después de firmar, la otra parte dice que los términos ya no le sirven y pide reabrir dos cláusulas.",
      o: [
        { t: "Negarte: está firmado", d: { rep: 2, red: -3, msg: "Les recuerdas que hay una firma. Cumplen el contrato al pie de la letra y ni una coma más." } },
        { t: "Reabrir a cambio de algo nuevo", d: { cri: 3, cash: 1500, ene: -2, msg: "Cedes las dos cláusulas y te llevas una tercera que te importaba más. Todos salen creyendo que ganaron." } },
        { t: "Ceder para cuidar la relación", d: { red: 3, cash: -2000, msg: "Cedes. Te lo agradecen con un almuerzo y te lo pedirán otra vez el año que viene." } },
      ] },
    { id: 17252, por: "Llevaste tú una negociación de cuatro sesiones", t: "Otra empresa quiere que negocies por ella",
      x: "Alguien de la otra mesa se quedó con tu nombre. Su empresa tiene una negociación difícil y busca a alguien que aguante cuatro sesiones.",
      o: [
        { t: "Aceptar el encargo", d: { cash: 3000, ene: -4,
          msg: "Aceptas. Otra mesa, otras concesiones y la misma sensación de jugar ajedrez con sueño.",
          luego: [{ en: 1, s: "cri", azar: [{ p: 50, id: 17255, bueno: true }, { p: 50, id: 17256, bueno: false }] }] } },
        { t: "Recomendar a alguien con más experiencia", d: { red: 2, rep: 1, msg: "Les pasas el nombre de una negociadora veterana. Ella te debe una y tú lo anotas." } },
        { t: "Decir que no tienes tiempo", d: { ene: 2, msg: "No lo tienes. Ellos encuentran a otro y tú duermes." } },
      ] },
    { id: 17253, por: "Mandaste una propuesta cerrada y no negociaste", t: "Te enteras de cuánto habrían cedido",
      x: "Un abogado de la contraparte, con dos copas encima, te cuenta que habrían aceptado condiciones bastante mejores para ti.",
      o: [
        { t: "Reírte y anotarlo", d: { cri: 3, msg: "Te ríes con él. Al llegar a casa escribes en una libreta: la próxima vez, negocia." } },
        { t: "Intentar reabrir el acuerdo", d: { rep: -3, red: -2, msg: "Llamas al día siguiente. Del otro lado nadie recuerda esa conversación ni a ese abogado." } },
        { t: "Contárselo a tu equipo como lección", d: { rep: 1, red: 1, cri: 1, msg: "Lo cuentas el lunes. Nadie vuelve a mandar una propuesta cerrada sin pensarlo dos veces." } },
      ] },
    { id: 17254, por: "Cerraste un acuerdo con una contraparte difícil", t: "La relación quedó fría",
      x: "Firmaron, pero del otro lado ya nadie te contesta rápido. Cada pedido menor se vuelve una negociación propia.",
      o: [
        { t: "Invitarlos a almorzar", d: { red: 3, cash: -500, msg: "Un almuerzo largo y sin agenda. Al postre, uno de ellos admite que se sintieron atropellados." } },
        { t: "Dejar todo por escrito", d: { cri: 2, ene: -2, msg: "Cada pedido va por correo con copia. Funciona y es tan cálido como suena." } },
        { t: "Quejarte con sus jefes", d: { rep: -2, red: -3, msg: "Te contestan más rápido y con menos ganas. Perdiste a quien te avisaba de los problemas." } },
      ] },
    { id: 17255, por: "Negociaste por encargo de otra empresa", t: "La segunda mesa sale mejor",
      x: "Aprendiste de la primera. Esta vez cierras en tres sesiones y con el centro del tablero de tu lado.",
      o: [
        { t: "Cobrar y volver a lo tuyo", d: { cash: 3000, rep: 3, msg: "Cobras el bono por resultado. Te llegan dos llamadas más en un mes." } },
        { t: "Ofrecerte como negociador fijo", d: { car: 3, ene: -4, red: 2, msg: "Te contratan para todas sus mesas del año. Mucha gente cree ahora que es lo único que haces." } },
      ] },
    { id: 17256, por: "Negociaste por encargo de otra empresa", t: "Apretaste de más y se rompió",
      x: "En la tercera sesión aprietas una cláusula que no hacía falta. La otra parte se levanta de la mesa y no vuelve.",
      o: [
        { t: "Asumirlo ante tu cliente", d: { rep: -2, cri: 3, msg: "Le dices a tu cliente que fue tu error. No te paga el bono, pero te sigue saludando." } },
        { t: "Culpar a la otra parte", d: { rep: -4, red: -2, msg: "Dices que eran imposibles. Tu cliente llama a la otra parte, que cuenta otra versión." } },
      ] },

    /* ===== 63: Cuatro postores por el mismo activo ===== */
    { id: 17301, por: "Pujaste en una subasta de cuatro postores", t: "Los bancos de la subasta te tienen en cuenta",
      x: "Los bancos que llevaban la venta tomaron nota de cómo pujaste. Te llega la invitación a otro proceso antes que a nadie.",
      o: [
        { t: "Entrar sin pensarlo mucho", d: { car: 3, ene: -3, cri: -1, msg: "Dices que sí esa misma tarde. Te gusta que te llamen primero, quizás demasiado." } },
        { t: "Estudiarlo con calma antes de decidir", d: { cri: 3, red: 1, msg: "Pides los números y dos semanas. Te las dan, que ya dice algo de cómo te ven." } },
        { t: "Pasar esta vez", d: { red: -1, ene: 2, msg: "Les das las gracias. La siguiente invitación tarda más en llegar." } },
      ] },
    { id: 17302, por: "Estuviste en una subasta de cuatro postores", t: "Sale a la venta otra del mismo sector",
      x: "Otra compañía del mismo sector sale a la venta. Esta vez conoces el sector por dentro gracias a aquella subasta.",
      o: [
        { t: "Pujar con tu propia estimación", d: { cash: -2000, ene: -3,
          msg: "Haces tu número, pagas la revisión de la compañía y metes el sobre. Ahora toca esperar.",
          luego: [{ en: 1, s: "cri", azar: [{ p: 50, id: 17306, bueno: true }, { p: 50, id: 17307, bueno: false }] }] } },
        { t: "Asesorar a otro postor por honorarios", d: { cash: 2500, red: 2, msg: "Otro postor paga por lo que sabes. Si gana, es su problema." } },
        { t: "Dejarla pasar", d: { ene: 2, msg: "Dejas que otros se peleen por ella. Tú miras desde la tribuna." } },
      ] },
    { id: 17303, por: "Te quedaste fuera de una subasta de cuatro postores", t: "El que ganó la subasta pagó de más",
      x: "Un año después, el ganador de aquella subasta ya admitió en sus cuentas que la compañía vale menos. Su comité está furioso.",
      o: [
        { t: "Llamarlo y ofrecerle ayuda", d: { red: 3, ene: -2, msg: "Lo llamas sin ironía. Te lo agradece de verdad y te debe una." } },
        { t: "Decir en el club que lo veías venir", d: { rep: -2, red: -2, msg: "Lo dices con una copa en la mano. Llega a sus oídos antes de que termines la copa." } },
        { t: "Estudiar el caso a fondo", d: { cri: 4, ene: -2, msg: "Desarmas su modelo con los datos públicos. Encuentras el error y te prometes no cometerlo." } },
      ] },
    { id: 17304, por: "Te quedaste fuera de una subasta de cuatro postores", t: "La que dejaste pasar duplicó su valor",
      x: "La compañía por la que no pujaste vale el doble dos años después. El que la compró habla de ella en cada cena.",
      o: [
        { t: "Revisar qué viste mal", d: { cri: 3, ene: -2, msg: "Repasas tu estimación. No estaba mal; él vio algo que tú no. Lo anotas." } },
        { t: "Felicitarlo de verdad", d: { red: 3, msg: "Lo felicitas en la cena. Te cuenta qué vio, que vale más que la envidia." } },
        { t: "Jurarte no dejar pasar la próxima", d: { cri: -2, car: 1, msg: "Te prometes pujar en la siguiente, sea cual sea. Es una promesa peligrosa." } },
      ] },
    { id: 17305, por: "Pujaste en una subasta de cuatro postores", t: "Tu estimación estaba lejos",
      x: "Con los resultados públicos de la compañía, revisas el número que llevaste aquel día. Estabas lejos, y no por poco.",
      o: [
        { t: "Rehacer el modelo para entender el error", d: { mod: 4, cri: 2, ene: -3, msg: "Rehaces todo con los datos reales. Encuentras el supuesto que te traicionó." } },
        { t: "Guardarlo en un cajón", d: { ene: 1, cri: -1, msg: "No quieres saber. El cajón cierra bien." } },
        { t: "Presentarlo como caso de estudio", d: { rep: 1, cri: 2, red: 1, msg: "Lo cuentas delante de tu equipo con tus propios números. Es incómodo y es útil." } },
      ] },
    { id: 17306, por: "Pujaste por otra compañía del mismo sector", t: "Pagaste un precio razonable",
      x: "Ganas esta subasta y, por una vez, no pagaste de más. Los números del primer año se parecen a los tuyos.",
      o: [
        { t: "Celebrarlo con el equipo", d: { rep: 3, red: 2, cash: 3000, msg: "Una cena para el equipo y un bono para ti. El sector empieza a llamarte." } },
        { t: "Volver a revisar antes de celebrar", d: { cri: 3, cash: 3000, msg: "Revisas dos veces. Todo cuadra. Celebras tarde y tranquilo." } },
      ] },
    { id: 17307, por: "Pujaste por otra compañía del mismo sector", t: "Ganaste porque nadie más pagaba tanto",
      x: "Te quedas con la compañía. Al abrir los sobres ves que el segundo ofreció bastante menos. Ganaste, y eso es justo lo que te preocupa.",
      o: [
        { t: "Reconocerlo pronto y ajustar el plan", d: { cri: 3, rep: -1, cash: -3000, msg: "Ajustas expectativas ante tu comité. Te cuesta orgullo y algo de dinero, no la credibilidad." } },
        { t: "Defender el precio a toda costa", d: { rep: -3, cash: -5000, msg: "Lo defiendes un año más. Cuando por fin lo admites, admitirlo sale más caro." } },
      ] },

    /* ===== 940: Media hora antes de que llegue todo el mundo ===== */
    { id: 17351, empleado: true, por: "Usaste las mañanas para estudiar a fondo", t: "El tema de tus mañanas sale en una reunión",
      x: "En una reunión con un cliente sale justo el tema que estudiaste. Todos miran a tu jefe, que no tiene idea.",
      o: [
        { t: "Contestar tú", d: { rep: 4, car: 2, red: -1, msg: "Lo explicas claro. El cliente asiente y tu jefe también, con una sonrisa un poco tiesa." } },
        { t: "Pasarle una nota a tu jefe", d: { red: 3, car: 1, msg: "Le deslizas una nota. Responde con tus palabras y al salir te da las gracias en voz baja." } },
        { t: "Quedarte callado", d: { ene: 1, rep: -1, msg: "Nadie contesta bien. Pasas el resto de la reunión mordiéndote la lengua." } },
      ] },
    { id: 17352, por: "Usaste las mañanas para estudiar a fondo", t: "Ves errores en los modelos de otros",
      x: "Sigues llegando temprano. Ya leíste varios manuales y empiezas a ver errores en modelos ajenos, algunos de gente con más rango.",
      o: [
        { t: "Señalarlos en voz alta", d: { rep: 2, red: -3, cri: 1, msg: "Tienes razón y lo dices en la reunión. La razón no te hace muchos amigos." } },
        { t: "Avisarles en privado", d: { red: 3, cri: 2, msg: "Mandas notas discretas. Te ganas aliados que no sabías que necesitabas." } },
        { t: "Escribir una guía de errores comunes", d: { rep: 4, ene: -4, msg: "Escribes una guía sin nombres. Todos la leen buscando si hablas de ellos." } },
      ] },
    { id: 17353, empleado: true, por: "Adelantaste el trabajo del viernes", t: "Te llegan los urgentes de todo el piso",
      x: "Desde que entregas antes, te pasan los encargos urgentes de todo el piso. Nadie pregunta si tienes tiempo.",
      o: [
        { t: "Sacarlo todo", d: { car: 3, ene: -6,
          msg: "Lo sacas todo. Te ganas fama de máquina, que suena mejor de lo que se siente.",
          luego: [{ en: 1, s: "ene", azar: [{ p: 45, id: 17356, bueno: true }, { p: 55, id: 17357, bueno: false }] }] } },
        { t: "Poner un límite", d: { ene: 3, rep: -1, msg: "Dices que no a dos encargos. Nadie se muere y alguno se molesta." } },
        { t: "Pedir que repartan mejor", d: { red: 2, car: -1, msg: "Lo planteas en la reunión de equipo. Reparten mejor durante dos semanas." } },
      ] },
    { id: 17354, por: "Adelantaste el trabajo del viernes", t: "La pregunta del capítulo que no leíste",
      x: "Un cliente te hace una pregunta técnica que estaba justo en el capítulo del manual que nunca abriste.",
      o: [
        { t: "Improvisar con seguridad", d: { rep: -3, msg: "Suenas convincente. Una semana después el cliente descubre que no era así." } },
        { t: "Decir que lo confirmas y volver con la respuesta", d: { cri: 2, rep: 1, ene: -1, msg: "Esa noche abres el manual por fin. Al día siguiente contestas mejor de lo que habrías improvisado." } },
        { t: "Pasarle la pregunta a un colega", d: { red: 1, rep: -1, msg: "Tu colega contesta bien. El cliente apunta su nombre y no el tuyo." } },
      ] },
    { id: 17356, empleado: true, por: "Sacaste todos los urgentes del piso", t: "Alguien notó quién saca todo",
      x: "En la evaluación de fin de año, tu jefe trae una lista de todo lo que sacaste. Dice que eso no se olvida.",
      o: [
        { t: "Pedir el ascenso ahí mismo", d: { car: 5, rep: 1, msg: "Lo pides sin rodeos. Te dice que sí, para el próximo ciclo. Esta vez lo cumple." } },
        { t: "Pedir menos carga en lugar de más cargo", d: { ene: 5, car: 1, msg: "Pides respirar. Te lo dan, con la promesa de tenerte en cuenta para lo siguiente." } },
      ] },
    { id: 17357, empleado: true, por: "Sacaste todos los urgentes del piso", t: "El cuerpo pasa la cuenta",
      x: "Un lunes no te levantas. El médico dice agotamiento y te manda dos semanas a casa. El piso sobrevive sin ti.",
      o: [
        { t: "Descansar de verdad", d: { ene: 8, car: -2, msg: "Apagas el teléfono. Vuelves con otra cara y con la lección aprendida, al menos por un tiempo." } },
        { t: "Trabajar desde la cama", d: { ene: -3, car: 1, msg: "Contestas correos con fiebre. Nadie te lo agradece y el médico te regaña." } },
      ] },

    /* ===== 941: La certificación ===== */
    { id: 17401, por: "Te presentaste al examen de certificación", t: "Los reclutadores te encuentran",
      x: "Haber pasado por el programa se ve en tu perfil. Tres reclutadores te escriben la misma semana.",
      o: [
        { t: "Ir a las entrevistas por si acaso", d: { red: 3, ene: -3, car: 1, msg: "Vas a dos. No te cambias, pero sales sabiendo cuánto vales afuera." } },
        { t: "Decirles que no estás buscando", d: { ene: 1, msg: "Les contestas con amabilidad. Guardan tu perfil para la próxima." } },
        { t: "Pedirles consejo para el siguiente paso", d: { red: 2, cri: 1, msg: "Uno de ellos te dice con franqueza lo que te falta. Gratis y sin pedir nada a cambio." } },
      ] },
    { id: 17402, por: "Estudiaste los sábados para una certificación", t: "Un colega quiere tus apuntes",
      x: "Un colega se inscribió en el programa y te pide los apuntes de tus sábados. Son seis meses de trabajo en tres cuadernos.",
      o: [
        { t: "Dárselos con una tarde de repaso", d: { red: 4, ene: -2, cri: 1, msg: "Le das los cuadernos y una tarde. Explicándolo te das cuenta de qué se te había olvidado." } },
        { t: "Prestárselos y ya", d: { red: 2, msg: "Te los devuelve con café derramado y un gracias sincero." } },
        { t: "Decirle que los perdiste", d: { red: -2, ene: 1, msg: "Le mientes. Él consigue los de otro y se entera de que tú los tenías." } },
      ] },
    { id: 17403, por: "Estudiaste los sábados para una certificación", t: "Uno del grupo de estudio arma un fondo",
      x: "Del grupo de los sábados salieron amistades. Uno de ellos arma un fondo pequeño y busca inversores que confíen en él.",
      o: [
        { t: "Poner algo de dinero", d: { cash: -4000, red: 3,
          msg: "Pones una parte prudente. Él te lo agradece como si fuera más.",
          luego: [{ en: 2, azar: [{ p: 40, id: 17406 }, { p: 60, id: 17407 }] }] } },
        { t: "Presentarle a gente con capital", d: { red: 4, msg: "Le haces tres presentaciones. Dos no van a nada y una sí." } },
        { t: "Desearle suerte y ya", d: { ene: 1, msg: "Le deseas lo mejor. Lo dices en serio." } },
      ] },
    { id: 17404, por: "Dejaste la certificación para otro año", t: "El puesto pedía la certificación",
      x: "Sale un puesto que te encantaba y pide la certificación como requisito. Lo publicaron el lunes y lo cerraron el viernes.",
      o: [
        { t: "Inscribirte este año, ahora sí", d: { cash: -1500, ene: -4, car: 2, cri: 2, msg: "Te inscribes. Llegará tarde para este puesto y a tiempo para el siguiente." } },
        { t: "Postularte igual", d: { car: 1, rep: -1, msg: "Te contestan con un correo automático. El filtro no lee motivaciones." } },
        { t: "Convencerte de que no lo querías", d: { ene: 2, cri: -1, msg: "A las dos semanas ya te lo crees. Casi." } },
      ] },
    { id: 17405, por: "Dejaste la certificación para otro año", t: "Los sábados son tuyos",
      x: "Mientras otros van a clases, tú tienes los sábados libres. Por primera vez en años, tiempo sin dueño.",
      o: [
        { t: "Armar un proyecto propio", d: { mod: 3, ene: -2, red: 1, msg: "Armas un modelo propio de un sector que te gusta. Nadie te lo pidió y es lo mejor que haces en el año." } },
        { t: "Descansar de verdad", d: { ene: 6, msg: "Duermes, caminas, cocinas. Vuelves los lunes con la cabeza fría." } },
        { t: "Dar clases los sábados", d: { cash: 1500, ene: -3, red: 2, msg: "Preparas a otros para el examen que tú no presentaste. La ironía no se te escapa." } },
      ] },
    { id: 17406, por: "Pusiste dinero en el fondo de un compañero", t: "El fondo de tu compañero despega",
      x: "El fondo pequeño de tu compañero de sábados tuvo dos años muy buenos. Te manda el informe con una nota de agradecimiento.",
      o: [
        { t: "Retirar la ganancia", d: { cash: 7000, red: 1, msg: "Retiras lo ganado y dejas el capital. Él lo entiende y te sigue mandando informes." } },
        { t: "Dejarlo todo adentro", d: { cash: 2000, red: 3, cri: 1, msg: "Lo dejas trabajar. El informe siguiente también es bueno, aunque menos." } },
      ] },
    { id: 17407, por: "Pusiste dinero en el fondo de un compañero", t: "El fondo de tu compañero no arranca",
      x: "Tu compañero no consiguió suficientes inversores. El fondo cierra y devuelve lo que queda, que es menos de lo que pusiste.",
      o: [
        { t: "Recibir lo que queda y agradecer", d: { cash: 2500, red: 2, msg: "Te devuelve una parte con una disculpa. Sigue siendo tu amigo, y eso cuenta." } },
        { t: "Reclamarle por cómo lo manejó", d: { cash: 2500, red: -4, msg: "Le reclamas. Tenías razón en dos cosas y lo perdiste en todas." } },
      ] },

    /* ===== 942: Te toca explicarlo tú ===== */
    { id: 17451, empleado: true, por: "Les diste la charla a los pasantes", t: "Los pasantes vienen a tu escritorio",
      x: "Desde la charla, los pasantes vienen con cada duda. Te quitan una hora al día y te enteras de todo lo que pasa en el piso.",
      o: [
        { t: "Atenderlos a todos", d: { red: 4, ene: -4, msg: "Atiendes a cada uno. Te vuelves el centro de información del piso, sin cargo pero con poder." } },
        { t: "Poner un horario de consulta", d: { cri: 2, red: 1, msg: "Martes y jueves, media hora. Llegan con las dudas mejor pensadas." } },
        { t: "Mandarlos al manual", d: { red: -2, ene: 2, msg: "Les señalas el manual. Dejan de venir y dejas de enterarte." } },
      ] },
    { id: 17452, empleado: true, por: "Les diste la charla a los pasantes", t: "El socio quiere la charla para un cliente",
      x: "El socio quiere que des una versión de la charla a un cliente grande, en su sala de directorio, con su gente mirando.",
      o: [
        { t: "Aceptar y prepararla de nuevo", d: { ene: -4, rep: 2,
          msg: "Rehaces todo para gente que paga. Ensayas tres veces frente al espejo del baño.",
          luego: [{ en: 1, s: "cri", azar: [{ p: 55, id: 17456, bueno: true }, { p: 45, id: 17457, bueno: false }] }] } },
        { t: "Proponer darla junto al socio", d: { red: 2, rep: 2, msg: "La dan entre los dos. Él cuenta las anécdotas y tú los números." } },
        { t: "Declinar con una excusa", d: { rep: -2, ene: 2, msg: "Dices que tienes un cierre esa semana. El socio no vuelve a pedírtelo." } },
      ] },
    { id: 17453, empleado: true, por: "Le pasaste la charla de los pasantes a un compañero", t: "Tu compañero ya es el que sabe explicar",
      x: "El compañero al que le pasaste la charla ya la dio tres veces. En la oficina lo presentan como el que sabe explicar.",
      o: [
        { t: "Pedirle participar en la próxima", d: { red: 2, rep: 1, msg: "Te deja una parte. El público aplaude a los dos, a él un poco más." } },
        { t: "Dejarlo así", d: { ene: 2, msg: "Es suya ahora. Tú tienes tus propios problemas." } },
        { t: "Recordarle al socio que te la pidió a ti", d: { rep: -3, red: -2, msg: "El socio te mira como quien recuerda algo vagamente. Tu compañero sí lo recuerda, y bien." } },
      ] },
    { id: 17454, empleado: true, por: "Le pasaste la charla de los pasantes a un compañero", t: "Un pasante aprendió mal",
      x: "Un pasante de aquella charla comete un error grande en un modelo. Cuando le preguntan, dice que así se lo explicaron.",
      o: [
        { t: "Sentarte a corregirlo con él", d: { mod: 2, red: 3, ene: -3, msg: "Le explicas lo que la charla se saltó. Aprende rápido y se acuerda de quién lo ayudó." } },
        { t: "Avisarle a tu compañero", d: { red: 1, cri: 1, msg: "Le cuentas a tu compañero. Corrige la charla y te lo agradece de verdad." } },
        { t: "No meterte", d: { ene: 1, rep: -1, msg: "No es tu charla ni tu pasante. El error llega al cliente y nadie sale bien." } },
      ] },
    { id: 17456, empleado: true, por: "Diste la charla del equipo ante un cliente", t: "El cliente pide más",
      x: "Al cliente le gustó tanto la charla que pide que lleves tú la relación con su equipo de finanzas.",
      o: [
        { t: "Aceptar la relación", d: { car: 4, rep: 3, ene: -3, msg: "Pasas a ser la cara del equipo ante ese cliente. El socio lo anuncia en la reunión del lunes." } },
        { t: "Compartirla con el socio", d: { car: 2, red: 3, msg: "Propones llevarla con el socio. Él lo agradece más de lo que esperabas." } },
      ] },
    { id: 17457, empleado: true, por: "Diste la charla del equipo ante un cliente", t: "La sala de directorio te comió",
      x: "A la mitad, el director financiero te interrumpe con una pregunta que no esperabas. Te trabas y el socio tiene que rescatarte.",
      o: [
        { t: "Pedir otra oportunidad", d: { rep: 1, cri: 2, ene: -2, msg: "Te la dan meses después. Esta vez llevas la respuesta a esa pregunta en la primera lámina." } },
        { t: "Dejar las charlas para otros", d: { rep: -2, ene: 2, msg: "Te quedas en el escritorio, que es donde nadie te interrumpe." } },
      ] },

    /* ===== 943: Alguien te pregunta algo básico ===== */
    { id: 17501, por: "Intentaste explicarle sus ahorros a un amigo", t: "Tu amigo trae a sus amigos",
      x: "Tu amigo contó por ahí que te tomaste en serio su pregunta. Ahora tres amigos más quieren sentarse contigo.",
      o: [
        { t: "Armar una tarde para todos", d: { red: 4, rep: 2, ene: -3, deja: "l7_divulgador", msg: "Una tarde, una pizarra y cero palabras técnicas. Salen sabiendo qué preguntar en su banco." } },
        { t: "Atenderlos uno por uno", d: { red: 3, ene: -5, msg: "Cada uno trae su caso y su desorden. Terminas sabiendo más de sus vidas que de sus cuentas." } },
        { t: "Decirles que no eres asesor", d: { cri: 2, red: -1, msg: "Les explicas que no es tu papel. Lo entienden, pero ya no te preguntan nada." } },
      ] },
    { id: 17502, por: "Intentaste explicarle sus ahorros a un amigo", t: "Tu amigo se pasó de entusiasmo",
      x: "Tu amigo tomó lo que hablaron y lo llevó al extremo. Metió todos sus ahorros en un solo lugar, convencido de que entendió.",
      o: [
        { t: "Llamarlo y corregir a tiempo", d: { red: 2, ene: -2, cri: 1, msg: "Lo llamas esa noche. Reparte un poco, a regañadientes, y te dice que eres muy conservador." } },
        { t: "Dejar que aprenda solo", d: { red: -1, cri: 1, msg: "Lo dejas. Cuando la cosa baja, te llama y esta vez escucha todo." } },
        { t: "Explicárselo otra vez, más despacio", d: { red: 3, ene: -3, msg: "Se lo explicas de nuevo con un ejemplo de su propia vida. Ahora sí lo entiende." } },
      ] },
    { id: 17503, por: "Le pasaste a un amigo el nombre de un fondo", t: "El fondo que le pasaste cayó",
      x: "El fondo que le recomendaste perdió una quinta parte este año. Tu amigo te escribe preguntando si debería vender.",
      o: [
        { t: "Explicarle ahora lo que no le explicaste", d: { red: 3, ene: -3, cri: 2, msg: "Te sientas con él una hora. Entiende qué tiene y por qué baja. Decide quedarse, por razones suyas." } },
        { t: "Decirle que aguante", d: { red: -1,
          msg: "Le dices que aguante, sin más. Te hace caso, y ahora el resultado también es tuyo.",
          luego: [{ en: 1, azar: [{ p: 55, id: 17506 }, { p: 45, id: 17507 }] }] } },
        { t: "Decirle que venda", d: { red: -2, cri: -1, msg: "Vende en lo más bajo. Nunca sabrá si fue buena idea, y tú tampoco." } },
      ] },
    { id: 17504, por: "Le pasaste a un amigo el nombre de un fondo", t: "El fondo que le pasaste subió",
      x: "El fondo subió y tu amigo te invita a comer para agradecerte. No sabe por qué subió, y tú no se lo explicaste.",
      o: [
        { t: "Explicárselo ahora, en la comida", d: { red: 3, cri: 1, msg: "Le explicas entre plato y plato. Te pide que le escribas todo, y lo haces." } },
        { t: "Aceptar la comida y el mérito", d: { red: 2, rep: 1, cri: -1, msg: "Aceptas el mérito. Ahora cree que eres un genio, que es peligroso para los dos." } },
        { t: "Advertirle que no siempre será así", d: { cri: 2, red: 1, msg: "Le dices que las subidas no se repiten por cortesía. Asiente sin creerte del todo." } },
      ] },
    { id: 17506, por: "Le dijiste a tu amigo que aguantara", t: "El fondo se recuperó",
      x: "El fondo que tu amigo aguantó volvió a donde estaba y un poco más. Tu amigo cuenta como un gran consejo lo que fue suerte.",
      o: [
        { t: "Confesarle que fue suerte", d: { cri: 3, red: 1, msg: "Le dices la verdad. Se ríe y te cree más que antes." } },
        { t: "Disfrutar el crédito", d: { rep: 2, cri: -2, msg: "Lo dejas creer. Te va a pedir otro consejo, y ese también lo darás sin pensar." } },
      ] },
    { id: 17507, por: "Le dijiste a tu amigo que aguantara", t: "El fondo siguió cayendo",
      x: "El fondo que le dijiste que aguantara siguió bajando otro año. Tu amigo ya no pregunta, solo te manda capturas.",
      o: [
        { t: "Sentarte con él a revisar todo", d: { red: 2, ene: -3, cri: 2, msg: "Revisan juntos qué tiene. Es tarde para lo perdido y temprano para lo que viene." } },
        { t: "Dejar de contestar sus mensajes", d: { red: -5, ene: 1, msg: "Dejas los mensajes en visto. Pierdes el dinero que no era tuyo y el amigo que sí." } },
      ] },

    /* ===== 950: Tres carpetas y un solo cheque ===== */
    { id: 17551, por: "Recomendaste una de tres operaciones al comité", t: "La que recomendaste va por debajo",
      x: "La operación que defendiste tiene su primer año de resultados. Están por debajo del plan, aunque no lejos.",
      o: [
        { t: "Defender el plan original", d: { rep: -1, cri: -1, msg: "Dices que el segundo año lo compensa. Lo apuntan con fecha." } },
        { t: "Proponer ajustes concretos", d: { mod: 3, rep: 2, ene: -3, msg: "Llegas con tres cambios y los números de cada uno. El comité aprueba dos." } },
        { t: "Pedir que otro la revise", d: { cri: 2, rep: -1, red: 1, msg: "Pides ojos frescos. El revisor encuentra lo mismo que tú y lo dice mejor." } },
      ] },
    { id: 17552, por: "Recomendaste una de tres operaciones al comité", t: "La que recomendaste supera el plan",
      x: "La empresa que defendiste crece más rápido de lo previsto. En el comité empiezan a preguntarte a ti primero.",
      o: [
        { t: "Pedir más responsabilidad", d: { car: 4, ene: -2, msg: "Te dan la siguiente operación a cargo. Ahora el éxito y el fracaso llevan tu nombre." } },
        { t: "Darle el crédito al equipo", d: { red: 3, rep: 2, msg: "El equipo sabe lo que hiciste, y eso vale más que el crédito." } },
        { t: "Recordar que un año no es una tendencia", d: { cri: 3, rep: 1, msg: "Le bajas el entusiasmo al comité. Te llaman aguafiestas y te escuchan igual." } },
      ] },
    { id: 17553, por: "Pasaste por el comité de las tres carpetas", t: "Un rival compró una de las descartadas",
      x: "Un fondo rival compró una de las candidatas que tu comité no eligió. Su gente te llama para saber qué viste tú.",
      o: [
        { t: "Contarles lo que viste", d: { red: 3, rep: -3, msg: "Les cuentas. Tu comité se entera y te recuerda, en voz baja, qué es confidencial." } },
        { t: "Decir que no puedes hablar", d: { rep: 2, cri: 1, msg: "Les dices que no. Te respetan más que si les hubieras contado." } },
        { t: "Ofrecerles un café más adelante", d: { red: 2, msg: "Les dices que cuando cierren, con gusto. Te queda un contacto en el fondo rival." } },
      ] },
    { id: 17554, por: "Le dijiste que no al comité y tuviste razón", t: "El comité quiere tu no primero",
      x: "Desde que pasaste de las tres, el comité te manda las carpetas más dudosas antes que a nadie. Quieren oír tu no antes que el sí de otros.",
      o: [
        { t: "Aceptar el papel", d: { rep: 3, car: 3, ene: -3, msg: "Te vuelves el filtro del comité. Te temen un poco, y eso también es respeto." } },
        { t: "Pedir ver también las buenas", d: { car: 2, cri: 1, msg: "Pides que no te encasillen. Te mandan una buena de vez en cuando, como premio." } },
        { t: "Advertir que a veces el no es un error", d: { cri: 3, rep: 1, msg: "Les recuerdas que acertar una vez no te vuelve infalible. Lo anotan y te mandan más." } },
      ] },
    { id: 17555, por: "Dejaste pasar la empresa que triplicó", t: "La broma ya no es tan broma",
      x: "Cada vez que opinas en el comité, alguien menciona la empresa que triplicó. Lo dicen sonriendo, pero lo dicen.",
      o: [
        { t: "Escribir un análisis honesto del error", d: { cri: 4, rep: 2, ene: -3, msg: "Escribes qué viste, qué no viste y por qué. El comité lo usa para entrenar a los nuevos." } },
        { t: "Recomendar la siguiente para compensar", d: { car: 1, cri: -2,
          msg: "La siguiente carpeta la recomiendas sin dudar. Quieres que se olviden de la otra.",
          luego: [{ en: 2, azar: [{ p: 40, id: 17556 }, { p: 60, id: 17557 }] }] } },
        { t: "Ignorar los comentarios", d: { ene: -2, rep: -1, msg: "Haces como que no oyes. Lo oyes." } },
      ] },
    { id: 17556, por: "Recomendaste una operación para compensar un error", t: "Saliste bien de pura suerte",
      x: "La operación que recomendaste para compensar resultó buena. Nadie vuelve a mencionar la otra, y tú sabes por qué elegiste esta.",
      o: [
        { t: "Aprender de todas maneras", d: { cri: 3, msg: "Te prometes no volver a recomendar por miedo. Esta vez el miedo tuvo suerte." } },
        { t: "Cobrarte el crédito", d: { rep: 3, car: 2, cri: -2, msg: "Lo celebras como un acierto aunque sabes que fue revancha." } },
      ] },
    { id: 17557, por: "Recomendaste una operación para compensar un error", t: "El miedo también recomienda mal",
      x: "La operación que recomendaste para que olvidaran la otra va mal. Ahora el comité recuerda las dos.",
      o: [
        { t: "Asumirlo de frente", d: { rep: -2, cri: 4, msg: "Lo dices tal cual: recomendaste por orgullo. El comité valora la honestidad más que tu historial." } },
        { t: "Apartarte del comité por un tiempo", d: { car: -3, ene: 4, msg: "Te apartas un año. Vuelves más callado y con mejor ojo." } },
      ] },

    /* ===== 951: El nuevo analista quiere aprender ===== */
    { id: 17601, por: "Te sentaste a enseñarle al analista nuevo", t: "El analista que formaste presenta solo",
      x: "El joven presenta su primera recomendación en el comité. Usa tus mismas preguntas y en el mismo orden.",
      o: [
        { t: "Dejarlo volar sin intervenir", d: { red: 3, ene: 2, deja: "l7_maestro", msg: "No dices nada en toda la sesión. Al final te busca con la mirada y tú asientes." } },
        { t: "Revisarle todo antes de que presente", d: { cri: 2, red: -2, msg: "Le corriges cada lámina. Presenta tu recomendación con su voz." } },
        { t: "Presentarlo como alumno tuyo", d: { rep: 2, red: -2, msg: "Lo presentas como tu alumno. Él sonríe, y un poco se encoge." } },
      ] },
    { id: 17602, por: "Tuviste a un analista joven a tu cargo", t: "Un rival quiere a tu analista",
      x: "Una firma rival le ofrece el doble al analista joven de tu equipo. Antes de contestar, viene a preguntarte qué harías tú.",
      o: [
        { t: "Aconsejarle que acepte", d: { red: 4, rep: 2, msg: "Le dices que vaya. Se va agradecido y empieza a mandarte negocios desde el otro lado." } },
        { t: "Convencerlo de quedarse", d: { ene: -2, red: 1,
          msg: "Le hablas del largo plazo y de lo que viene. Se queda, por ahora.",
          luego: [{ en: 2, azar: [{ p: 50, id: 17605 }, { p: 50, id: 17606 }] }] } },
        { t: "Darle más responsabilidad para retenerlo", d: { car: 2, ene: -3, red: 2, msg: "Le das su primera operación a cargo. No es el doble de sueldo, pero es otra cosa." } },
      ] },
    { id: 17603, por: "Le mandaste un libro al analista nuevo", t: "El libro no le alcanzó",
      x: "El analista se leyó el libro entero y aun así eligió mal en su primera carpeta. El comité pregunta quién lo supervisa.",
      o: [
        { t: "Asumir que era tu responsabilidad", d: { rep: -1, red: 3, cri: 2, msg: "Dices que es tuyo. El analista no lo olvida y el comité tampoco, para bien." } },
        { t: "Sentarte con él ahora", d: { ene: -3, red: 3, mod: 1, msg: "La media hora que no le diste antes se vuelve una tarde entera. Vale la pena igual." } },
        { t: "Decir que aprende solo", d: { rep: -2, red: -3, msg: "Dices que es autodidacta. El comité entiende que nadie lo supervisa, que era justo la pregunta." } },
      ] },
    { id: 17604, por: "Le mandaste un libro al analista nuevo", t: "El analista aprendió por su cuenta",
      x: "Se leyó el libro y diez más. Ya no te pregunta nada y en las reuniones te contradice con datos.",
      o: [
        { t: "Darle la razón en público", d: { red: 2, rep: 2, msg: "Lo dices en el comité: tiene razón. El joven crece un palmo y tú no pierdes nada." } },
        { t: "Ponerlo en su lugar", d: { red: -4, rep: -1, msg: "Le recuerdas quién manda. Deja de contradecirte en las reuniones y empieza a hacerlo en los pasillos." } },
        { t: "Pedirle que te enseñe lo que leyó", d: { cri: 3, red: 3, msg: "Te sientas a que te explique. Aprendes dos cosas y él otra: que también se enseña hacia arriba." } },
      ] },
    { id: 17605, por: "Convenciste a tu analista de quedarse", t: "Se quedó y despegó",
      x: "El analista que convenciste de quedarse ya lleva sus propias operaciones. Dice en público que se quedó por ti.",
      o: [
        { t: "Sumarlo a tus operaciones", d: { car: 2, red: 4, cash: 2000, msg: "Le das una parte de tus operaciones. Trabaja el doble y tú duermes un poco más." } },
        { t: "Dejar que siga su camino", d: { red: 2, ene: 2, msg: "Lo dejas crecer por su lado. Cada vez que gana algo, te escribe." } },
      ] },
    { id: 17606, por: "Convenciste a tu analista de quedarse", t: "Se quedó y se arrepintió",
      x: "La firma rival vuelve a buscarlo y esta vez no te pregunta. Se va, y en la despedida dice que debió irse antes.",
      o: [
        { t: "Despedirte con elegancia", d: { red: 2, rep: 1, msg: "Le deseas suerte y lo dices en serio. Él no lo esperaba." } },
        { t: "Reprocharle que no fue leal", d: { red: -4, rep: -2, msg: "Le reprochas. Se va igual y ahora cuenta su versión en la otra firma." } },
      ] },
  ],

  raices: {
    "54": {
      "0": { deja: "l7_dolares_al_vuelo", luego: [{ en: 1, azar: [{ p: 35, id: 17001 }, { p: 40, id: 17002 }, { p: 25, id: 17004 }] }] },
      "1": { luego: [{ en: 1, azar: [{ p: 60, id: 17003 }, { p: 40, id: 17004 }] }] },
      "2": { luego: [{ en: 1, s: "red", azar: [{ p: 40, id: 17005, bueno: true }, { p: 35, id: 17003, bueno: false }, { p: 25, id: 17004 }] }] },
    },
    "55": {
      "0": { deja: "l7_emigraste", luego: [{ en: 1, s: "red", azar: [{ p: 40, id: 17051, bueno: false }, { p: 30, id: 17052 }, { p: 30, id: 17053, bueno: true }] }] },
      "1": { deja: "l7_te_quedaste", luego: [{ en: 2, s: "red", azar: [{ p: 50, id: 17054 }, { p: 50, id: 17055, bueno: true }] }] },
    },
    "56": {
      "0": { luego: [{ en: 1, s: "red", azar: [{ p: 40, id: 17101, bueno: true }, { p: 35, id: 17103 }, { p: 25, id: 17105, bueno: false }] }] },
      "1": { luego: [{ en: 1, azar: [{ p: 50, id: 17102 }, { p: 30, id: 17103 }, { p: 20, id: 17105 }] }] },
      "2": { luego: [{ en: 1, azar: [{ p: 60, id: 17104 }, { p: 40, id: 17105 }] }] },
    },
    "60": {
      "0": { luego: [{ en: 1, azar: [{ p: 55, id: 17151 }, { p: 45, id: 17152 }] }] },
      "1": { luego: [{ en: 1, azar: [{ p: 45, id: 17153 }, { p: 55, id: 17154 }] }] },
    },
    "61": {
      "0": { luego: [{ en: 1, azar: [{ p: 35, id: 17201 }, { p: 30, id: 17202 }, { p: 35, id: 17203 }] }] },
      "1": { luego: [{ en: 2, azar: [{ p: 45, id: 17204 }, { p: 55, id: 17205 }] }] },
    },
    "62": {
      "0": { luego: [{ en: 1, azar: [{ p: 40, id: 17252 }, { p: 35, id: 17251 }, { p: 25, id: 17254 }] }] },
      "1": { luego: [{ en: 1, azar: [{ p: 40, id: 17253 }, { p: 35, id: 17254 }, { p: 25, id: 17251 }] }] },
    },
    "63": {
      "0": { luego: [{ en: 1, s: "cri", azar: [{ p: 40, id: 17301, bueno: true }, { p: 30, id: 17305, bueno: false }, { p: 30, id: 17302 }] }] },
      "1": { luego: [{ en: 2, azar: [{ p: 40, id: 17303 }, { p: 35, id: 17304 }, { p: 25, id: 17302 }] }] },
    },
    "940": {
      "0": { luego: [{ en: 1, azar: [{ p: 45, id: 17351 }, { p: 55, id: 17352 }] }] },
      "1": { luego: [{ en: 1, azar: [{ p: 55, id: 17353 }, { p: 45, id: 17354 }] }] },
    },
    "941": {
      "0": { luego: [{ en: 1, azar: [{ p: 35, id: 17401 }, { p: 30, id: 17402 }, { p: 35, id: 17403 }] }] },
      "1": { luego: [{ en: 1, azar: [{ p: 55, id: 17404 }, { p: 45, id: 17405 }] }] },
    },
    "942": {
      "0": { luego: [{ en: 1, azar: [{ p: 50, id: 17451 }, { p: 50, id: 17452 }] }] },
      "1": { luego: [{ en: 1, azar: [{ p: 55, id: 17453 }, { p: 45, id: 17454 }] }] },
    },
    "943": {
      "0": { luego: [{ en: 1, azar: [{ p: 55, id: 17501 }, { p: 45, id: 17502 }] }] },
      "1": { luego: [{ en: 1, azar: [{ p: 50, id: 17503 }, { p: 50, id: 17504 }] }] },
    },
    "950": {
      "0": { luego: [{ en: 1, azar: [{ p: 40, id: 17551 }, { p: 35, id: 17552 }, { p: 25, id: 17553 }] }] },
      "1": {
        ok: { deja: "l7_el_del_no", luego: [{ en: 1, azar: [{ p: 65, id: 17554 }, { p: 35, id: 17553 }] }] },
        no: { deja: "l7_la_que_triplico", luego: [{ en: 1, azar: [{ p: 70, id: 17555 }, { p: 30, id: 17553 }] }] },
      },
    },
    "951": {
      "0": { luego: [{ en: 2, azar: [{ p: 55, id: 17601 }, { p: 45, id: 17602 }] }] },
      "1": { luego: [{ en: 1, azar: [{ p: 40, id: 17603 }, { p: 35, id: 17604 }, { p: 25, id: 17602 }] }] },
    },
  },

  finales: [
    { id: "l7_otra_liga", huellas: ["l7_emigraste"], t: "Otra liga",
      x: "Te fuiste a Miami con una agenda que allá no servía. Armaste otra red desde cero, en otro idioma, y aprendiste que el talento viaja mejor que los contactos." },
    { id: "l7_el_del_no", huellas: ["l7_el_del_no"], t: "El que sabía decir que no",
      x: "Te ganaste tu lugar diciendo que no cuando todos querían un sí. No firmaste las peores operaciones de tu época, y nadie hace estatuas por eso." },
    { id: "l7_maestro", huellas: ["l7_maestro"], t: "El que enseñaba",
      x: "Formaste a gente que hoy decide sin ti y usa tus preguntas en el mismo orden. No es una fortuna, pero es la parte de tu carrera que sigue trabajando." },
  ],
};
